// Ella authority pages (2026-09). Same CityInfoData shape as cityInfoContent.ts.
// Reached via getEllaInfoContent() -> getCityInfoContent().
//
// Every tourCard slug is taken from the live tour list for this city.
import type { CityInfoData } from './cityInfoContent';

export function getEllaInfoContent(slug: string): CityInfoData | null {
  switch (slug) {
    case "nine-arch-bridge-guide":
      return {
        title: "The Nine Arch Bridge, Ella: How to Get There and When the Train Crosses",
        seoTitle: "Nine Arch Bridge Ella Guide",
        description: "Where to walk in from, what the train timetable actually is, the best viewpoints, and the story about the bridge being built without steel.",
        heroImage: "https://res.cloudinary.com/dx2fxyaft/image/upload/v1788368885/asiabylocals/tours/from-ella-waterfalls-abseiling-adventure-thrill-nature/img0.jpg",
        fastFacts: [
          { icon: "map", label: "Walk from Ella town", value: "About 20-25 minutes downhill through tea" },
          { icon: "train", label: "Trains cross", value: "Roughly every 2 hours; ask at Ella station for the day's times" },
          { icon: "ticket", label: "Cost", value: "Free — there is no ticket" },
          { icon: "info", label: "Built", value: "During the First World War, in stone and brick" },
          { icon: "mountain", label: "Span", value: "About 91 m long, 24 m high, nine arches" },
          { icon: "clock", label: "Best time", value: "Before 8am — after that it is busy" },
        ],
        sections: [
          {
            title: "The Nine Arch Bridge, Ella: How to Get There and When the Train Crosses",
            icon: "train",
            content: "The Nine Arch Bridge is a 91-metre stone viaduct standing 24 metres above a gorge between Ella and Demodara, and it is the single most photographed structure in Sri Lanka.\n\nThe reason it is made of stone and brick rather than steel is the interesting part, and the version most guides tell is roughly true. Construction began under the British around 1919, and the steel that had been earmarked for the bridge was requisitioned for the war effort in Europe. Rather than wait, the work was completed in solid stone, brick and cement, with no steel in the structure at all. A local builder named P. K. Appuhami is widely credited with leading the work, and Sri Lankans tell the story with some pride.\n\nIt still carries the daily trains on the Badulla line, which is what makes it worth standing under rather than just looking at. A train crossing a stone viaduct in the middle of tea country, with jungle on both sides, is the image that put Ella on most people's list.\n\nThere is no ticket and no official viewing area. You walk in, stand where you like, and wait.",
            tourCard: {
              slug: "ella-waterfall-abseiling-adventure-hotel-pickup",
              title: "Ella Waterfall Abseiling Adventure with Hotel Pickup",
              description: "Bookable directly through AsiaByLocals, with a verified local operator.",
              price: "From USD 57.71",
              duration: "4 hours",
              image: "https://res.cloudinary.com/dx2fxyaft/image/upload/v1788368885/asiabylocals/tours/from-ella-waterfalls-abseiling-adventure-thrill-nature/img0.jpg",
            },
          },
          {
            title: "Getting there: three routes in",
            icon: "map",
            content: "The usual walk starts in Ella town near the Kithalella road and drops through tea and jungle for about 20 to 25 minutes. It is downhill on the way in, which means it is uphill on the way back, in heat — worth knowing before you set off in flip-flops.\n\nThe second route is from the Demodara side, which is quieter and comes out at the far end of the bridge. Tuk-tuks will run you there for a few hundred rupees and it saves the climb back.\n\nThe third is along the railway track itself from Ella station, which many people do and which is technically walking on a live line. Trains are infrequent and slow here and locals use the track as a footpath, but it is not risk-free and it is not something to do with children or headphones on.\n\nThere are cafés on the hillside above the bridge with terraces overlooking it. They charge for a drink rather than for the view, and on a hot morning that is a fair trade.\n\nThe path gets slippery in the wet season. Trainers rather than sandals.",
            tourCard: {
              slug: "ella-to-kandy-guided-transfer-with-nuwara-eliya-ramboda-falls",
              title: "Ella to Kandy Guided Transfer with Nuwara Eliya, Ramboda Falls and Peradeniya",
              description: "Bookable directly through AsiaByLocals, with a verified local operator.",
              price: "From USD 60.67",
              duration: "8 hours",
              image: "https://res.cloudinary.com/dx2fxyaft/image/upload/v1788375678/asiabylocals/tours/ella-to-kandy-transfer-with-lakes-falls-botanical-garden/img0.jpg",
            },
          },
          {
            title: "When the train actually crosses",
            icon: "clock",
            content: "This is the question everyone gets wrong, because the published timetable and reality are different things.\n\nTrains cross roughly every two hours through the day on the Badulla line, and Sri Lanka Railways runs late as a matter of routine — delays of 30 to 90 minutes are normal rather than exceptional. Any blog post listing exact crossing times is quoting a timetable, not observing the bridge.\n\nThe reliable method is to ask at Ella station on the morning you plan to go. Staff will tell you what is expected and roughly how late it is running, and locals near the bridge track it too. Allow a generous margin and treat the wait as part of the visit.\n\nEarly morning is the best window for two reasons: the light comes across the valley rather than into your lens, and the crowds are small. By ten there can be several hundred people on and around the bridge, plus drone operators, and the atmosphere changes completely.\n\nIf you are riding the train from Nanu Oya, you cross the bridge on the way into Ella. You cannot photograph it from on board in any useful way — that is what the walk is for.",
            tourCard: {
              slug: "ella-to-kandy-transfer-with-the-hill-country-train-ride-and-nuwara-eliya",
              title: "Ella to Kandy Transfer with the Hill Country Train Ride and Nuwara Eliya",
              description: "Bookable directly through AsiaByLocals, with a verified local operator.",
              price: "From USD 65.95",
              duration: "8 hours",
              image: "https://res.cloudinary.com/dx2fxyaft/image/upload/v1788375778/asiabylocals/tours/ella-kandy-transfer-with-train-ride-nuwara-eliya-tour/img0.jpg",
            },
          },
          {
            title: "Where to stand, and drones",
            icon: "eye",
            content: "There are three positions and they give different pictures.\n\nUnder the bridge, on the grass at the base of the arches, gives you the scale and the classic upward shot with the train small along the top. This is where most people end up.\n\nOn the hillside above the northern end, where the cafés are, you get the full nine-arch profile with the train crossing left to right and jungle behind. This is the postcard.\n\nOn the bridge itself is the one people should think twice about. You can walk across it and people do, but it is a working railway with no walkway and no railing, and the deck is narrow. When a train comes, there is very little room. Every year there are close calls here, and there have been deaths on Sri Lankan railway lines involving people photographing themselves. Get off well before the train arrives, not as it does.\n\nDrone use is common and is not clearly regulated at the bridge. It also ruins the experience for everyone standing underneath, and locals have started objecting. If you fly one, fly it briefly and early.",
            tourCard: {
              slug: "ella-waterfall-abseiling-adventure-hotel-pickup",
              title: "Ella Waterfall Abseiling Adventure with Hotel Pickup",
              description: "Bookable directly through AsiaByLocals, with a verified local operator.",
              price: "From USD 57.71",
              duration: "4 hours",
              image: "https://res.cloudinary.com/dx2fxyaft/image/upload/v1788368885/asiabylocals/tours/from-ella-waterfalls-abseiling-adventure-thrill-nature/img0.jpg",
            },
          },
          {
            title: "What else is within an hour",
            icon: "map",
            content: "The bridge takes an hour including the walk and the wait, so pair it with the rest of Ella rather than making a morning of it alone.\n\n[Little Adam's Peak](/sri-lanka/ella/little-adams-peak-and-ella-rock) is the other essential and the easier of the two walks — about 45 minutes up a stepped path with the best view in the area, out through the gap in the hills towards the southern plain. Go at dawn; by nine it is a queue for the same photograph.\n\nElla Rock is the harder one: three hours return, badly signed, and genuinely easy to get lost on. Take a guide or take Little Adam's Peak.\n\nRavana Falls is ten minutes south by tuk-tuk, a broad 25-metre cascade beside the road named after the demon king of the Ramayana who is said to have hidden Sita in the caves above it. Abseiling operators run down waterfalls in the same valley.\n\nThe Demodara Loop, where the line spirals under itself to gain height, is a genuine piece of engineering curiosity a few minutes further on and almost nobody visits it.",
            tourCard: {
              slug: "udawalawe-to-kandy-private-transfer-via-ella-the-nine-arch-bridge",
              title: "Udawalawe to Kandy Private Transfer via Ella, the Nine Arch Bridge and Nuwara Eliya",
              description: "Bookable directly through AsiaByLocals, with a verified local operator.",
              price: "From USD 98.93",
              duration: "12 hours",
              image: "https://res.cloudinary.com/dx2fxyaft/image/upload/v1788375996/asiabylocals/tours/from-udawalawe-to-kandy-transfer-with-sightseeing-stops/img0.jpg",
            },
          },
        ],
        faqs: [
          { q: "How do you get to the Nine Arch Bridge from Ella?", a: "A 20-25 minute walk downhill from Ella town through tea and jungle — which means uphill on the way back, in heat. A tuk-tuk to the Demodara side is quieter and saves the climb. Walking the railway track from Ella station is common but it is a live line." },
          { q: "What time does the train cross the Nine Arch Bridge?", a: "Roughly every two hours, but Sri Lanka Railways runs 30-90 minutes late as a matter of routine, so any blog quoting exact times is quoting a timetable rather than reality. Ask at Ella station on the morning — staff will tell you what is expected and how late it is." },
          { q: "Is there an entrance fee for the Nine Arch Bridge?", a: "No. There is no ticket and no official viewing area — you walk in and stand where you like. Cafés on the hillside above charge for a drink rather than the view." },
          { q: "Can you walk on the Nine Arch Bridge?", a: "People do, but it is a working railway with no walkway and no railing, and the deck is narrow. Get off well before a train is due rather than as it arrives. There have been deaths on Sri Lankan lines involving people photographing themselves." },
          { q: "Why was the Nine Arch Bridge built without steel?", a: "Construction began around 1919 and the steel earmarked for it was requisitioned for the First World War effort. Rather than wait, the builders completed it in solid stone, brick and cement with no steel in the structure. A local builder, P. K. Appuhami, is widely credited with leading the work." },
          { q: "What is the best time to visit the Nine Arch Bridge?", a: "Before 8am. The light comes across the valley rather than into your lens, and by ten there can be several hundred people on and around it. The path is also cooler and less slippery early." },
          { q: "How long does a visit take?", a: "About an hour including the walk in, the wait for a train and the walk back up. Pair it with Little Adam's Peak at dawn and Ravana Falls in the afternoon for a full day in Ella." },
        ],
        jsonLd: {
          "@context": "https://schema.org",
          "@type": "FAQPage",
          mainEntity: [
            { "@type": "Question", name: "How do you get to the Nine Arch Bridge from Ella?", acceptedAnswer: { "@type": "Answer", text: "A 20-25 minute walk downhill from Ella town through tea and jungle — which means uphill on the way back, in heat. A tuk-tuk to the Demodara side is quieter and saves the climb. Walking the railway track from Ella station is common but it is a live line." } },
            { "@type": "Question", name: "What time does the train cross the Nine Arch Bridge?", acceptedAnswer: { "@type": "Answer", text: "Roughly every two hours, but Sri Lanka Railways runs 30-90 minutes late as a matter of routine, so any blog quoting exact times is quoting a timetable rather than reality. Ask at Ella station on the morning — staff will tell you what is expected and how late it is." } },
            { "@type": "Question", name: "Is there an entrance fee for the Nine Arch Bridge?", acceptedAnswer: { "@type": "Answer", text: "No. There is no ticket and no official viewing area — you walk in and stand where you like. Cafés on the hillside above charge for a drink rather than the view." } },
            { "@type": "Question", name: "Can you walk on the Nine Arch Bridge?", acceptedAnswer: { "@type": "Answer", text: "People do, but it is a working railway with no walkway and no railing, and the deck is narrow. Get off well before a train is due rather than as it arrives. There have been deaths on Sri Lankan lines involving people photographing themselves." } },
            { "@type": "Question", name: "Why was the Nine Arch Bridge built without steel?", acceptedAnswer: { "@type": "Answer", text: "Construction began around 1919 and the steel earmarked for it was requisitioned for the First World War effort. Rather than wait, the builders completed it in solid stone, brick and cement with no steel in the structure. A local builder, P. K. Appuhami, is widely credited with leading the work." } },
            { "@type": "Question", name: "What is the best time to visit the Nine Arch Bridge?", acceptedAnswer: { "@type": "Answer", text: "Before 8am. The light comes across the valley rather than into your lens, and by ten there can be several hundred people on and around it. The path is also cooler and less slippery early." } },
            { "@type": "Question", name: "How long does a visit take?", acceptedAnswer: { "@type": "Answer", text: "About an hour including the walk in, the wait for a train and the walk back up. Pair it with Little Adam's Peak at dawn and Ravana Falls in the afternoon for a full day in Ella." } },
          ],
        },
      };

    case "little-adams-peak-and-ella-rock":
      return {
        title: "Little Adam's Peak and Ella Rock: Which Walk to Do and How Hard They Are",
        seoTitle: "Little Adam's Peak & Ella Rock",
        description: "The two Ella walks compared honestly: 45 minutes on steps versus three hours of unsigned tracks, and why most people should take the first.",
        heroImage: "https://res.cloudinary.com/dx2fxyaft/image/upload/v1788368885/asiabylocals/tours/from-ella-waterfalls-abseiling-adventure-thrill-nature/img0.jpg",
        fastFacts: [
          { icon: "mountain", label: "Little Adam's Peak", value: "45 min up, stepped path, suitable for most" },
          { icon: "mountain", label: "Ella Rock", value: "3 hours return, unsigned, easy to get lost" },
          { icon: "clock", label: "Best start", value: "Dawn — both are exposed and hot by nine" },
          { icon: "ticket", label: "Cost", value: "Both free; a guide for Ella Rock is USD 10-20" },
          { icon: "info", label: "Little Adam's Peak height", value: "About 1,141 m" },
          { icon: "info", label: "Ella Rock height", value: "About 1,041 m, but a much longer approach" },
        ],
        sections: [
          {
            title: "Little Adam's Peak and Ella Rock: Which Walk to Do and How Hard They Are",
            icon: "mountain",
            content: "Ella has two walks and most itineraries list them as if they are comparable. They are not.\n\nLittle Adam's Peak is 45 minutes up a mostly stepped path from the edge of town, suitable for anyone reasonably mobile including children, and it delivers the best view in the area — out through the Ella Gap towards the southern plain, with tea on every slope in between. It is one of the highest returns on effort anywhere in Sri Lanka.\n\nElla Rock is three hours return, largely unsigned, follows a railway line for part of the way and then a series of unmarked tea-estate paths, and it is genuinely easy to get lost on. People do get lost on it, regularly, and locals appear at junctions offering to guide you for a fee — which is sometimes helpful and sometimes a shakedown.\n\nBoth are free. Neither has water or shade at the top.\n\nIf you have one morning in Ella, take Little Adam's Peak and use the time you saved on the [Nine Arch Bridge](/sri-lanka/ella/nine-arch-bridge-guide). If you want a proper half-day walk and you take a guide, Ella Rock is a good one.",
            tourCard: {
              slug: "ella-waterfall-abseiling-adventure-hotel-pickup",
              title: "Ella Waterfall Abseiling Adventure with Hotel Pickup",
              description: "Bookable directly through AsiaByLocals, with a verified local operator.",
              price: "From USD 57.71",
              duration: "4 hours",
              image: "https://res.cloudinary.com/dx2fxyaft/image/upload/v1788368885/asiabylocals/tours/from-ella-waterfalls-abseiling-adventure-thrill-nature/img0.jpg",
            },
          },
          {
            title: "Little Adam's Peak, step by step",
            icon: "sunrise",
            content: "The path starts about 15 minutes' walk from Ella town centre, off the Passara road near the Flower Garden hotel, and it is signed from there. Tuk-tuks will drop you at the trailhead for a few hundred rupees if you want to skip the road section.\n\nFrom the trailhead it is a gentle climb through tea estates on a made path, then a set of concrete steps for the final section. Forty-five minutes at a comfortable pace, less if you push. The steps are the only real effort and they are short.\n\nThe summit is a series of connected knolls — most people stop at the first, but walking on to the second and third takes ten more minutes and empties out considerably. There is a swing and a zip line operator up there, which some find fun and others find intrusive.\n\nGo at dawn. The path faces east, sunrise over the Ella Gap is the reason to be there, and by nine there is a queue for the same photograph. It is also 15 degrees cooler at six than at ten.\n\nTake water. There is a stall at the bottom and nothing above it.",
            tourCard: {
              slug: "ella-waterfall-abseiling-adventure-hotel-pickup",
              title: "Ella Waterfall Abseiling Adventure with Hotel Pickup",
              description: "Bookable directly through AsiaByLocals, with a verified local operator.",
              price: "From USD 57.71",
              duration: "4 hours",
              image: "https://res.cloudinary.com/dx2fxyaft/image/upload/v1788368885/asiabylocals/tours/from-ella-waterfalls-abseiling-adventure-thrill-nature/img0.jpg",
            },
          },
          {
            title: "Ella Rock, and why people get lost",
            icon: "mountain",
            content: "The standard route starts at Ella railway station, follows the track southwest for about 20 minutes, crosses a small bridge, and then leaves the line onto a path through tea and eucalyptus before climbing to the summit ridge.\n\nThe getting-lost happens at the point where you leave the railway. There is no sign, there are several plausible paths, and the correct one is not the obvious one. From there the route crosses estate land where paths branch constantly.\n\nWhat this means practically: either take a guide, download an offline map with the route on it before you go, or accept that you will probably be steered by a local who then asks for money. None of those is unreasonable; arriving with none of them is how people end up wandering tea slopes for four hours.\n\nThe walk itself is not technically hard — it is a long uphill on rough ground, three hours return at a moderate pace. The summit is open grass with a big view back over Ella and the Gap.\n\nWalking the railway is part of the standard route and locals use the line constantly. Trains are slow and infrequent here, but stay off the sleepers and listen.",
            tourCard: {
              slug: "ella-to-kandy-guided-transfer-with-nuwara-eliya-ramboda-falls",
              title: "Ella to Kandy Guided Transfer with Nuwara Eliya, Ramboda Falls and Peradeniya",
              description: "Bookable directly through AsiaByLocals, with a verified local operator.",
              price: "From USD 60.67",
              duration: "8 hours",
              image: "https://res.cloudinary.com/dx2fxyaft/image/upload/v1788375678/asiabylocals/tours/ella-to-kandy-transfer-with-lakes-falls-botanical-garden/img0.jpg",
            },
          },
          {
            title: "What to take, and when not to go",
            icon: "info",
            content: "Shoes with grip for both. The tea-estate paths on Ella Rock and the upper steps on Little Adam's Peak are slippery after rain, and Ella gets afternoon rain in most months.\n\nAt least a litre of water each, more for Ella Rock. There is nothing to buy on either route once you leave town.\n\nStart at first light. Both walks are exposed, this is the tropics, and the difference between 6am and 10am is not marginal.\n\nLeeches appear on the Ella Rock route in the wet season, mostly in the wooded section. Long socks deal with them.\n\nDo not do Ella Rock in poor visibility. The summit route crosses open ground with steep drops and the path is hard enough to follow in clear weather.\n\nBoth walks are fine to do alone in terms of safety, and both are done by hundreds of people a week. The risk on Ella Rock is navigational, not personal.",
            tourCard: {
              slug: "udawalawe-to-kandy-private-transfer-via-ella-the-nine-arch-bridge",
              title: "Udawalawe to Kandy Private Transfer via Ella, the Nine Arch Bridge and Nuwara Eliya",
              description: "Bookable directly through AsiaByLocals, with a verified local operator.",
              price: "From USD 98.93",
              duration: "12 hours",
              image: "https://res.cloudinary.com/dx2fxyaft/image/upload/v1788375996/asiabylocals/tours/from-udawalawe-to-kandy-transfer-with-sightseeing-stops/img0.jpg",
            },
          },
          {
            title: "Fitting the walks into an Ella stay",
            icon: "clock",
            content: "Two nights in Ella is the right length and it maps neatly onto the two mornings.\n\nMorning one: Little Adam's Peak at dawn, back for breakfast, then the [Nine Arch Bridge](/sri-lanka/ella/nine-arch-bridge-guide) mid-morning when a train is due. Afternoon at Ravana Falls or abseiling in the same valley, both ten minutes south.\n\nMorning two: Ella Rock with a guide, back by lunch, and an afternoon doing nothing — which after several days of Sri Lankan driving is a legitimate use of a day.\n\nIf you have one night, take Little Adam's Peak and the bridge and skip Ella Rock without regret.\n\nElla is small: one main street, walkable end to end in ten minutes, with everything else within a few kilometres by tuk-tuk. It is also the most backpacker-heavy place in Sri Lanka, which is either part of the appeal or a reason to stay a few kilometres out.",
            tourCard: {
              slug: "ella-to-kandy-transfer-with-the-hill-country-train-ride-and-nuwara-eliya",
              title: "Ella to Kandy Transfer with the Hill Country Train Ride and Nuwara Eliya",
              description: "Bookable directly through AsiaByLocals, with a verified local operator.",
              price: "From USD 65.95",
              duration: "8 hours",
              image: "https://res.cloudinary.com/dx2fxyaft/image/upload/v1788375778/asiabylocals/tours/ella-kandy-transfer-with-train-ride-nuwara-eliya-tour/img0.jpg",
            },
          },
        ],
        faqs: [
          { q: "How hard is Little Adam's Peak?", a: "Easy. About 45 minutes up a mostly stepped path from the edge of town, suitable for most fitness levels and for children. The concrete steps at the end are the only real effort and they are short." },
          { q: "How long does Ella Rock take?", a: "About three hours return at a moderate pace. It is not technically hard but the route is largely unsigned, crosses estate land where paths branch constantly, and people get lost on it regularly." },
          { q: "Do I need a guide for Ella Rock?", a: "Take one, or an offline map with the route loaded. The critical point is where the path leaves the railway line — there is no sign and the correct path is not the obvious one. Locals appear at junctions offering to guide you, which is sometimes helpful and sometimes a shakedown." },
          { q: "Which is better, Little Adam's Peak or Ella Rock?", a: "Little Adam's Peak for almost everyone: a fraction of the effort for arguably the better view, out through the Ella Gap. Ella Rock is worth it if you want a proper half-day walk and you take a guide." },
          { q: "What time should I start?", a: "First light. Both walks are exposed with no shade at the top, this is the tropics, and by nine Little Adam's Peak has a queue for the same photograph. It is also considerably cooler." },
          { q: "Is it safe to walk the railway line to Ella Rock?", a: "It is the standard route and locals use the line constantly — trains here are slow and infrequent. Stay off the sleepers, listen, and do not walk it with headphones on. The real risk on Ella Rock is navigational rather than personal." },
          { q: "Are the walks free?", a: "Yes, both. There is no ticket for either. A guide for Ella Rock runs roughly USD 10-20, and there is a stall at the bottom of Little Adam's Peak but nothing above it — carry water." },
        ],
        jsonLd: {
          "@context": "https://schema.org",
          "@type": "FAQPage",
          mainEntity: [
            { "@type": "Question", name: "How hard is Little Adam's Peak?", acceptedAnswer: { "@type": "Answer", text: "Easy. About 45 minutes up a mostly stepped path from the edge of town, suitable for most fitness levels and for children. The concrete steps at the end are the only real effort and they are short." } },
            { "@type": "Question", name: "How long does Ella Rock take?", acceptedAnswer: { "@type": "Answer", text: "About three hours return at a moderate pace. It is not technically hard but the route is largely unsigned, crosses estate land where paths branch constantly, and people get lost on it regularly." } },
            { "@type": "Question", name: "Do I need a guide for Ella Rock?", acceptedAnswer: { "@type": "Answer", text: "Take one, or an offline map with the route loaded. The critical point is where the path leaves the railway line — there is no sign and the correct path is not the obvious one. Locals appear at junctions offering to guide you, which is sometimes helpful and sometimes a shakedown." } },
            { "@type": "Question", name: "Which is better, Little Adam's Peak or Ella Rock?", acceptedAnswer: { "@type": "Answer", text: "Little Adam's Peak for almost everyone: a fraction of the effort for arguably the better view, out through the Ella Gap. Ella Rock is worth it if you want a proper half-day walk and you take a guide." } },
            { "@type": "Question", name: "What time should I start?", acceptedAnswer: { "@type": "Answer", text: "First light. Both walks are exposed with no shade at the top, this is the tropics, and by nine Little Adam's Peak has a queue for the same photograph. It is also considerably cooler." } },
            { "@type": "Question", name: "Is it safe to walk the railway line to Ella Rock?", acceptedAnswer: { "@type": "Answer", text: "It is the standard route and locals use the line constantly — trains here are slow and infrequent. Stay off the sleepers, listen, and do not walk it with headphones on. The real risk on Ella Rock is navigational rather than personal." } },
            { "@type": "Question", name: "Are the walks free?", acceptedAnswer: { "@type": "Answer", text: "Yes, both. There is no ticket for either. A guide for Ella Rock runs roughly USD 10-20, and there is a stall at the bottom of Little Adam's Peak but nothing above it — carry water." } },
          ],
        },
      };

    case "ella-city-guide":
      return {
        title: "Ella Guide: What to Do, Where It Gets Busy and How Long to Stay",
        seoTitle: "Ella Guide, Sri Lanka",
        description: "A guide to Ella: the two walks, the Nine Arch Bridge, Ravana Falls, the tea estates, and an honest word about how crowded the town has become.",
        heroImage: "https://res.cloudinary.com/dx2fxyaft/image/upload/v1788368885/asiabylocals/tours/from-ella-waterfalls-abseiling-adventure-thrill-nature/img0.jpg",
        fastFacts: [
          { icon: "clock", label: "How long to stay", value: "Two nights; one if you are only doing the bridge" },
          { icon: "map", label: "Altitude", value: "About 1,041 m — cool nights, warm days" },
          { icon: "map", label: "Town size", value: "One main street, walkable end to end in 10 minutes" },
          { icon: "train", label: "Reached by", value: "The hill line from Nanu Oya, about 4 hours" },
          { icon: "info", label: "Busiest", value: "December to March; book ahead" },
          { icon: "mountain", label: "The two walks", value: "Little Adam's Peak (easy), Ella Rock (hard)" },
        ],
        sections: [
          {
            title: "Ella Guide: What to Do, Where It Gets Busy and How Long to Stay",
            icon: "map",
            content: "Ella is a single street in a gap between two ridges, at just over a thousand metres, surrounded by tea. Twenty years ago it was a few guesthouses. It is now the most concentrated backpacker town in Sri Lanka, and that is the first thing an honest guide should say.\n\nWhat has not changed is why people come. The gap the town sits in — the Ella Gap — opens south towards the plain, and on a clear morning you can see a long way from almost anywhere above the town. The walking is genuinely good and starts from the street. The train arrives across a stone viaduct through jungle. The tea estates begin at the edge of town.\n\nWhat has changed is the density. The main street is cafés, tour desks and hostels, prices are noticeably higher than anywhere else in the hill country, and the two headline sights have crowds on them by mid-morning.\n\nBoth things are true at once. Ella earns its reputation and it is not a quiet mountain village. Staying a few kilometres out, and doing everything before nine in the morning, gets you most of the first and very little of the second.",
            tourCard: {
              slug: "ella-waterfall-abseiling-adventure-hotel-pickup",
              title: "Ella Waterfall Abseiling Adventure with Hotel Pickup",
              description: "Bookable directly through AsiaByLocals, with a verified local operator.",
              price: "From USD 57.71",
              duration: "4 hours",
              image: "https://res.cloudinary.com/dx2fxyaft/image/upload/v1788368885/asiabylocals/tours/from-ella-waterfalls-abseiling-adventure-thrill-nature/img0.jpg",
            },
          },
          {
            title: "The essential four",
            icon: "sparkles",
            content: "[Little Adam's Peak](/sri-lanka/ella/little-adams-peak-and-ella-rock). Forty-five minutes up a stepped path from the edge of town, the best view in the area out through the Ella Gap, and easy enough for most people and for children. Go at dawn.\n\nThe [Nine Arch Bridge](/sri-lanka/ella/nine-arch-bridge-guide). A 91-metre stone viaduct 24 metres above a gorge, built without steel during the First World War because the steel went to Europe. A 20-minute walk down from town, free, and best before eight when the light is right and the crowd is not there yet. Trains cross roughly every two hours and run late as a matter of routine — ask at the station.\n\nRavana Falls. A broad 25-metre cascade beside the road ten minutes south, named after the demon king of the Ramayana who is said to have hidden Sita in the caves above it. Roadside, so easy, and busy for the same reason.\n\nElla Rock. Three hours return, unsigned, and easy to get lost on. Worth it with a guide, skippable without one.\n\nBeyond those: waterfall abseiling in the Ravana valley, a working tea factory, and the Demodara Loop where the railway spirals under itself to gain height.",
            tourCard: {
              slug: "ella-waterfall-abseiling-adventure-hotel-pickup",
              title: "Ella Waterfall Abseiling Adventure with Hotel Pickup",
              description: "Bookable directly through AsiaByLocals, with a verified local operator.",
              price: "From USD 57.71",
              duration: "4 hours",
              image: "https://res.cloudinary.com/dx2fxyaft/image/upload/v1788368885/asiabylocals/tours/from-ella-waterfalls-abseiling-adventure-thrill-nature/img0.jpg",
            },
          },
          {
            title: "Tea, and where to actually see it made",
            icon: "leaf",
            content: "Ella sits in the Uva province tea district, which produces a distinct style — Uva teas are grown with a dry seasonal wind blowing across them from June to September, and the resulting leaf has a character tasters can identify blind.\n\nThere are working factories within a few kilometres, and a proper visit walks you from the withering troughs through rolling, oxidation and firing to the grading table in about forty-five minutes. The point is not the tasting at the end but the explanation of why one bush produces six graded products that sell at wildly different prices.\n\nFactories close on poya days, the monthly full moons, which catches people out. If your one free day is a poya, an estate walk with a plucker is the substitute and is arguably more interesting anyway.\n\nThe plucking itself happens in the morning. Walking out into the estates before nine, you will see the work being done; by afternoon the slopes are empty.\n\nBuy tea at a factory rather than in town if you want the good grades. The shops on the main street sell to visitors at visitor prices.",
            tourCard: {
              slug: "ella-to-kandy-guided-transfer-with-nuwara-eliya-ramboda-falls",
              title: "Ella to Kandy Guided Transfer with Nuwara Eliya, Ramboda Falls and Peradeniya",
              description: "Bookable directly through AsiaByLocals, with a verified local operator.",
              price: "From USD 60.67",
              duration: "8 hours",
              image: "https://res.cloudinary.com/dx2fxyaft/image/upload/v1788375678/asiabylocals/tours/ella-to-kandy-transfer-with-lakes-falls-botanical-garden/img0.jpg",
            },
          },
          {
            title: "Eating and staying",
            icon: "utensils",
            content: "Ella's main street is the most internationalised food in Sri Lanka outside Colombo — smoothie bowls, pizza, banana pancakes. It is fine, it is not why you came, and it costs two to three times what the same meal costs elsewhere in the country.\n\nThe better eating is the rice and curry at the small local places set back from the strip, and the roti stalls. Kottu in the evening, as everywhere. Buffalo curd with treacle for dessert.\n\nOn accommodation, the practical advice is to stay slightly out. Guesthouses on the slopes above town and along the Passara road are quieter, cooler at night, usually have the view, and are five minutes by tuk-tuk from the street. Places on the main strip are convenient and loud.\n\nBook ahead between December and March. Ella fills up in a way most Sri Lankan towns do not, and the good-value places go first.\n\nNights are cool at 1,000 metres — not cold like Nuwara Eliya, but you will want a layer after dark, and few places have heating or hot water that is reliably hot.",
            tourCard: {
              slug: "udawalawe-to-kandy-private-transfer-via-ella-the-nine-arch-bridge",
              title: "Udawalawe to Kandy Private Transfer via Ella, the Nine Arch Bridge and Nuwara Eliya",
              description: "Bookable directly through AsiaByLocals, with a verified local operator.",
              price: "From USD 98.93",
              duration: "12 hours",
              image: "https://res.cloudinary.com/dx2fxyaft/image/upload/v1788375996/asiabylocals/tours/from-udawalawe-to-kandy-transfer-with-sightseeing-stops/img0.jpg",
            },
          },
          {
            title: "How long, and what Ella is not",
            icon: "clock",
            content: "Two nights is right. That gives you two dawns, which is what the town is for: [Little Adam's Peak](/sri-lanka/ella/little-adams-peak-and-ella-rock) on one and either Ella Rock or the bridge on the other, with afternoons for the falls, a tea factory or nothing.\n\nOne night works if you arrive on the afternoon train, do the bridge that evening and Little Adam's Peak at dawn before moving on. It is tight but common.\n\nThree nights is only worth it if you are walking seriously or genuinely want to stop moving, which after the standard Sri Lankan loop is a real thing to want.\n\nWhat Ella is not: a base for the south coast (Mirissa is four hours), a base for safari (Udawalawe is two hours and is better done on the way out), or a quiet retreat. It is a small, busy, beautifully-sited walking town, and taken as that it is one of the best stops in the country.\n\nThe single best piece of planning advice: whatever you do here, do it before nine in the morning.",
            tourCard: {
              slug: "ella-to-kandy-transfer-with-the-hill-country-train-ride-and-nuwara-eliya",
              title: "Ella to Kandy Transfer with the Hill Country Train Ride and Nuwara Eliya",
              description: "Bookable directly through AsiaByLocals, with a verified local operator.",
              price: "From USD 65.95",
              duration: "8 hours",
              image: "https://res.cloudinary.com/dx2fxyaft/image/upload/v1788375778/asiabylocals/tours/ella-kandy-transfer-with-train-ride-nuwara-eliya-tour/img0.jpg",
            },
          },
        ],
        faqs: [
          { q: "How many days do you need in Ella?", a: "Two nights. That gives you two dawns — Little Adam's Peak on one, the Nine Arch Bridge or Ella Rock on the other — with afternoons for Ravana Falls, a tea factory or nothing. One night works if you arrive on the afternoon train." },
          { q: "Is Ella too touristy?", a: "It is the most concentrated backpacker town in Sri Lanka and the main street is cafés and tour desks. That is real. The walking, the tea country and the setting are also real. Staying a few kilometres out and doing everything before nine gets you the good half." },
          { q: "What is the best thing to do in Ella?", a: "Little Adam's Peak at dawn — 45 minutes up a stepped path for the best view in the area, out through the Ella Gap. The Nine Arch Bridge is the other essential, best before eight when the light works and the crowds have not arrived." },
          { q: "Is Ella cold at night?", a: "Cool rather than cold at just over 1,000 metres — you will want a layer after dark, but nothing like Nuwara Eliya at 1,900 m. Few guesthouses have heating, and hot water is not always reliably hot." },
          { q: "Where should I stay in Ella?", a: "Slightly out of town. Guesthouses on the slopes above and along the Passara road are quieter, cooler, usually have the view, and are five minutes by tuk-tuk from the street. Book ahead December to March." },
          { q: "Can I visit a tea factory from Ella?", a: "Yes, several are within a few kilometres, and a proper visit takes about 45 minutes from the withering troughs to the grading table. They close on poya days — if your free day is a full moon, take an estate walk instead." },
          { q: "Is Ella a good base for the south coast or a safari?", a: "No. Mirissa is about four hours away and Udawalawe two, and both are better done on the way out rather than as day trips. Ella is a walking town — treat it as one." },
        ],
        jsonLd: {
          "@context": "https://schema.org",
          "@type": "FAQPage",
          mainEntity: [
            { "@type": "Question", name: "How many days do you need in Ella?", acceptedAnswer: { "@type": "Answer", text: "Two nights. That gives you two dawns — Little Adam's Peak on one, the Nine Arch Bridge or Ella Rock on the other — with afternoons for Ravana Falls, a tea factory or nothing. One night works if you arrive on the afternoon train." } },
            { "@type": "Question", name: "Is Ella too touristy?", acceptedAnswer: { "@type": "Answer", text: "It is the most concentrated backpacker town in Sri Lanka and the main street is cafés and tour desks. That is real. The walking, the tea country and the setting are also real. Staying a few kilometres out and doing everything before nine gets you the good half." } },
            { "@type": "Question", name: "What is the best thing to do in Ella?", acceptedAnswer: { "@type": "Answer", text: "Little Adam's Peak at dawn — 45 minutes up a stepped path for the best view in the area, out through the Ella Gap. The Nine Arch Bridge is the other essential, best before eight when the light works and the crowds have not arrived." } },
            { "@type": "Question", name: "Is Ella cold at night?", acceptedAnswer: { "@type": "Answer", text: "Cool rather than cold at just over 1,000 metres — you will want a layer after dark, but nothing like Nuwara Eliya at 1,900 m. Few guesthouses have heating, and hot water is not always reliably hot." } },
            { "@type": "Question", name: "Where should I stay in Ella?", acceptedAnswer: { "@type": "Answer", text: "Slightly out of town. Guesthouses on the slopes above and along the Passara road are quieter, cooler, usually have the view, and are five minutes by tuk-tuk from the street. Book ahead December to March." } },
            { "@type": "Question", name: "Can I visit a tea factory from Ella?", acceptedAnswer: { "@type": "Answer", text: "Yes, several are within a few kilometres, and a proper visit takes about 45 minutes from the withering troughs to the grading table. They close on poya days — if your free day is a full moon, take an estate walk instead." } },
            { "@type": "Question", name: "Is Ella a good base for the south coast or a safari?", acceptedAnswer: { "@type": "Answer", text: "No. Mirissa is about four hours away and Udawalawe two, and both are better done on the way out rather than as day trips. Ella is a walking town — treat it as one." } },
          ],
        },
      };

    case "getting-to-ella":
      return {
        title: "Getting to Ella: The Train, the Road, and Which One to Take",
        seoTitle: "Getting to Ella, Sri Lanka",
        description: "Kandy, Nuwara Eliya, Colombo or the south coast to Ella: real journey times, the train booking window, and the luggage problem nobody mentions.",
        heroImage: "https://res.cloudinary.com/dx2fxyaft/image/upload/v1788375778/asiabylocals/tours/ella-kandy-transfer-with-train-ride-nuwara-eliya-tour/img0.jpg",
        fastFacts: [
          { icon: "train", label: "Nanu Oya to Ella by train", value: "About 4 hours — the scenic section" },
          { icon: "train", label: "Kandy to Ella by train", value: "6-7 hours scheduled, routinely later" },
          { icon: "car", label: "Kandy to Ella by road", value: "140 km, 4-5 hours" },
          { icon: "car", label: "Colombo to Ella by road", value: "About 6 hours" },
          { icon: "ticket", label: "Reserved seats", value: "Open 30 days ahead; sell out in hours Dec-Mar" },
          { icon: "info", label: "Nuwara Eliya station", value: "There isn't one — use Nanu Oya, 10 km away" },
        ],
        sections: [
          {
            title: "Getting to Ella: The Train, the Road, and Which One to Take",
            icon: "train",
            content: "Almost everyone arrives in Ella by train, and almost everyone should — but not necessarily for the whole journey.\n\nThe hill line runs Kandy to Nanu Oya to Ella to Badulla, and the section people photograph is the last one: Nanu Oya to Ella, about four hours through the highest tea estates on the island, crossing the [Nine Arch Bridge](/sri-lanka/ella/nine-arch-bridge-guide) on the way in. The first half, Kandy to Nanu Oya, is pleasant and unremarkable, and it takes two to three hours.\n\nThat is the whole decision. If you have time and want the full six to seven hours of it, ride from Kandy. If you would rather see Ramboda Falls, a working tea factory and Nuwara Eliya on the way, drive that half with stops and pick the train up at Nanu Oya. Most people who have done both recommend the second.\n\nThe train is slow, frequently late, and one of the best rail journeys anywhere. Treat it as the day's activity rather than as transport, and it never disappoints. Treat it as a way to get somewhere by a certain time and it will.",
            tourCard: {
              slug: "ella-to-kandy-transfer-with-the-hill-country-train-ride-and-nuwara-eliya",
              title: "Ella to Kandy Transfer with the Hill Country Train Ride and Nuwara Eliya",
              description: "Bookable directly through AsiaByLocals, with a verified local operator.",
              price: "From USD 65.95",
              duration: "8 hours",
              image: "https://res.cloudinary.com/dx2fxyaft/image/upload/v1788375778/asiabylocals/tours/ella-kandy-transfer-with-train-ride-nuwara-eliya-tour/img0.jpg",
            },
          },
          {
            title: "Booking: the 30-day window and what to do when you miss it",
            icon: "ticket",
            content: "Reserved seats — first, second and third class — open exactly 30 days before departure. Between December and March they sell out within hours of opening. If you want a guaranteed seat you need to be organised a month ahead or book through an agent who does it for you.\n\nMissing that window is normal and it is not a disaster. Unreserved second and third class are sold at the station on the day and are never sold out, because there is no seat limit — people stand. This is where the open doorways are, where you can sit on the steps with your legs out, and where nearly every photograph you have seen of this train was taken.\n\nFirst class observation carriages are the trap. Air conditioning, sealed windows, rear-facing seats, no door access. Comfortable, and the wrong choice for a journey whose entire point is the view.\n\nIf you take unreserved, be on the platform 30 to 45 minutes early for any chance of a seat, and accept that you may stand for four hours. Most people end up saying it was better that way.",
            tourCard: {
              slug: "ella-to-kandy-transfer-with-the-hill-country-train-ride-and-nuwara-eliya",
              title: "Ella to Kandy Transfer with the Hill Country Train Ride and Nuwara Eliya",
              description: "Bookable directly through AsiaByLocals, with a verified local operator.",
              price: "From USD 65.95",
              duration: "8 hours",
              image: "https://res.cloudinary.com/dx2fxyaft/image/upload/v1788375778/asiabylocals/tours/ella-kandy-transfer-with-train-ride-nuwara-eliya-tour/img0.jpg",
            },
          },
          {
            title: "The luggage problem",
            icon: "info",
            content: "This is the practical detail that ruins the ride for people who did not plan for it.\n\nUnreserved carriages are crowded and there is nowhere sensible to put a large suitcase. You will be standing in a doorway for hours with a bag you cannot put down, and the romance of the open door disappears very quickly.\n\nIf you have a driver, the standard and correct arrangement is that the car takes your luggage on to Ella by road while you ride with a day bag. Every driver in Sri Lanka understands this request and most will suggest it themselves.\n\nWithout a driver, the options are to travel light, to use the luggage van if the service has one, or to book a reserved seat where there is at least a rack. Guesthouses in Ella and Nanu Oya will also hold or forward bags for a fee.\n\nOne more: Nuwara Eliya has no railway station. The stop is Nanu Oya, 10 kilometres and a 20-30 minute drive from the town, and tuk-tuk fares there rise sharply the moment a train arrives.",
            tourCard: {
              slug: "ella-to-kandy-guided-transfer-with-nuwara-eliya-ramboda-falls",
              title: "Ella to Kandy Guided Transfer with Nuwara Eliya, Ramboda Falls and Peradeniya",
              description: "Bookable directly through AsiaByLocals, with a verified local operator.",
              price: "From USD 60.67",
              duration: "8 hours",
              image: "https://res.cloudinary.com/dx2fxyaft/image/upload/v1788375678/asiabylocals/tours/ella-to-kandy-transfer-with-lakes-falls-botanical-garden/img0.jpg",
            },
          },
          {
            title: "By road, from every direction",
            icon: "car",
            content: "Kandy to Ella is 140 kilometres and four to five hours. The road climbs to Nuwara Eliya then drops, and it bends continuously — take something if you are prone to motion sickness.\n\nColombo to Ella is about six hours and is a long day; almost nobody does it in one go and almost nobody should.\n\nNuwara Eliya to Ella is about two hours, and it is the shortest useful leg on the hill route.\n\nFrom the south coast, Mirissa or Galle to Ella is four to five hours through Udawalawe country, which is why a safari stop on the way makes sense in either direction.\n\nUdawalawe to Ella is two hours and pairs naturally with a morning game drive.\n\nA car with a driver runs roughly USD 55-75 a day including fuel. For a one-way move, a guided transfer with stops costs little more than a plain transfer and turns five hours of driving into the day's sightseeing — which on this particular route, past Ramboda Falls and the tea estates, is worth doing.",
            tourCard: {
              slug: "udawalawe-to-kandy-private-transfer-via-ella-the-nine-arch-bridge",
              title: "Udawalawe to Kandy Private Transfer via Ella, the Nine Arch Bridge and Nuwara Eliya",
              description: "Bookable directly through AsiaByLocals, with a verified local operator.",
              price: "From USD 98.93",
              duration: "12 hours",
              image: "https://res.cloudinary.com/dx2fxyaft/image/upload/v1788375996/asiabylocals/tours/from-udawalawe-to-kandy-transfer-with-sightseeing-stops/img0.jpg",
            },
          },
          {
            title: "Onward from Ella",
            icon: "map",
            content: "Ella is the natural hinge of a Sri Lankan loop, and where you go next largely decides the shape of the trip.\n\nSouth to Udawalawe and the coast is the standard continuation: a morning safari at Udawalawe, two hours on, and you are at Mirissa or Tangalle by mid-afternoon. This is the route most seven-day itineraries take.\n\nNorth back to Kandy is four to five hours and is worth doing as a guided transfer with Nuwara Eliya, a tea factory and Ramboda Falls built in, rather than as a plain drive.\n\nEast to Arugam Bay is about three hours and is the right call between May and September, when the east coast is the dry side of the island and the south is not.\n\nThe train continues to Badulla, an hour further, which almost no visitors do and which is a quiet, pleasant hour if you want the line to yourself.\n\nWhichever direction, book transport the day before. Ella is small and the good drivers are busy.",
            tourCard: {
              slug: "udawalawe-to-kandy-private-transfer-via-ella-the-nine-arch-bridge",
              title: "Udawalawe to Kandy Private Transfer via Ella, the Nine Arch Bridge and Nuwara Eliya",
              description: "Bookable directly through AsiaByLocals, with a verified local operator.",
              price: "From USD 98.93",
              duration: "12 hours",
              image: "https://res.cloudinary.com/dx2fxyaft/image/upload/v1788375996/asiabylocals/tours/from-udawalawe-to-kandy-transfer-with-sightseeing-stops/img0.jpg",
            },
          },
        ],
        faqs: [
          { q: "Should I take the train from Kandy or from Nanu Oya?", a: "From Nanu Oya, for most people. The scenic section is Nanu Oya to Ella, about four hours; the Kandy to Nanu Oya half is pleasant but ordinary and takes two to three hours. Drive that half with stops at Ramboda Falls and a tea factory instead." },
          { q: "How far ahead do I need to book the Ella train?", a: "Reserved seats open exactly 30 days before departure and sell out within hours between December and March. Unreserved second and third class are sold on the day and always available — you will stand, which is where the open doorways and the photographs are." },
          { q: "Is first class worth it on the Ella train?", a: "No. The observation carriage has sealed windows, air conditioning and rear-facing seats, and you cannot reach the open doorways. It is the most comfortable and the worst choice for the view." },
          { q: "What do I do with my luggage on the train?", a: "If you have a driver, send it ahead by road — every driver understands this and most suggest it. Otherwise travel light or book a reserved seat with a rack. Unreserved carriages are crowded with nowhere to put a suitcase, and standing for four hours holding one is miserable." },
          { q: "How long is Kandy to Ella by road?", a: "140 km and four to five hours — the road climbs to Nuwara Eliya then drops, bending continuously. A guided transfer with Ramboda Falls, a tea factory and Nuwara Eliya built in costs little more than a plain one and turns the drive into the day." },
          { q: "Which station do I use for Nuwara Eliya?", a: "Nanu Oya, about 10 km and a 20-30 minute drive from the town. Nuwara Eliya has no station of its own. Tuk-tuk fares at Nanu Oya rise sharply the moment a train arrives." },
          { q: "Where should I go after Ella?", a: "South is the standard continuation — a morning safari at Udawalawe two hours away, then on to the south coast by mid-afternoon. East to Arugam Bay is the right call from May to September, when the east is the dry side of the island." },
        ],
        jsonLd: {
          "@context": "https://schema.org",
          "@type": "FAQPage",
          mainEntity: [
            { "@type": "Question", name: "Should I take the train from Kandy or from Nanu Oya?", acceptedAnswer: { "@type": "Answer", text: "From Nanu Oya, for most people. The scenic section is Nanu Oya to Ella, about four hours; the Kandy to Nanu Oya half is pleasant but ordinary and takes two to three hours. Drive that half with stops at Ramboda Falls and a tea factory instead." } },
            { "@type": "Question", name: "How far ahead do I need to book the Ella train?", acceptedAnswer: { "@type": "Answer", text: "Reserved seats open exactly 30 days before departure and sell out within hours between December and March. Unreserved second and third class are sold on the day and always available — you will stand, which is where the open doorways and the photographs are." } },
            { "@type": "Question", name: "Is first class worth it on the Ella train?", acceptedAnswer: { "@type": "Answer", text: "No. The observation carriage has sealed windows, air conditioning and rear-facing seats, and you cannot reach the open doorways. It is the most comfortable and the worst choice for the view." } },
            { "@type": "Question", name: "What do I do with my luggage on the train?", acceptedAnswer: { "@type": "Answer", text: "If you have a driver, send it ahead by road — every driver understands this and most suggest it. Otherwise travel light or book a reserved seat with a rack. Unreserved carriages are crowded with nowhere to put a suitcase, and standing for four hours holding one is miserable." } },
            { "@type": "Question", name: "How long is Kandy to Ella by road?", acceptedAnswer: { "@type": "Answer", text: "140 km and four to five hours — the road climbs to Nuwara Eliya then drops, bending continuously. A guided transfer with Ramboda Falls, a tea factory and Nuwara Eliya built in costs little more than a plain one and turns the drive into the day." } },
            { "@type": "Question", name: "Which station do I use for Nuwara Eliya?", acceptedAnswer: { "@type": "Answer", text: "Nanu Oya, about 10 km and a 20-30 minute drive from the town. Nuwara Eliya has no station of its own. Tuk-tuk fares at Nanu Oya rise sharply the moment a train arrives." } },
            { "@type": "Question", name: "Where should I go after Ella?", acceptedAnswer: { "@type": "Answer", text: "South is the standard continuation — a morning safari at Udawalawe two hours away, then on to the south coast by mid-afternoon. East to Arugam Bay is the right call from May to September, when the east is the dry side of the island." } },
          ],
        },
      };

    case "best-time-to-visit-ella":
      return {
        title: "Best Time to Visit Ella: Cloud, Rain and the Months the View Disappears",
        seoTitle: "Best Time to Visit Ella",
        description: "Ella sits between Sri Lanka's two monsoons and gets rain from both. When the Ella Gap view is reliable, when the hills are in cloud, and what to expect month by month.",
        heroImage: "https://res.cloudinary.com/dx2fxyaft/image/upload/v1788368885/asiabylocals/tours/from-ella-waterfalls-abseiling-adventure-thrill-nature/img0.jpg",
        fastFacts: [
          { icon: "calendar-days", label: "Clearest views", value: "January to March" },
          { icon: "calendar-days", label: "Uva's dry wind season", value: "June to September — dry but hazy and windy" },
          { icon: "calendar-days", label: "Wettest", value: "October to December" },
          { icon: "calendar-days", label: "Temperature", value: "Around 16-27C; cool nights year-round" },
          { icon: "cloud", label: "The real risk", value: "Cloud, not rain — it hides the Gap view" },
          { icon: "calendar-days", label: "Busiest", value: "December to March; book ahead" },
        ],
        sections: [
          {
            title: "Best Time to Visit Ella: Cloud, Rain and the Months the View Disappears",
            icon: "calendar-days",
            content: "Ella is in Uva province, on the eastern flank of the central highlands, and it sits awkwardly between Sri Lanka's two monsoon systems. The southwest monsoon, which soaks Colombo and the west from May to September, mostly spends itself on the far side of the mountains before it gets here. The northeast monsoon, which covers the north and east from October to January, reaches Ella more directly.\n\nThat gives Ella a rain pattern unlike either coast: a genuinely wet stretch from October to December, a clear window from January to March, and a dry but strange period from June to September when the Uva wind blows.\n\nThe thing to plan around, though, is not rain. It is cloud. Ella's whole appeal is the view south through the Ella Gap and out over the tea, and at a thousand metres that view is regularly inside a cloud. You can have a dry day with nothing visible from [Little Adam's Peak](/sri-lanka/ella/little-adams-peak-and-ella-rock). Mornings are reliably clearer than afternoons in every month, which is the single most useful fact on this page.\n\nTemperatures barely move: 16 to 27 degrees year-round, cool at night, never cold.",
            table: {
              headers: ["Months", "Rain", "Cloud / views", "Verdict"],
              rows: [["Jan-Mar", "Low", "Clearest of the year", "Best; busiest"], ["Apr-May", "Building storms", "Variable", "Hot; New Year closures mid-April"], ["Jun-Sep", "Dry (Uva wind)", "Hazy but open", "Good for walking"], ["Oct-Dec", "Wettest", "Often clouded in", "Green, cheap, gamble on views"]],
            },
            tourCard: {
              slug: "ella-waterfall-abseiling-adventure-hotel-pickup",
              title: "Ella Waterfall Abseiling Adventure with Hotel Pickup",
              description: "Bookable directly through AsiaByLocals, with a verified local operator.",
              price: "From USD 57.71",
              duration: "4 hours",
              image: "https://res.cloudinary.com/dx2fxyaft/image/upload/v1788368885/asiabylocals/tours/from-ella-waterfalls-abseiling-adventure-thrill-nature/img0.jpg",
            },
          },
          {
            title: "January to March: the clear window",
            icon: "sun",
            content: "These are the best months and the busiest. The northeast monsoon has finished with Uva, the air is clearest, and the Ella Gap view is reliable in a way it is not at other times of year. Mornings are frequently cloudless.\n\nThis is also when the whole island is in season — the west and south coasts are dry, the hill country is clear, and everyone is doing the same loop. Ella fills up. Guesthouses on the main street book out, reserved train seats vanish within hours of the 30-day window opening, and prices are at their annual high.\n\nFebruary is the pick if you want one month. Rainfall is at its lowest, the crowds are marginally below the December-January peak, and the tea slopes are still green from the wet season.\n\nBook accommodation and, if you want a reserved train seat, do it a month ahead. This is the one place in Sri Lanka where turning up without a plan in high season genuinely costs you.",
            tourCard: {
              slug: "ella-to-kandy-transfer-with-the-hill-country-train-ride-and-nuwara-eliya",
              title: "Ella to Kandy Transfer with the Hill Country Train Ride and Nuwara Eliya",
              description: "Bookable directly through AsiaByLocals, with a verified local operator.",
              price: "From USD 65.95",
              duration: "8 hours",
              image: "https://res.cloudinary.com/dx2fxyaft/image/upload/v1788375778/asiabylocals/tours/ella-kandy-transfer-with-train-ride-nuwara-eliya-tour/img0.jpg",
            },
          },
          {
            title: "June to September: dry, windy and hazy",
            icon: "wind",
            content: "The southwest monsoon largely misses Ella, which means these months are dry here while Colombo is being drenched — a useful inversion for anyone travelling in the European summer.\n\nWhat arrives instead is the Uva wind: a persistent dry wind that blows across the province from around June to September and is what gives Uva tea its distinctive character. It also raises haze, so while it does not rain much, the long views are often soft rather than sharp. Photographers notice; most visitors do not.\n\nThe walking is at its best in this window — dry paths, no leeches, and cooler air moving. [Ella Rock](/sri-lanka/ella/little-adams-peak-and-ella-rock) in particular is much more pleasant in a dry August than a wet November.\n\nThe crowds are moderate. This is not peak season for Sri Lanka as a whole, so Ella is busy without being full, and prices sit below the winter peak.\n\nFor a trip built around the cultural triangle and the east coast, which are also dry in these months, Ella fits perfectly as the hill-country stop.",
            tourCard: {
              slug: "ella-to-kandy-guided-transfer-with-nuwara-eliya-ramboda-falls",
              title: "Ella to Kandy Guided Transfer with Nuwara Eliya, Ramboda Falls and Peradeniya",
              description: "Bookable directly through AsiaByLocals, with a verified local operator.",
              price: "From USD 60.67",
              duration: "8 hours",
              image: "https://res.cloudinary.com/dx2fxyaft/image/upload/v1788375678/asiabylocals/tours/ella-to-kandy-transfer-with-lakes-falls-botanical-garden/img0.jpg",
            },
          },
          {
            title: "October to December: the wet months",
            icon: "cloud-rain",
            content: "October and November are Ella's wettest and least predictable stretch, as the second inter-monsoon and then the northeast monsoon arrive. Rain comes in heavy afternoon bursts, the paths turn slippery, and leeches appear on the Ella Rock route and in the wooded sections.\n\nMore to the point, this is when the cloud sits lowest. There are days in November when [Little Adam's Peak](/sri-lanka/ella/little-adams-peak-and-ella-rock) has no view at all, and the walk up is still pleasant but the reason for it is missing.\n\nWhat you get in return is the greenest the tea country ever looks, the fewest visitors of the year, the lowest prices, and waterfalls at full volume — Ravana Falls in November is a different thing from Ravana Falls in March.\n\nBy mid-December the pattern usually breaks toward the dry season, and the first half of December can be very good value: near-dry weather at pre-Christmas prices.\n\nIf you are travelling in these months, plan for two mornings rather than one. The odds of at least one clear dawn are much better across two days than one.",
            tourCard: {
              slug: "udawalawe-to-kandy-private-transfer-via-ella-the-nine-arch-bridge",
              title: "Udawalawe to Kandy Private Transfer via Ella, the Nine Arch Bridge and Nuwara Eliya",
              description: "Bookable directly through AsiaByLocals, with a verified local operator.",
              price: "From USD 98.93",
              duration: "12 hours",
              image: "https://res.cloudinary.com/dx2fxyaft/image/upload/v1788375996/asiabylocals/tours/from-udawalawe-to-kandy-transfer-with-sightseeing-stops/img0.jpg",
            },
          },
          {
            title: "April, May and the practical rules",
            icon: "calendar-days",
            content: "April is hot by hill-country standards and brings the Sinhala and Tamil New Year in the middle of the month — the biggest holiday of the year, when domestic tourism surges and many small businesses close for several days. Ella gets busy with Sri Lankan visitors rather than foreign ones, which is a different and rather good atmosphere if you plan around the closures.\n\nMay is the start of the southwest monsoon and the least reliable of the drier months, with afternoon storms building.\n\nAcross every month, three rules hold. Do the walks at dawn: mornings are clearer than afternoons in every season, without exception. Carry a rain layer regardless of forecast, because the hills make their own weather. And take a warm layer for the evening — Ella is never cold, but at a thousand metres it drops enough after dark to matter.\n\nIf you have only one morning here and it is clouded in, the [Nine Arch Bridge](/sri-lanka/ella/nine-arch-bridge-guide) is unaffected — it sits below the cloud line and works in any weather.",
            tourCard: {
              slug: "ella-waterfall-abseiling-adventure-hotel-pickup",
              title: "Ella Waterfall Abseiling Adventure with Hotel Pickup",
              description: "Bookable directly through AsiaByLocals, with a verified local operator.",
              price: "From USD 57.71",
              duration: "4 hours",
              image: "https://res.cloudinary.com/dx2fxyaft/image/upload/v1788368885/asiabylocals/tours/from-ella-waterfalls-abseiling-adventure-thrill-nature/img0.jpg",
            },
          },
        ],
        faqs: [
          { q: "What is the best month to visit Ella?", a: "February. It has the clearest air and the most reliable Ella Gap view, and it sits just past the December-January price peak. January and March are close behind." },
          { q: "Does it rain a lot in Ella?", a: "October to December is genuinely wet. June to September is dry but hazy, because of the Uva wind. The bigger issue than rain is cloud — at 1,000 m the view can be inside a cloud on a dry day, and mornings are clearer than afternoons in every month." },
          { q: "Is Ella worth visiting in the rainy season?", a: "Yes, with lowered expectations for the views. The tea country is at its greenest, waterfalls are at full volume, prices are lowest and crowds are thinnest. Plan two mornings rather than one — the odds of catching a clear dawn are much better across two days." },
          { q: "How cold does Ella get?", a: "Around 16-27C year-round. Cool after dark rather than cold — you will want a layer in the evening, but nothing like Nuwara Eliya at 1,900 m. Few guesthouses have heating." },
          { q: "Does the southwest monsoon affect Ella?", a: "Much less than the west coast. The mountains take most of it, so June to September is dry in Ella while Colombo is being drenched — a useful inversion for a European summer trip. What you get instead is the dry Uva wind and some haze." },
          { q: "When is Ella busiest?", a: "December to March, when the whole island is in season. Guesthouses on the main street book out, reserved train seats vanish within hours of the 30-day window opening, and prices peak. Book ahead." },
          { q: "What if the weather is bad on my only day in Ella?", a: "The Nine Arch Bridge sits below the cloud line and works in any weather, as do the tea factories, Ravana Falls and the abseiling. It is the ridge views from Little Adam's Peak and Ella Rock that cloud takes away." },
        ],
        jsonLd: {
          "@context": "https://schema.org",
          "@type": "FAQPage",
          mainEntity: [
            { "@type": "Question", name: "What is the best month to visit Ella?", acceptedAnswer: { "@type": "Answer", text: "February. It has the clearest air and the most reliable Ella Gap view, and it sits just past the December-January price peak. January and March are close behind." } },
            { "@type": "Question", name: "Does it rain a lot in Ella?", acceptedAnswer: { "@type": "Answer", text: "October to December is genuinely wet. June to September is dry but hazy, because of the Uva wind. The bigger issue than rain is cloud — at 1,000 m the view can be inside a cloud on a dry day, and mornings are clearer than afternoons in every month." } },
            { "@type": "Question", name: "Is Ella worth visiting in the rainy season?", acceptedAnswer: { "@type": "Answer", text: "Yes, with lowered expectations for the views. The tea country is at its greenest, waterfalls are at full volume, prices are lowest and crowds are thinnest. Plan two mornings rather than one — the odds of catching a clear dawn are much better across two days." } },
            { "@type": "Question", name: "How cold does Ella get?", acceptedAnswer: { "@type": "Answer", text: "Around 16-27C year-round. Cool after dark rather than cold — you will want a layer in the evening, but nothing like Nuwara Eliya at 1,900 m. Few guesthouses have heating." } },
            { "@type": "Question", name: "Does the southwest monsoon affect Ella?", acceptedAnswer: { "@type": "Answer", text: "Much less than the west coast. The mountains take most of it, so June to September is dry in Ella while Colombo is being drenched — a useful inversion for a European summer trip. What you get instead is the dry Uva wind and some haze." } },
            { "@type": "Question", name: "When is Ella busiest?", acceptedAnswer: { "@type": "Answer", text: "December to March, when the whole island is in season. Guesthouses on the main street book out, reserved train seats vanish within hours of the 30-day window opening, and prices peak. Book ahead." } },
            { "@type": "Question", name: "What if the weather is bad on my only day in Ella?", acceptedAnswer: { "@type": "Answer", text: "The Nine Arch Bridge sits below the cloud line and works in any weather, as do the tea factories, Ravana Falls and the abseiling. It is the ridge views from Little Adam's Peak and Ella Rock that cloud takes away." } },
          ],
        },
      };

    case "ella-2-day-itinerary":
      return {
        title: "Two Days in Ella: Both Dawns Used Properly",
        seoTitle: "Ella 2-Day Itinerary",
        description: "A two-day Ella plan built around the two mornings: Little Adam's Peak at dawn, the Nine Arch Bridge before eight, and afternoons that ask nothing of you.",
        heroImage: "https://res.cloudinary.com/dx2fxyaft/image/upload/v1788368885/asiabylocals/tours/from-ella-waterfalls-abseiling-adventure-thrill-nature/img0.jpg",
        fastFacts: [
          { icon: "clock", label: "Day 1", value: "Little Adam's Peak at dawn, Nine Arch Bridge, Ravana Falls" },
          { icon: "clock", label: "Day 2", value: "Ella Rock with a guide, or a tea estate morning" },
          { icon: "ticket", label: "Cost of the sights", value: "Almost nothing — both walks and the bridge are free" },
          { icon: "clock", label: "The one rule", value: "Everything before nine in the morning" },
          { icon: "map", label: "Stay", value: "A few km out for quiet and the view" },
          { icon: "info", label: "Book ahead", value: "December to March, both rooms and train seats" },
        ],
        sections: [
          {
            title: "Two Days in Ella: Both Dawns Used Properly",
            icon: "clock",
            content: "Ella's sights are free, close together and small in number, which means the plan is not about fitting things in. It is about being awake early.\n\nEverything here is better before nine. The Ella Gap view is clearer in the morning in every month of the year. [Little Adam's Peak](/sri-lanka/ella/little-adams-peak-and-ella-rock) has a queue for the same photograph by nine. The [Nine Arch Bridge](/sri-lanka/ella/nine-arch-bridge-guide) has hundreds of people on it by ten. The tea pluckers are in the field in the morning and gone by afternoon.\n\nSo the itinerary below uses both mornings hard and asks nothing of the afternoons, which after several days of Sri Lankan driving is the point of stopping here at all.\n\nTwo nights is the right length. One works if you arrive on the afternoon train. Three is only worth it if you are walking seriously or genuinely want to stop.",
            tourCard: {
              slug: "ella-waterfall-abseiling-adventure-hotel-pickup",
              title: "Ella Waterfall Abseiling Adventure with Hotel Pickup",
              description: "Bookable directly through AsiaByLocals, with a verified local operator.",
              price: "From USD 57.71",
              duration: "4 hours",
              image: "https://res.cloudinary.com/dx2fxyaft/image/upload/v1788368885/asiabylocals/tours/from-ella-waterfalls-abseiling-adventure-thrill-nature/img0.jpg",
            },
          },
          {
            title: "Day 1, dawn: Little Adam's Peak",
            icon: "sunrise",
            content: "Leave your guesthouse in the dark. The trailhead is about fifteen minutes' walk from the centre off the Passara road, or a few hundred rupees by tuk-tuk.\n\nFrom there it is a gentle climb through tea on a made path, then concrete steps for the last section — 45 minutes at a comfortable pace, easy enough for children and for most fitness levels. Sunrise comes up through the Ella Gap and it is the reason people put this town on a list.\n\nWalk on past the first knoll. Most people stop there; the second and third are ten minutes further and considerably emptier.\n\nBack in town by eight for breakfast.\n\nTake water — there is a stall at the bottom and nothing above it — and shoes with grip, because the steps are slippery after overnight rain, which is most nights in some months.",
            tourCard: {
              slug: "ella-waterfall-abseiling-adventure-hotel-pickup",
              title: "Ella Waterfall Abseiling Adventure with Hotel Pickup",
              description: "Bookable directly through AsiaByLocals, with a verified local operator.",
              price: "From USD 57.71",
              duration: "4 hours",
              image: "https://res.cloudinary.com/dx2fxyaft/image/upload/v1788368885/asiabylocals/tours/from-ella-waterfalls-abseiling-adventure-thrill-nature/img0.jpg",
            },
          },
          {
            title: "Day 1, mid-morning: the Nine Arch Bridge",
            icon: "train",
            content: "Ask at Ella station what time the next train is expected and how late it is running — the published timetable and reality are different things, and staff will tell you both.\n\nThe walk in from town takes 20 to 25 minutes, downhill through tea and jungle, which means uphill on the way back. A tuk-tuk to the Demodara side is quieter and saves the climb.\n\nThe bridge is a 91-metre stone viaduct, 24 metres above a gorge, built during the First World War without any steel because the steel went to Europe. It is free, there is no official viewing area, and you stand where you like.\n\nThree positions: underneath for scale, the hillside cafés above for the full nine-arch profile with a train crossing, and on the bridge itself — which is a working railway with no walkway, so get off well before a train is due rather than as it arrives.\n\nBefore eight is best. By ten there are several hundred people and a queue of drones.",
            tourCard: {
              slug: "ella-to-kandy-transfer-with-the-hill-country-train-ride-and-nuwara-eliya",
              title: "Ella to Kandy Transfer with the Hill Country Train Ride and Nuwara Eliya",
              description: "Bookable directly through AsiaByLocals, with a verified local operator.",
              price: "From USD 65.95",
              duration: "8 hours",
              image: "https://res.cloudinary.com/dx2fxyaft/image/upload/v1788375778/asiabylocals/tours/ella-kandy-transfer-with-train-ride-nuwara-eliya-tour/img0.jpg",
            },
          },
          {
            title: "Day 1, afternoon: falls, abseiling, or nothing",
            icon: "waves",
            content: "Ravana Falls is ten minutes south by tuk-tuk, a broad 25-metre cascade right beside the road, named after the demon king of the Ramayana who is said to have hidden Sita in the caves above it. It is roadside and therefore easy and therefore busy; in the wet season it is genuinely powerful.\n\nAbseiling operators work waterfalls in the same valley and it is the one real adventure activity in Ella — a guided descent down a falls face with all equipment provided, no experience needed.\n\nOr do nothing. There are cafés with terraces looking down the Gap, and after four or five days of the standard Sri Lankan loop, an afternoon that involves no vehicle is a legitimate plan.\n\nEvening: eat rice and curry at one of the small local places set back from the main strip rather than on it. The strip does smoothie bowls and pizza at two to three times the national price; the food you came for is a street back.",
            tourCard: {
              slug: "ella-waterfall-abseiling-adventure-hotel-pickup",
              title: "Ella Waterfall Abseiling Adventure with Hotel Pickup",
              description: "Bookable directly through AsiaByLocals, with a verified local operator.",
              price: "From USD 57.71",
              duration: "4 hours",
              image: "https://res.cloudinary.com/dx2fxyaft/image/upload/v1788368885/asiabylocals/tours/from-ella-waterfalls-abseiling-adventure-thrill-nature/img0.jpg",
            },
          },
          {
            title: "Day 2: Ella Rock, or the tea",
            icon: "mountain",
            content: "The ambitious version is [Ella Rock](/sri-lanka/ella/little-adams-peak-and-ella-rock): three hours return, starting along the railway from Ella station, leaving the line at an unsigned junction and climbing through tea and eucalyptus to an open summit ridge. Take a guide or an offline map — the junction is where people get lost, and they get lost regularly. It is not technically hard, just long and unmarked.\n\nThe gentler version is a tea morning. Walk out into the estates before nine and you will see plucking actually happening; by afternoon the slopes are empty. A working factory visit takes 45 minutes from the withering troughs to the grading table and explains why one bush yields six graded products at wildly different prices. Factories close on poya days, when an estate walk substitutes.\n\nThe Demodara Loop, where the railway spirals under itself to gain height, is a few minutes on and is a real curiosity that almost nobody visits.\n\nAfternoon: leave, or don't. If you are moving on, book the vehicle the day before — Ella is small and the good drivers are busy.",
            tourCard: {
              slug: "ella-to-kandy-guided-transfer-with-nuwara-eliya-ramboda-falls",
              title: "Ella to Kandy Guided Transfer with Nuwara Eliya, Ramboda Falls and Peradeniya",
              description: "Bookable directly through AsiaByLocals, with a verified local operator.",
              price: "From USD 60.67",
              duration: "8 hours",
              image: "https://res.cloudinary.com/dx2fxyaft/image/upload/v1788375678/asiabylocals/tours/ella-to-kandy-transfer-with-lakes-falls-botanical-garden/img0.jpg",
            },
          },
          {
            title: "Where to go next",
            icon: "map",
            content: "South is the standard continuation and the best one: a 6am game drive at Udawalawe, two hours away, then two hours more to the south coast, arriving mid-afternoon with the beach day intact. Udawalawe is the dependable elephant park — open all year, far fewer jeeps than Yala, near-certain sightings.\n\nNorth back to Kandy is four to five hours, and worth doing as a guided transfer with Nuwara Eliya, a tea factory and Ramboda Falls built in rather than as a plain drive.\n\nEast to Arugam Bay is about three hours and is the right call from May to September, when the east coast is the dry side of the island.\n\nThe train continues to Badulla, an hour on, which almost nobody does and which is a quiet, pleasant hour if you want the line to yourself.\n\nWhichever way you go, the sightseeing on this island is usually better built into the transfer than bought as a separate day trip.",
            tourCard: {
              slug: "udawalawe-to-kandy-private-transfer-via-ella-the-nine-arch-bridge",
              title: "Udawalawe to Kandy Private Transfer via Ella, the Nine Arch Bridge and Nuwara Eliya",
              description: "Bookable directly through AsiaByLocals, with a verified local operator.",
              price: "From USD 98.93",
              duration: "12 hours",
              image: "https://res.cloudinary.com/dx2fxyaft/image/upload/v1788375996/asiabylocals/tours/from-udawalawe-to-kandy-transfer-with-sightseeing-stops/img0.jpg",
            },
          },
        ],
        faqs: [
          { q: "How many days do you need in Ella?", a: "Two nights, which gives you two dawns — Little Adam's Peak on one and either Ella Rock or a tea morning on the other, with the Nine Arch Bridge mid-morning on day one. One night works if you arrive on the afternoon train." },
          { q: "What is the single most important thing to know about visiting Ella?", a: "Do everything before nine in the morning. The Ella Gap view is clearer in the morning in every month, Little Adam's Peak has a queue by nine, and the Nine Arch Bridge has hundreds of people on it by ten." },
          { q: "How much does two days in Ella cost?", a: "Very little for the sights themselves — both walks and the bridge are free. Budget for accommodation, food, tuk-tuks at a few hundred rupees a hop, and optionally a guide for Ella Rock at USD 10-20 or an abseiling session." },
          { q: "Should I do Ella Rock or a tea estate morning on day two?", a: "Ella Rock if you want a proper walk and you take a guide or an offline map. A tea morning if you would rather see the estates working — go out before nine, when the pluckers are in the field." },
          { q: "Where do I go after Ella?", a: "South is the standard route: a 6am Udawalawe safari two hours away, then two hours more to the south coast, arriving with the afternoon intact. North to Kandy is four to five hours and better as a guided transfer with stops than a plain drive." },
          { q: "Do I need to book anything in advance for Ella?", a: "Between December and March, yes — both accommodation and reserved train seats, which open 30 days ahead and go within hours. Outside those months you can usually turn up. Book onward transport the day before whatever the season." },
          { q: "What if it is cloudy?", a: "The Nine Arch Bridge sits below the cloud line and works in any weather, as do the tea factories, Ravana Falls and abseiling. Only the ridge views from the two walks are lost to cloud, and mornings are clearer than afternoons in every month." },
        ],
        jsonLd: {
          "@context": "https://schema.org",
          "@type": "FAQPage",
          mainEntity: [
            { "@type": "Question", name: "How many days do you need in Ella?", acceptedAnswer: { "@type": "Answer", text: "Two nights, which gives you two dawns — Little Adam's Peak on one and either Ella Rock or a tea morning on the other, with the Nine Arch Bridge mid-morning on day one. One night works if you arrive on the afternoon train." } },
            { "@type": "Question", name: "What is the single most important thing to know about visiting Ella?", acceptedAnswer: { "@type": "Answer", text: "Do everything before nine in the morning. The Ella Gap view is clearer in the morning in every month, Little Adam's Peak has a queue by nine, and the Nine Arch Bridge has hundreds of people on it by ten." } },
            { "@type": "Question", name: "How much does two days in Ella cost?", acceptedAnswer: { "@type": "Answer", text: "Very little for the sights themselves — both walks and the bridge are free. Budget for accommodation, food, tuk-tuks at a few hundred rupees a hop, and optionally a guide for Ella Rock at USD 10-20 or an abseiling session." } },
            { "@type": "Question", name: "Should I do Ella Rock or a tea estate morning on day two?", acceptedAnswer: { "@type": "Answer", text: "Ella Rock if you want a proper walk and you take a guide or an offline map. A tea morning if you would rather see the estates working — go out before nine, when the pluckers are in the field." } },
            { "@type": "Question", name: "Where do I go after Ella?", acceptedAnswer: { "@type": "Answer", text: "South is the standard route: a 6am Udawalawe safari two hours away, then two hours more to the south coast, arriving with the afternoon intact. North to Kandy is four to five hours and better as a guided transfer with stops than a plain drive." } },
            { "@type": "Question", name: "Do I need to book anything in advance for Ella?", acceptedAnswer: { "@type": "Answer", text: "Between December and March, yes — both accommodation and reserved train seats, which open 30 days ahead and go within hours. Outside those months you can usually turn up. Book onward transport the day before whatever the season." } },
            { "@type": "Question", name: "What if it is cloudy?", acceptedAnswer: { "@type": "Answer", text: "The Nine Arch Bridge sits below the cloud line and works in any weather, as do the tea factories, Ravana Falls and abseiling. Only the ridge views from the two walks are lost to cloud, and mornings are clearer than afternoons in every month." } },
          ],
        },
      };

    default:
      return null;
  }
}
