// Generated from indonesia_itineraries_content.json — do not hand-edit.
// Every tour URL here was checked against the live tour list before writing,
// so a reader clicking through from a day never lands on a 404.
import type { ItineraryData } from './japanItineraries';

export const INDONESIA_ITINERARIES: Record<string, ItineraryData> = {
  "3-days": {
    days: 3,
    title: "3 Days in Bali: Ubud and One Sunset in the South",
    metaTitle: "3 Day Bali Itinerary | AsiaByLocals",
    metaDescription: "A realistic 3 day Bali itinerary: two days based in Ubud for the terraces, temples and a Batur sunrise, then Uluwatu for the cliffs and the Kecak, planned around Nyepi and the tide.",
    routeSummary: "Ubud → Ubud → Uluwatu",
    intro: "Three days in Bali is enough for the interior and one evening on the coast, and not enough for the islands. This route gives Ubud two days, because that is where the terraces, the temples and the volcano are, and finishes at Uluwatu for a sunset that the whole island is arranged around. Nusa Penida is left out on purpose: from Ubud it is a twelve-hour day, and on a three-day trip that day is a third of your holiday spent in a van and a boat.\n\nTwo things to check before anything is booked. First, the date of Nyepi, the Balinese day of silence in March, when the airport closes and no one may leave their hotel for twenty-four hours; a three-day trip that lands on it loses a day. Second, whether your dates are dry season, April to October, when the Batur sunrise is a good bet, or wet season, when it is a gamble on cloud and the jeep is the fallback.",
    bestFor: "Stopovers, long weekends, and first visits where the interior matters more than the beach.",
    quickAnswer: "With three days, give Ubud two of them and finish in the south. Day 1: Tegallalang before 8:30, Tirta Empul, the Monkey Forest late. Day 2: the Mount Batur sunrise trek from a 2am pickup, hot springs, waterfalls in the afternoon. Day 3: drive to Uluwatu, a cliff cove at the right tide, and the Kecak fire dance at the temple at sunset. Three days is enough for the interior and one coast evening, not for Nusa Penida.",
    days_detail: [
      {
        day: 1,
        base: "Ubud",
        heading: "Terraces early, temples after, Monkey Forest at the end",
        narrative: "Be at Tegallalang before 8:30, when the light is low across the wet paddies and the road above them is still empty of coaches; by ten it is a queue for the swings. Walk down into the terraces rather than photographing them from the cafes. Then north-east along the Pakerisan river to Tirta Empul, where the purification pools are calm before the late-morning crowd, and if the legs allow it, Gunung Kawi's rock-cut shrines at the bottom of three hundred steps.\n\nBack in Ubud for a late lunch and the Monkey Forest in the last two hours of the afternoon, when the macaques are active again after the heat. Zip the bag, put the sunglasses inside it, and do not carry food. Early night: tomorrow starts at two.",
        tours: ["/indonesia/ubud/half-day-tirta-empul-purification-and-gunung-kawi-temple-in-ubud", "/indonesia/ubud/tirta-empul-kanto-lampo-waterfall-rice-terraces-and-swings-in-ubud"],
        travel: "Airport to Ubud about 1.5 hours; book a fixed-price transfer.",
        tip: "Wear a sarong-friendly outfit for the temples; sarongs are provided at the gate but shoulders should already be covered.",
      },
      {
        day: 2,
        base: "Ubud",
        heading: "Batur sunrise, hot springs, and an afternoon of waterfalls",
        narrative: "Pickup at two in the morning for the drive to Toya Bungkah and a two-hour climb by torchlight to the rim of Mount Batur at 1,717 metres. Bring a real jacket: the summit before dawn is regularly under 12°C and you will stand still in it. Sunrise comes up behind Mount Agung across the lake, breakfast is eggs cooked in the steam vents, and the walk down is in full sun by half past seven. The hot springs on the lake shore are where the morning becomes worth it for whoever did not enjoy the cold. Anyone who does not want the climb takes the jeep to the flank viewpoint for the same sunrise.\n\nSleep until early afternoon. Then the eastern waterfalls: Tibumana for the pretty one, Kanto Lampo for the photograph, and skip Tukad Cepung today because its light beams only work between nine and eleven in the morning.",
        tours: ["/indonesia/ubud/shared-mount-batur-sunrise-jeep-tour-with-hot-springs", "/indonesia/ubud/mount-batur-shared-sunrise-jeep-and-natural-hot-springs"],
        travel: "Ubud to the Batur trailhead about 1.25 hours each way.",
        tip: "Trekking on Batur is guided-only through the village association; every tour includes it, so a quote that seems to exclude the trek fee is a quote to question.",
      },
      {
        day: 3,
        base: "Uluwatu",
        heading: "South to the cliffs, a cove, and the Kecak at sunset",
        narrative: "Leave Ubud by nine for the two-hour drive to the Bukit peninsula, and go straight to a cove while the tide is right: Padang Padang or Balangan at mid to high tide for swimming, both reached by cliff stairs with no shade, so carry water down. Lunch above Suluban watching the surfers on the Uluwatu reef.\n\nBe through the temple gate by half past four. Sunglasses and hats go in the bag before you enter; the macaques here take them off heads and trade them for food. Walk the cliff path while the light is good, then be in the amphitheatre by five for a seat on the left side, which faces the sun. The Kecak starts around six: fifty men chanting in rings, the Ramayana acted out in front of them, and Hanuman kicking real fire around the arena as the sun goes into the sea.",
        tours: ["/indonesia/uluwatu/uluwatu-sunset-magic-kecak-padang-padang-cliff-and-dinner-uluwatu", "/indonesia/uluwatu/uluwatu-temple-tour-with-sunset-kecak-fire-dance"],
        travel: "Ubud to Uluwatu about 2 hours; Uluwatu to the airport 30 to 40 minutes in the morning, over an hour from midday.",
        tip: "Kecak tickets are separate from temple entry and sell out on busy evenings; the tours listed here include them.",
      },
    ],
    logistics: [
      { heading: "Getting around", content: "Bali's roads are slow: thirty kilometres is an hour, and the lanes out of Ubud and into the Bukit jam from mid-morning. The whole route works on a private driver for eight to ten hours a day, usually forty to sixty US dollars for the car with fuel, which is what every driver-based tour on this site is built on. Ride-hailing apps drop you in Ubud but often refuse pickups in the centre; they work normally in the south." },
      { heading: "Where to stay", content: "Two nights in Ubud and the last night in Uluwatu, or fly out that evening if the flight is late; Uluwatu is thirty to forty minutes from the airport before the traffic builds. If the flight is early morning, sleep in Jimbaran or Seminyak instead, which are closer still." },
      { heading: "Nyepi", content: "The Balinese day of silence falls in March on a date that moves with the lunar calendar. The airport closes, no one leaves their hotel, and lights and noise are forbidden for twenty-four hours. The parade of demon effigies the night before is spectacular; the day itself is a day of hotel. Check the date before booking March." },
    ],
    faqs: [
      { question: "Is 3 days enough for Bali?", answer: "Enough for Ubud and one evening in the south, which is what this route does. It is not enough for Nusa Penida, which is a twelve-hour day from Ubud, or for the east coast. Treat three days as a first look and plan to come back." },
      { question: "Should I stay in Ubud or on the coast for 3 days?", answer: "Ubud, for two of the three nights. The terraces, temples and Batur are all there, and the south coast is best done as a final afternoon and evening ending at the Uluwatu temple." },
      { question: "Can I do Nusa Penida in a 3 day Bali trip?", answer: "Only by giving up a full day to it: an hour to Sanur, a 45-minute boat, the island's rough roads, and the same back. On three days that is a third of the trip in transit. Five days is where Penida fits." },
      { question: "What if my 3 days include Nyepi?", answer: "One of them is spent inside your hotel: no going out, no lights, no airport. Either move the dates or accept it and see the ogoh-ogoh parade the evening before, which is worth the trade for some people." },
    ],
  },
  "5-days": {
    days: 5,
    title: "5 Days in Bali: Ubud, Nusa Penida and the Cliffs of Uluwatu",
    metaTitle: "5 Day Bali Itinerary | AsiaByLocals",
    metaDescription: "A 5 day Bali itinerary that fits the island's three best days: Ubud's terraces and a Batur sunrise, a full day on Nusa Penida from the south coast, and Uluwatu's coves and Kecak.",
    routeSummary: "Ubud → Ubud → Uluwatu → Nusa Penida → Uluwatu",
    intro: "Five days is the first length at which Bali stops being a compromise. Two days in Ubud cover the interior properly, and moving to the south coast for the last three puts you forty-five minutes from Sanur harbour, which is what makes a Nusa Penida day possible without a four o'clock alarm and twelve hours of transit.\n\nThe order matters. Ubud first, because the Batur sunrise is best done rested and the terraces are best seen before the coaches. Then Uluwatu as the base for Penida and for the sunset temple. Canggu's surf and cafes are left out of this version; they fit at seven days.",
    bestFor: "First visits that want the volcano, the terraces and the islands without rushing any of them.",
    quickAnswer: "Five days fits Bali's three best days. Two nights in Ubud for the terraces, river temples and a Batur sunrise; then move to Uluwatu, which puts Sanur harbour 45 minutes away for a full Nusa Penida west-side day (Kelingking, Broken Beach, Angel's Billabong, Crystal Bay) by the first boat; the Kecak at sunset and a cove by the tide fill the rest. Canggu's surf is the trade-off; it fits at seven days.",
    days_detail: [
      {
        day: 1,
        base: "Ubud",
        heading: "Tegallalang at dawn, the river temples, and the Monkey Forest",
        narrative: "The terraces before 8:30, walking down into them rather than staying on the road. Then Tirta Empul for the purification pools while they are quiet, done properly if you go in: changing rooms, the green sarong, the spouts left to right, skipping the ones for the dead. Gunung Kawi's rock-cut shrines are up the same river and worth the three hundred steps if the day is not already hot.\n\nThe Monkey Forest in the late afternoon, bag zipped, no food, sunglasses inside. Dinner early; tomorrow starts at two.",
        tours: ["/indonesia/ubud/half-day-tirta-empul-purification-and-gunung-kawi-temple-in-ubud", "/indonesia/ubud/bali-hidden-hidden-canyon-tirta-empul-and-gunung-kawi-ubud"],
        travel: "Airport to Ubud about 1.5 hours.",
        tip: "Sarongs are provided at every temple and included in the entry; cover shoulders as well.",
      },
      {
        day: 2,
        base: "Ubud",
        heading: "Mount Batur sunrise, then the waterfalls in the right order",
        narrative: "Two in the morning pickup, a two-hour climb by torchlight to the rim, and a summit that is under 12°C while you wait for the sun to come up behind Agung. A proper jacket is the difference between a great morning and a miserable one. Eggs in the steam vents, the walk down in sun, the hot springs on the lake.\n\nSleep, then the eastern waterfall loop timed correctly: Tukad Cepung is out because its cave light only works before eleven, so Tibumana and Kanto Lampo, close together, one for the setting and one for the photograph. The jeep to the Batur flank is the honest alternative for anyone not walking.",
        tours: ["/indonesia/ubud/mount-batur-sunrise-hike-and-tibumana-waterfall", "/indonesia/ubud/shared-mount-batur-sunrise-jeep-tour-with-hot-springs"],
        travel: "Ubud to Toya Bungkah about 1.25 hours each way.",
        tip: "Wet season, November to March, often puts the summit in cloud; if dates are flexible, book the first clear-looking morning.",
      },
      {
        day: 3,
        base: "Uluwatu",
        heading: "Down to the Bukit: a cove by the tide, and the Kecak",
        narrative: "Drive south after breakfast, two hours to the peninsula, and pick the cove by the tide: Padang Padang or Balangan at mid to high, Melasti at low for the shallows. Every cove except Melasti is a staircase down the cliff with no shade; water goes down with you.\n\nThe temple gate by half past four, everything loose zipped away before the macaques see it, the cliff walk in the good light, and a seat on the left of the amphitheatre by five for the Kecak at six. Dinner at Jimbaran's fish grills on the sand, twenty minutes away, if there is energy left.",
        tours: ["/indonesia/uluwatu/kecak-fire-dance-temple-and-jimbaran-seafood-dinner", "/indonesia/uluwatu/uluwatu-sunset-magic-kecak-padang-padang-cliff-and-dinner-uluwatu"],
        travel: "Ubud to Uluwatu about 2 hours.",
        tip: "Sit on the left side of the Kecak amphitheatre as you enter; it faces the sunset. Those seats go first.",
      },
      {
        day: 4,
        base: "Nusa Penida (day trip)",
        heading: "Nusa Penida's west: Kelingking, Broken Beach, Angel's Billabong, Crystal Bay",
        narrative: "Pickup at six, Sanur harbour by seven, the first fast boat across the strait in about forty-five minutes while the sea is still calm. On the island a van on rough roads to the west side, in the order that beats the crowd: Kelingking first, for the dinosaur cliff from the viewpoint, and the climb down only for the fit and properly shod. Then Broken Beach's natural arch and Angel's Billabong's tidal pool, which is safe to enter only at low tide on a calm morning and dangerous whenever swell comes over the lip. Crystal Bay for an actual swim before the afternoon boat.\n\nThe east side is a separate day; a tour that promises both sides in one is a day in a van.",
        tours: ["/indonesia/nusa-penida/fast-boat-transfer-between-sanur-and-nusa-penida", "/indonesia/nusa-penida/island-beach-highlights-swim-and-hike-tour-in-nusa-penida"],
        travel: "Uluwatu to Sanur about 45 minutes early; boat 45 minutes each way. Book the return with the outbound.",
        tip: "Do not swim at Kelingking beach. The shore break and rip have taken strong swimmers; the beach is for looking.",
      },
      {
        day: 5,
        base: "Uluwatu",
        heading: "A slow last morning: surf watching, GWK, or another cove",
        narrative: "No alarm. A morning above Suluban watching the surfers on the Uluwatu reef from the cliff bars, or the Garuda Wisnu Kencana park's 120-metre statue if the flight is late, or one more cove at the right tide. The airport is thirty to forty minutes away before midday and well over an hour after; plan the departure around that rather than the flight time alone.",
        tours: ["/indonesia/uluwatu/surfers-paradise-2-hour-surf-experience-in-uluwatu-uluwatu", "/indonesia/uluwatu/bukit-peninsula-2-hour-surf-experience-at-uluwatu-beach-uluwatu"],
        travel: "Uluwatu to airport 30 to 40 minutes in the morning, over an hour from midday.",
        tip: "If the flight is early the next morning, spend the last night in Jimbaran or Seminyak instead, closer to the airport.",
      },
    ],
    logistics: [
      { heading: "Getting around", content: "A private driver for eight to ten hours a day is the default on this route and is how every driver-based tour on this site is arranged. Scooters are cheap and legally need an international permit with a motorcycle category; police checkpoints fine foreigners without one and insurance excludes unlicensed riders. Ride-hailing apps work in the south and are restricted for pickups in central Ubud." },
      { heading: "The Nusa Penida boat", content: "Fast boats leave Sanur from around seven; the early ones are the day-trippers' boats and the afternoon returns fill up, so both legs are booked together. Boarding can mean wading from the beach; keep passports and phones in a dry bag. Dry-season mornings are calm and afternoons choppy; wet-season swells occasionally cancel crossings." },
      { heading: "Nyepi", content: "One day in March on a moving date: airport closed, everyone indoors, no boats, no lights. Check the date before booking March; the parade the evening before is worth seeing, the day itself is a hotel day." },
    ],
    faqs: [
      { question: "Is 5 days enough for Bali?", answer: "Enough for the three things most people come for: Ubud's interior with a Batur sunrise, a full day on Nusa Penida, and Uluwatu's coves and sunset temple. It does not include Canggu's surf or the east coast; those fit at seven days." },
      { question: "Where should I base myself for Nusa Penida?", answer: "The south coast. Uluwatu, Seminyak or Sanur itself are all within 45 minutes to an hour of the harbour, which makes the first boat a 6am pickup rather than a 4:30 one from Ubud." },
      { question: "Can you see both sides of Nusa Penida in one day?", answer: "It is sold, but the roads are rough and slow and it means minutes at each stop. One side per day; the west first on a first visit." },
      { question: "Is the Batur sunrise trek hard?", answer: "A steady two-hour uphill on loose ground with a steep final section. Average fitness is fine. The cold at the top and the lack of sleep are what people struggle with, not the climb. A jeep viewpoint tour exists for anyone not walking." },
    ],
  },
  "7-days": {
    days: 7,
    title: "7 Days in Bali: Interior, Islands and the Surf Coast",
    metaTitle: "7 Day Bali Itinerary | AsiaByLocals",
    metaDescription: "A 7 day Bali itinerary with three nights in Ubud including the east's temples and terraces, an overnight on Nusa Penida for Kelingking at dawn and the mantas, and Uluwatu and Canggu on the coast.",
    routeSummary: "Ubud → Ubud → Ubud → Nusa Penida → Nusa Penida → Uluwatu → Canggu",
    intro: "A week is where Bali starts to make sense as one island rather than a list of places. Three nights in Ubud allow a day for the volcano, a day for the temples and waterfalls, and a day for the east, where Sidemen's terraces and Tirta Gangga's water palace are the calm version of the postcard. A night on Nusa Penida turns the island from an exhausting day trip into two good ones, with Kelingking at dawn before the boats arrive and the manta cleaning stations by boat. The last two nights split the south coast between Uluwatu's cliffs and Canggu's surf.\n\nThe route runs inland to island to coast so that the earliest starts, Batur and the Penida crossing, come while you are still fresh, and the surf and beach clubs come at the end when you are not.",
    bestFor: "First visits with a full week, couples, and anyone who wants the islands done properly rather than in a rush.",
    quickAnswer: "A week runs inland to island to coast. Three nights in Ubud: terraces and temples, the Batur sunrise, and an early run east to the Lempuyang gate, Tirta Gangga and Sidemen. One night on Nusa Penida so Kelingking is at dawn and the mantas are by boat. Then Uluwatu for the coves and Kecak, and Canggu for a surf lesson at Batu Bolong and a beach-club sunset before flying out.",
    days_detail: [
      {
        day: 1,
        base: "Ubud",
        heading: "Arrive, settle, and the Monkey Forest before dark",
        narrative: "Most flights land in the afternoon, and the ninety-minute drive to Ubud through the traffic is the first lesson in island distances. Walk the centre, see the lotus pond at Saraswati temple, and if there is an hour of light left, the Monkey Forest with the bag zipped. Early dinner; the terraces are at dawn tomorrow.",
        tours: ["/indonesia/ubud/saraswati-temple-and-ubud-monkey-forest-with-waterfalls", "/indonesia/ubud/waterfall-rice-terraces-and-monkey-forest-private-tour-in-ubud"],
        travel: "Airport to Ubud about 1.5 hours.",
        tip: "Book the airport transfer at a fixed price; the app at the arrivals hall is where first-day overcharging happens.",
      },
      {
        day: 2,
        base: "Ubud",
        heading: "Terraces at dawn, the Pakerisan temples, waterfalls in the afternoon",
        narrative: "Tegallalang before 8:30, walking down through the paddies while they are still mirrors. Tirta Empul for the purification, done properly or watched from the side, then Gunung Kawi's cliff shrines if the steps appeal. Lunch in Ubud. The waterfalls east of town in the afternoon: Tibumana for the setting, Kanto Lampo for the photograph, Tukad Cepung skipped because its light beams are a nine-to-eleven event.",
        tours: ["/indonesia/ubud/tibumana-tukad-cepung-kanto-lampo-and-tegenungan-tour-in-ubud", "/indonesia/ubud/tirta-empul-kanto-lampo-waterfall-rice-terraces-and-swing-in-ubud"],
        travel: "All within 30 to 45 minutes of Ubud.",
        tip: "Wear shoes that grip and can get wet; every waterfall injury is a slip on rock, not the water.",
      },
      {
        day: 3,
        base: "Ubud",
        heading: "Batur sunrise, hot springs, rest",
        narrative: "Two in the morning pickup, torchlight to the rim, a cold forty minutes waiting for the sun to come up behind Agung, eggs from the steam vents, hot springs on the lake. Jeep to the flank viewpoint for anyone not walking. Back in Ubud by late morning and the rest of the day is a pool and a massage; tomorrow is another early one.",
        tours: ["/indonesia/ubud/shared-mount-batur-sunrise-jeep-tour-with-hot-springs", "/indonesia/ubud/mount-batur-jeep-sunrise-tour-and-ubud-zipline-adventure"],
        travel: "Ubud to Toya Bungkah 1.25 hours each way.",
        tip: "Bring a real jacket and a headtorch. The summit is often under 12°C and the guides' spare jackets run out.",
      },
      {
        day: 4,
        base: "Ubud",
        heading: "East Bali: Sidemen, Tirta Gangga and the Lempuyang gate",
        narrative: "An early start east, because the famous gate at Lempuyang, Mount Agung framed between two stone halves, has a queue for the photo that is commonly an hour by mid-morning. Know before you go that the reflection in the picture is a piece of glass held under the lens; there is no lake. Then Tirta Gangga's water palace with its stepping stones across the carp pools, calm and beautiful, and lunch in the Sidemen valley, whose terraces are as fine as Tegallalang's with nobody in them. Back to Ubud by evening.",
        tours: ["/indonesia/ubud/east-bali-lempuyang-temple-tirta-gangga-and-taman-ujung-ubud", "/indonesia/ubud/sidemen-bali-mount-agung-sunrise-or-daytime-trek-3-142m-peak-ubud"],
        travel: "Ubud to Lempuyang 1.5 to 2 hours each way; a ten-hour day.",
        tip: "Leave by six. The difference between six and eight at Lempuyang is the difference between a five-minute wait and an hour.",
      },
      {
        day: 5,
        base: "Nusa Penida",
        heading: "Cross to Penida and see the west in the golden hour",
        narrative: "A midday boat from Sanur, calmer than the dawn rush and emptier, and check in on the island. The west side in the late afternoon, when the day-trip vans are heading for the harbour: Broken Beach's arch and Angel's Billabong at low tide if the sea is calm, then Crystal Bay for a swim and the sunset. Kelingking is tomorrow, at dawn, on purpose.",
        tours: ["/indonesia/nusa-penida/kelingking-beach-broken-beach-and-sunset-dinner-in-nusa-penida", "/indonesia/nusa-penida/island-beach-highlights-swim-and-hike-tour-in-nusa-penida"],
        travel: "Ubud to Sanur about 1 hour; boat 45 minutes.",
        tip: "Penida's roads are rough and slow; a driver arranged through the tour or guesthouse beats a rented scooter here.",
      },
      {
        day: 6,
        base: "Uluwatu",
        heading: "Kelingking at dawn, mantas by boat, back to the mainland",
        narrative: "At the Kelingking viewpoint before eight with the cliff to yourself, which is the whole reason for the overnight; the climb down to the sand only if fit and shod for it, and no swimming at the bottom whatever the day looks like. Then a boat along the south-west coast to the manta cleaning stations at Manta Point or Manta Bay, floating still while the rays circle below, with Crystal Bay's coral on the way back. An afternoon boat to Sanur and the drive to Uluwatu for the Kecak at sunset if the timing holds; if it does not, the dance is tomorrow.",
        tours: ["/indonesia/uluwatu/uluwatu-temple-tour-with-sunset-kecak-fire-dance", "/indonesia/uluwatu/uluwatu-temple-tour-and-kecak-dance-at-karang-boma-cliff"],
        travel: "Boat to Sanur 45 minutes; Sanur to Uluwatu about 1 hour.",
        tip: "Manta Point takes open-ocean swell and operators divert or cancel on big days. Trust that call.",
      },
      {
        day: 7,
        base: "Canggu",
        heading: "Uluwatu's coves in the morning, Canggu's surf and sunset to finish",
        narrative: "A cove at the right tide first thing, Padang Padang or Balangan, before the stairs are in full sun. Then north along the coast to Canggu, an hour and a half, for a surf lesson at Batu Bolong where the wave is slow and forgiving on a longboard, and the evening at a beach club on the black sand facing west. Fly out from here the next morning; forty-five minutes to the airport at dawn, two hours by afternoon.",
        tours: ["/indonesia/canggu/surf-lesson-in-batu-bolong-canggu-with-certified-instructor-canggu", "/indonesia/canggu/ubud-highlights-tour-w-canggu-black-sand-beach-chill"],
        travel: "Uluwatu to Canggu 1 to 1.5 hours; Canggu to airport 45 minutes at dawn.",
        tip: "Reserve a beach-club day bed for three o'clock onwards if sunset is the goal; they run on minimum spends redeemed on food and drink.",
      },
    ],
    logistics: [
      { heading: "Getting around", content: "A private driver by the day on the mainland, at a flat rate with fuel, and a driver arranged on Penida for the island's roads. Scooters are for licensed, experienced riders only; the surfaces on Penida and the lanes in Canggu catch out the rest. Apps work in the south and are restricted for pickups in central Ubud." },
      { heading: "Boats", content: "Sanur to Penida is 45 minutes by fast boat. Take a midday crossing out and an afternoon crossing back to avoid the day-trip rush both ways, and book both when you book the first. Dry bag for phones and passports; boarding can mean wading." },
      { heading: "Nyepi and ceremonies", content: "Nyepi, in March on a moving date, closes the airport and the island for a day. Galungan and Kuningan, on a 210-day cycle, fill the roads with bamboo penjor and the temples with ceremonies; nothing closes but drivers run late. A driver who is local will know which temple has a ceremony that morning." },
    ],
    faqs: [
      { question: "Is one night on Nusa Penida enough?", answer: "Yes, and it transforms the island. Arriving midday and leaving the next afternoon gives the west side in the golden hour, Kelingking at dawn before the boats, and the mantas by boat, with calmer crossings than the day-trip schedule." },
      { question: "Should I do Ubud or the coast first?", answer: "Ubud first. The earliest starts, the Batur trek and the Lempuyang gate, are best done while fresh, and the surf and beach clubs at the end need no alarm." },
      { question: "Is Lempuyang worth the drive?", answer: "With a six o'clock departure, yes: the gate with Agung behind it is extraordinary in early light. By mid-morning the queue for the photo is an hour and the reflection everyone posts is glass held under a phone. Tirta Gangga and Sidemen on the same day are the calm half of the trip." },
      { question: "Can beginners surf in Canggu?", answer: "Yes, at Batu Bolong, where the wave breaks slowly over sand a long way out and every school on the beach teaches. Two-hour lessons with an instructor in the water are the standard." },
    ],
  },
  "10-days": {
    days: 10,
    title: "10 Days in Bali: The Full Island Without the Rush",
    metaTitle: "10 Day Bali Itinerary | AsiaByLocals",
    metaDescription: "A 10 day Bali itinerary that gives Ubud four nights, Nusa Penida two, and the south coast four between Uluwatu and Canggu, with the north's lakes and Jatiluwih on the way.",
    routeSummary: "Ubud → Ubud → Ubud → Ubud → Nusa Penida → Nusa Penida → Uluwatu → Uluwatu → Canggu → Canggu",
    intro: "Ten days lets Bali breathe. Four nights in Ubud make room for the volcano, the river temples, the eastern gates and water palaces, and a day north into the highlands for Jatiluwih's vast terraces and the lake temple at Ulun Danu Beratan, which the shorter routes cannot fit. Two nights on Nusa Penida cover both sides of the island and the mantas without a single dawn boat. Four nights on the south coast split between Uluwatu's cliffs and Canggu's surf, with an afternoon at Tanah Lot timed to the tide.\n\nThis is the version where nothing is done in the wrong hour. The terraces are seen at dawn, Lempuyang before the queue, Tukad Cepung when the light beams are on, Kelingking with the cliff empty, and the Kecak from the seats that face the sun.",
    bestFor: "Honeymoons, first long visits, and anyone who found a shorter Bali trip felt like a checklist.",
    quickAnswer: "Ten days does the whole island at the right hours. Four nights in Ubud add a north day for Jatiluwih's terraces and the lake temple to the volcano, the river temples and the east. Two nights on Nusa Penida cover both sides and the mantas without a dawn boat. Four nights on the south coast split Uluwatu's cliffs and Canggu's surf, with Tanah Lot timed to the tide on the last afternoon.",
    days_detail: [
      {
        day: 1,
        base: "Ubud",
        heading: "Arrive and walk the centre",
        narrative: "The drive in from the airport, a walk through Ubud's centre to the lotus pond at Saraswati temple, and the Monkey Forest in the last light with everything zipped away. Early dinner; the terraces are at dawn.",
        tours: ["/indonesia/ubud/saraswati-temple-and-ubud-monkey-forest-with-waterfalls", "/indonesia/ubud/waterfall-rice-terraces-and-monkey-forest-private-tour-in-ubud"],
        travel: "Airport to Ubud about 1.5 hours.",
        tip: "Fix the transfer price before you get in the car.",
      },
      {
        day: 2,
        base: "Ubud",
        heading: "Tegallalang at dawn, Tukad Cepung in its window, the river temples",
        narrative: "The terraces before 8:30, walked rather than photographed from the road. Then straight to Tukad Cepung for the nine-to-eleven window when sunlight comes down through the canyon roof in beams, the only hour it works and the reason it is today and early. Tirta Empul after, quieter by then in the afternoon lull than at noon, and Gunung Kawi's rock shrines up the same river if the legs are willing.",
        tours: ["/indonesia/ubud/bali-hidden-hidden-canyon-tirta-empul-and-gunung-kawi-ubud", "/indonesia/ubud/half-day-tirta-empul-purification-and-gunung-kawi-temple-in-ubud"],
        travel: "All within 45 minutes of Ubud.",
        tip: "Tukad Cepung closes after heavy rain for flash-flood risk; a local driver knows that morning.",
      },
      {
        day: 3,
        base: "Ubud",
        heading: "Batur sunrise and a day of nothing",
        narrative: "Two in the morning, the climb, the cold rim, Agung behind the sunrise, eggs in the steam, hot springs on the lake, back by late morning. The rest of the day is deliberately empty: a pool, a massage, an early night. The jeep to the flank viewpoint is the alternative for anyone not walking.",
        tours: ["/indonesia/ubud/shared-mount-batur-sunrise-jeep-tour-with-hot-springs", "/indonesia/ubud/mount-batur-shared-sunrise-jeep-and-natural-hot-springs"],
        travel: "Ubud to Toya Bungkah 1.25 hours each way.",
        tip: "A proper jacket and a headtorch. Nearly everyone who is miserable on the summit dressed for the lowlands.",
      },
      {
        day: 4,
        base: "Ubud",
        heading: "The east: Lempuyang early, Tirta Gangga, lunch in Sidemen",
        narrative: "Out by six for Lempuyang's split gate with Agung framed in it, before the photo queue reaches an hour, and knowing the mirror in every picture is a piece of glass held under the lens. Tirta Gangga's water palace and its stepping stones across the carp pools. Lunch in the Sidemen valley among terraces with nobody in them. Back to Ubud for the evening.",
        tours: ["/indonesia/ubud/east-bali-lempuyang-temple-tirta-gangga-and-taman-ujung-ubud", "/indonesia/ubud/bali-private-tour-gate-of-heaven-tirta-gangga-and-besakih-ubud"],
        travel: "Ubud to Lempuyang 1.5 to 2 hours each way.",
        tip: "This is the ten-hour day; the reward for the early start is the gate without a crowd.",
      },
      {
        day: 5,
        base: "Ubud",
        heading: "North: Jatiluwih, the lake temple, and the highland road",
        narrative: "West and up to Jatiluwih, the UNESCO-listed terraces that Tegallalang is a postcard of, walked for an hour or two on paths with almost no one on them. Then Ulun Danu Beratan, the temple whose pagodas stand in the lake, cool and often misty by afternoon. Back down through the highland road to Ubud, or, if the plan is Canggu-first rather than Ubud-last, drop to the coast for Tanah Lot at sunset.",
        tours: ["/indonesia/ubud/north-bali-banyumala-waterfall-and-ulun-danu-beratan-temple-ubud", "/indonesia/ubud/full-day-ulun-danu-beratan-temple-and-gitgit-waterfall-in-ubud"],
        travel: "Ubud to Jatiluwih about 1.5 hours; Jatiluwih to Ulun Danu 40 minutes.",
        tip: "The highlands are cloudy by afternoon most days; Jatiluwih is the morning stop.",
      },
      {
        day: 6,
        base: "Nusa Penida",
        heading: "Midday boat to Penida, the west side in the golden hour",
        narrative: "Sanur at midday for a calm, uncrowded crossing, and the west of the island in the late afternoon as the day-trip vans leave: Broken Beach's arch, Angel's Billabong if the tide is low and the sea calm, Crystal Bay for the swim and the sunset.",
        tours: ["/indonesia/nusa-penida/island-beach-highlights-swim-and-hike-tour-in-nusa-penida", "/indonesia/nusa-penida/kelingking-beach-broken-beach-and-sunset-dinner-in-nusa-penida"],
        travel: "Ubud to Sanur 1 hour; boat 45 minutes.",
        tip: "Book the return boat now, for the afternoon of day eight.",
      },
      {
        day: 7,
        base: "Nusa Penida",
        heading: "Kelingking at dawn, then the east: Diamond Beach and the Thousand Islands",
        narrative: "The Kelingking viewpoint before eight with the cliff empty, the climb down for those who want it and are shod for it, no swimming at the bottom. Then across the island's slow roads to the east: Diamond Beach beneath its limestone spires by the cliff staircase, Atuh's cove next door, the Thousand Islands viewpoint along the cliff path, and the tree house that has become a photo stop. A quiet evening; the day-trippers never reach this side.",
        tours: ["/indonesia/nusa-penida/nusa-penida-journey-to-atuh-diamond-beach-and-tree-house-tour-nusa-penida", "/indonesia/nusa-penida/tembeling-beach-and-forest-kelingking-beach-broken-in-nusa-penida"],
        travel: "Penida west to east about 1.5 hours on rough roads.",
        tip: "Diamond Beach's sea carries the same warning as Kelingking's. Swim at Crystal Bay, not here.",
      },
      {
        day: 8,
        base: "Uluwatu",
        heading: "Mantas by boat, then the boat home and the Kecak",
        narrative: "A morning boat to the manta cleaning stations on the south-west coast, floating still above the rays with Crystal Bay's coral on the way back, and the mola mola possible from July to October. An early-afternoon crossing to Sanur, the drive to the Bukit, and the temple gate by half past four for the Kecak at sunset from the left-hand seats.",
        tours: ["/indonesia/uluwatu/uluwatu-temple-tour-with-sunset-kecak-fire-dance", "/indonesia/uluwatu/uluwatu-temple-sunset-tour-with-kecak-fire-dance"],
        travel: "Boat to Sanur 45 minutes; Sanur to Uluwatu about 1 hour.",
        tip: "Manta trips divert or cancel on big-swell days; the cliffs that make the coast are the same swell.",
      },
      {
        day: 9,
        base: "Uluwatu",
        heading: "Coves by the tide and surf from the cliff",
        narrative: "Padang Padang or Balangan at mid to high tide for swimming, Melasti at low for the shallows, all but Melasti reached by cliff stairs with no shade. The afternoon above Suluban watching the Uluwatu reef break from the bars on the cliff, and dinner at Jimbaran's grills on the sand.",
        tours: ["/indonesia/uluwatu/uluwatu-sunset-magic-kecak-padang-padang-cliff-and-dinner-uluwatu", "/indonesia/uluwatu/beginner-and-intermediate-surf-lesson-with-equipment-in-uluwatu"],
        travel: "All within 20 minutes on the peninsula.",
        tip: "Reef shoes for any low-tide walk; every break on the Bukit is over sharp limestone.",
      },
      {
        day: 10,
        base: "Canggu",
        heading: "Canggu: a surf lesson, and Tanah Lot at the right tide to finish",
        narrative: "North to Canggu and a lesson at Batu Bolong, slow waves over sand and an instructor pushing you in. Then Tanah Lot, thirty to forty-five minutes up the coast, timed to the tide: at low tide walk across to the rock and be blessed at the spring; at high tide the temple is the island in the photographs. Ninety minutes before sunset for a spot on the cliff, then back to Canggu for the last evening on the black sand. Fly out the next morning, forty-five minutes to the airport at dawn.",
        tours: ["/indonesia/canggu/surf-lesson-in-batu-bolong-canggu-with-certified-instructor-canggu", "/indonesia/canggu/north-bali-ulundanu-waterfall-and-sunset-tanah-lot-temple-canggu"],
        travel: "Uluwatu to Canggu 1 to 1.5 hours; Canggu to Tanah Lot 30 to 45 minutes; Canggu to airport 45 minutes at dawn.",
        tip: "Check the tide table for Tanah Lot before choosing the hour; the two versions of the visit are both good and completely different.",
      },
    ],
    logistics: [
      { heading: "Getting around", content: "Private drivers by the day everywhere on the mainland, a driver arranged on Penida, and ride-hailing apps for short hops in the south. Scooter rental is cheap and, without an international permit with a motorcycle category, both illegal at the checkpoints and uninsured in an accident. Canggu's lanes and Penida's roads are where visitors get hurt." },
      { heading: "Boats and tides", content: "Sanur to Penida is 45 minutes; midday out and mid-afternoon back avoid the day-trip rush, and both legs are booked together. Tide tables decide Tanah Lot, the Uluwatu coves and Angel's Billabong; a local driver checks them, or ask at the harbour." },
      { heading: "Nyepi and the calendar", content: "Nyepi, in March on a moving date, closes the airport and confines everyone indoors for a day. Galungan and Kuningan, on a 210-day cycle, decorate the villages and slow the roads. Check the March date before booking; the rest is atmosphere." },
    ],
    faqs: [
      { question: "Is 10 days too long for Bali?", answer: "Not on this route. Four nights in Ubud, two on Penida and four on the coast fill every day with something done at the right hour. It is the shorter trips that feel like a checklist." },
      { question: "Should I add Lombok or the Gilis to 10 days in Bali?", answer: "Only by taking days from this route. Ten days does Bali properly; Lombok and the Gilis are a separate trip or a two-week version." },
      { question: "Is Nusa Penida worth two nights?", answer: "Yes. Two nights cover the west in the golden hour, Kelingking at dawn, the entire east side and a manta boat, with calm crossings both ways. One night does most of it; a day trip does the west in a crowd." },
      { question: "When should I go for this itinerary?", answer: "May, June or September: dry-season mornings for Batur, the beams at Tukad Cepung and calm Penida crossings, without the July and August peak. November to March works too, with cloud a risk for the sunrises and swell a risk for the boats." },
    ],
  },
};
