// Pattaya authority pages (2026-08). Same CityInfoData shape as cityInfoContent.ts.
// Reached via getThailandInfoContent() -> getCityInfoContent().
import type { CityInfoData } from './cityInfoContent';

const IMG = {
    sanctuary: "https://res.cloudinary.com/dx2fxyaft/image/upload/v1786098704/asiabylocals/tours/pattaya-the-sanctuary-of-truth-admission-ticket/hq_tour_img_1.png",
    kohLarn: "https://res.cloudinary.com/dx2fxyaft/image/upload/v1786098597/asiabylocals/tours/pattaya-coral-island-speedboat-tour-with-lunch-and-transfer/hq_tour_img_1.png",
    nongNooch: "https://res.cloudinary.com/dx2fxyaft/image/upload/v1786098681/asiabylocals/tours/pattaya-nong-nooch-tropical-garden-ticket-for-foreigners/hq_tour_img_1.jpg",
    bigBuddha: "https://res.cloudinary.com/dx2fxyaft/image/upload/v1786098868/asiabylocals/tours/pattaya-big-buddha-temple-and-night-market-tour/hq_tour_img_1.jpg",
    catamaran: "https://res.cloudinary.com/dx2fxyaft/image/upload/v1786098547/asiabylocals/tours/pattaya-exclusive-3-island-catamaran-tour-with-buffet-lunch/hq_tour_img_1.jpg",
    tiffany: "https://res.cloudinary.com/dx2fxyaft/image/upload/v1786098839/asiabylocals/tours/pattaya-tiffany-cabaret-show-with-dinner-vip-seating-more/hq_tour_img_1.jpg",
    elephants: "https://res.cloudinary.com/dx2fxyaft/image/upload/v1786098559/asiabylocals/tours/from-pattaya-living-green-elephant-sanctuary-day-trip/hq_tour_img_1.jpg",
};

const CARD = {
    sanctuary: { slug: "sanctuary-of-truth-naklua-pattaya-spiritual-tour", title: "Sanctuary of Truth Wooden Temple Entrance Ticket", description: "Thailand's 105-metre all-teak cathedral, built without a single nail and deliberately never finished.", price: "From $17", duration: "1.5-2 hours", rating: "4.8", reviews: "8", image: IMG.sanctuary },
    kohLarn: { slug: "koh-larn-coral-island-full-day-tour", title: "Coral Island Day Trip by Speedboat with Lunch", description: "Koh Larn's turquoise water 7 km offshore — speedboat transfer, beach time and lunch, with hotel pickup.", price: "From $11", duration: "6 hours", rating: "4.7", reviews: "8", image: IMG.kohLarn },
    nongNooch: { slug: "nong-nooch-tropical-garden-pattaya-cultural-tour", title: "Nong Nooch Garden Entry Pass with Cultural Shows", description: "600 acres of world-class botanical gardens, a cycad collection of global importance, and a Thai cultural show.", price: "From $14", duration: "3-4 hours", rating: "4.7", reviews: "8", image: IMG.nongNooch },
    catamaran: { slug: "monkey-island-chonburi-boat-tour", title: "Pattaya 3-Island Catamaran Cruise with Thai Buffet", description: "The quieter outer islands — Koh Sak, Koh Phai — by catamaran, away from Koh Larn's crowds.", price: "From $87", duration: "7 hours", rating: "4.8", reviews: "8", image: IMG.catamaran },
    bigBuddha: { slug: "pattaya-marina-night-market-sunset-tour", title: "Pattaya Sunset Trio: Big Buddha Hill, Viewpoint & Night Market", description: "Wat Phra Yai, the Pattaya bay viewpoint and the marina night market — the city's best three hours at dusk.", price: "From $84", duration: "3 hours", rating: "4.8", reviews: "7", image: IMG.bigBuddha },
    tiffany: { slug: "tiffanys-show-theatre-north-pattaya-entry-ticket", title: "Tiffany's Show Pattaya: Cabaret with Dinner & VIP Seat", description: "The cabaret that has run since 1974 — sequins, big production numbers and a genuine Pattaya institution.", price: "From $60", duration: "2.5 hours", rating: "4.8", reviews: "8", image: IMG.tiffany },
    elephants: { slug: "living-green-elephant-sanctuary-chonburi-full-day-tour", title: "Ethical Elephant Sanctuary Day Trip from Pattaya", description: "A no-riding sanctuary in the Chonburi countryside — feed, walk with and observe a rescued herd.", price: "From $65", duration: "6 hours", rating: "4.9", reviews: "8", image: IMG.elephants },
};

export function getPattayaInfoContent(slug: string): CityInfoData | null {
    switch (slug) {

        case "is-pattaya-worth-visiting":
            return {
                title: "Is Pattaya Worth Visiting? An Honest 2026 Answer",
                description: "Pattaya has a reputation, and it's partly earned. Who should go, who genuinely shouldn't, what the city does better than anywhere in Thailand, and how to avoid the parts you came to avoid.",
                heroImage: IMG.nongNooch,
                sections: [
                    {
                        title: "Let's Deal With the Reputation First",
                        icon: "Info",
                        content: "No Thai city carries as much baggage as Pattaya. Ask around and you'll be told it's a sex-tourism town, that it's tacky, that it's where package tourism goes to die. Search it and you'll find a hundred articles either scolding it or coyly refusing to explain what they mean.\n\nSo, plainly: **Pattaya does have a large and highly visible adult nightlife industry**, concentrated in a few well-defined areas — principally **Walking Street** in South Pattaya, plus Soi 6 and a handful of surrounding blocks. It grew out of the city's role as an R&R destination for American servicemen during the Vietnam War, when a quiet fishing village on the Gulf of Thailand was transformed in the space of a decade. That history is real and its consequences are still the most notorious thing about the city.\n\nHere's what the reputation misses: **that district is a small fraction of a city of roughly 120,000 people that sprawls for 15 kilometres along the coast.** Walking Street is about 500 metres long. You can spend a week in Pattaya and never set foot on it, which is exactly what a very large number of visitors — Thai families, Russian and Scandinavian long-stayers, Chinese and Indian tour groups, retirees, weekending Bangkokians — actually do.\n\nThe useful question isn't \"is Pattaya good or bad.\" It's **\"which Pattaya are you booking?\"** — because the answer is almost entirely determined by which neighbourhood you sleep in. Get that right and it's a genuinely enjoyable, absurdly good-value beach city two hours from Bangkok. Get it wrong and you'll spend three days wondering why you came.",
                    },
                    {
                        title: "Who Pattaya Is Genuinely Good For",
                        icon: "CheckCircle2",
                        content: "**People with limited time in Bangkok.** Pattaya is the closest real beach destination to the capital — roughly **two hours** by road, no domestic flight required. If you have three spare days at the end of a Bangkok trip and don't want to burn two of them flying to Phuket and back, this is the answer. Nothing else on the Gulf is as accessible.\n\n**Families.** This surprises people, but Pattaya is arguably the most child-friendly city in Thailand in sheer density of things to do: waterparks, Nong Nooch's gardens and elephant shows, the Sanctuary of Truth, Underwater World, go-karting, Ramayana Water Park, Koh Larn's beaches. Base yourself in **Jomtien** or **Naklua** and the adult-nightlife city may as well not exist.\n\n**Budget travellers.** Pattaya is significantly cheaper than Phuket or Samui for equivalent quality. Beachfront four-star hotels run at prices that get you a guesthouse on Phuket's west coast in January. Food is cheap and excellent, especially seafood.\n\n**Long-stay visitors and remote workers.** There's a substantial long-term foreign community, good hospitals, cheap monthly condo rentals with sea views, fast internet, and every conceivable cuisine. It's not Chiang Mai for atmosphere, but it's practical.\n\n**Watersports people.** The islands off the coast offer some of the most accessible diving in Thailand, including wreck dives, and the jet-ski, parasail and kitesurf infrastructure at Jomtien is extensive.\n\n**Thai domestic tourists.** Worth noting because it's a useful signal: Pattaya is enormously popular with Bangkok Thais on weekends. They are not coming for Walking Street. They come for the seafood, the islands and the resorts.",
                        tourCard: CARD.nongNooch,
                    },
                    {
                        title: "Who Should Probably Go Elsewhere",
                        icon: "AlertTriangle",
                        content: "Honesty cuts both ways. Pattaya is the wrong choice if:\n\n**You want a beautiful beach.** This is the biggest single caveat. **Pattaya Beach itself is mediocre** — narrow, busy, with water that isn't what you're picturing when you imagine Thailand. Jomtien is considerably better, and Koh Larn's beaches are genuinely lovely, but if postcard sand is the primary goal, **Krabi, Koh Lanta, Koh Samui or the Andaman coast will serve you far better**. People who arrive expecting Phuket-quality beach and get Pattaya Beach are the single largest group of disappointed visitors.\n\n**You want unspoiled or \"authentic\" Thailand.** Pattaya is developed, commercial and unapologetic about it. High-rise condos line the bay. If you're looking for a fishing village atmosphere, this isn't it — though Bang Saray, 20 minutes south, still partly is.\n\n**You're bothered by the nightlife industry's existence.** Even if you avoid the districts entirely, Pattaya's economy is visibly shaped by it, and there's a persistent open presence of it in parts of the city. Some visitors find that uncomfortable regardless of where they stay, and that's a legitimate reason to choose elsewhere.\n\n**You're travelling solo as a young woman and want a relaxed beach town.** You'll be fine and it's safe, but the atmosphere in central and south Pattaya can be wearing. Jomtien or Naklua fix most of it; Krabi or Koh Lanta fix all of it.\n\n**You have limited time in Thailand overall.** If you have ten days total and haven't seen Chiang Mai or the Andaman islands, Pattaya shouldn't be on the list. It earns its place on a second trip, or as a short add-on to Bangkok — not as a headline destination.",
                    },
                    {
                        title: "What Pattaya Does Better Than Anywhere Else",
                        icon: "Star",
                        content: "Set the reputation aside and there are things here you genuinely can't get elsewhere in Thailand.\n\n**The [Sanctuary of Truth](/thailand/pattaya/sanctuary-of-truth-pattaya)** is, without much competition, one of the most extraordinary buildings in Southeast Asia: a 105-metre hand-carved teak temple on the sea, built entirely without nails, under continuous construction since 1981 — and deliberately designed **never to be finished**. It alone justifies a trip.\n\n**Nong Nooch Tropical Garden** is not the tourist trap the name suggests. It's a 600-acre botanical garden of international scientific standing, holding one of the world's most important **cycad collections**, alongside sculpted French and Italian gardens, an orchid nursery and a large cultural show. Botanists travel here specifically.\n\n**[Koh Larn](/thailand/pattaya/koh-larn-island-guide)** — the island 7 km offshore with water that looks nothing like the mainland's. A 45-minute public ferry costing ฿40 gets you to genuinely turquoise water and white sand. It's the single best-value day out in the region.\n\n**The cabaret shows.** Tiffany's has run since 1974 and is one of the oldest and most professionally staged cabaret productions in Asia, with Alcazar its long-standing rival. These are big-budget, family-attended variety shows, and they're a legitimate Pattaya institution rather than a seedy footnote.\n\n**Wat Phra Yai (Big Buddha Hill)** and the Pratumnak viewpoint at sunset, over the whole sweep of the bay.\n\n**The seafood.** Naklua's fish market and the restaurants along the northern and southern coasts serve outstanding seafood at prices the islands can't match.\n\n**Accessibility.** Two hours from Bangkok, cheap, with more to do per square kilometre than anywhere else on the Gulf.",
                        tourCard: CARD.sanctuary,
                    },
                    {
                        title: "The Verdict — and How to Do It Right",
                        icon: "Map",
                        content: "**Our honest verdict**: Pattaya is worth visiting **as a 2–4 day add-on to Bangkok**, particularly if you have children, a limited budget, or limited time. It is **not** worth structuring a Thailand trip around, and it is not the place to go if you want a beautiful beach.\n\nIf you go, four decisions determine your experience:\n\n**1. Stay in the right neighbourhood.** This matters more than anything else. **Naklua** (north, quiet, Thai, good seafood) or **Jomtien** (long beach, families and long-stayers) for a relaxed trip; **Pratumnak** — the green hill between the two — is the best compromise for most people. **Avoid South Pattaya / Walking Street** unless that's specifically why you came. Our [where to stay in Pattaya guide](/thailand/pattaya/where-to-stay-in-pattaya) breaks each area down.\n\n**2. Get off the mainland.** Spend a day on [Koh Larn](/thailand/pattaya/koh-larn-island-guide) or take a [catamaran to the quieter outer islands](/thailand/pattaya/monkey-island-chonburi-boat-tour). The water improves dramatically the moment you leave the bay.\n\n**3. Do the two genuinely world-class things.** The Sanctuary of Truth and Nong Nooch. Both are inexpensive and both are better than their marketing.\n\n**4. Eat where the Thais eat.** Naklua's seafood restaurants and the local markets, not the beach-road tourist strips.\n\n**Getting there**: buses from Bangkok's Ekkamai terminal run every 30 minutes (about ฿130, 2 hours); minivans from Victory Monument are faster and cheaper; a private car is about ฿1,500–2,000. From Suvarnabhumi Airport it's around 90 minutes, which makes Pattaya a genuinely practical first or last stop on a Thailand trip.\n\n**Best time to go**: **November to February**, when the Gulf is calm and humidity drops. March–May is very hot; the monsoon runs roughly June–October, though Gulf-coast rain is less disruptive than the Andaman's.",
                        tourCard: CARD.kohLarn,
                    }
                ],
                faqs: [
                    { q: "Is Pattaya worth visiting?", a: "**As a 2–4 day add-on to Bangkok, yes** — especially for families, budget travellers or anyone short on time, since it's the closest real beach destination to the capital (about 2 hours). It's **not** worth structuring a Thailand trip around, and it's the wrong choice if a beautiful beach is your main goal." },
                    { q: "Is Pattaya just a sex tourism destination?", a: "No, though it does have a large and visible adult nightlife industry concentrated in **Walking Street and a few surrounding blocks in South Pattaya** — a small fraction of a city sprawling 15 km along the coast. Most visitors, including many Thai families and long-stay residents, never go near it. Where you stay determines your experience almost entirely." },
                    { q: "Is Pattaya suitable for families with children?", a: "Yes, surprisingly so — it has arguably the highest density of family attractions in Thailand: waterparks, Nong Nooch gardens, the Sanctuary of Truth, Underwater World, go-karting and Koh Larn's beaches. Base yourself in **Jomtien** or **Naklua** and the nightlife districts are irrelevant to your trip." },
                    { q: "Are Pattaya's beaches any good?", a: "**Pattaya Beach itself is mediocre** — narrow, busy, and the water isn't what you're imagining. **Jomtien is considerably better**, and **Koh Larn**, 7 km offshore, has genuinely lovely turquoise water and white sand. If beaches are your priority, the Andaman coast or Koh Samui will serve you far better." },
                    { q: "How do you get from Bangkok to Pattaya?", a: "Buses leave Ekkamai terminal roughly every 30 minutes (about **฿130, 2 hours**); minivans from Victory Monument are faster and cheaper; a private car runs ฿1,500–2,000. From Suvarnabhumi Airport it's about 90 minutes, which makes Pattaya practical as a first or last stop." },
                    { q: "What is actually worth doing in Pattaya?", a: "The **Sanctuary of Truth** (a 105-metre all-teak temple built without nails, under construction since 1981), **Nong Nooch Tropical Garden** (600 acres, a globally important cycad collection), a day on **Koh Larn**, the **Tiffany's or Alcazar cabaret**, and sunset at **Big Buddha Hill**. The seafood in Naklua is excellent." }
                ],
                jsonLd: {
                    "@context": "https://schema.org",
                    "@graph": [
                        {
                            "@type": "FAQPage",
                            "mainEntity": [
                                { "@type": "Question", "name": "Is Pattaya worth visiting?", "acceptedAnswer": { "@type": "Answer", "text": "As a 2–4 day add-on to Bangkok, yes — especially for families, budget travellers or anyone short on time, since it's the closest real beach destination to the capital. It's not worth structuring a Thailand trip around, and it's the wrong choice if a beautiful beach is your main goal." } },
                                { "@type": "Question", "name": "Is Pattaya just a sex tourism destination?", "acceptedAnswer": { "@type": "Answer", "text": "No, though it has a large visible adult nightlife industry concentrated in Walking Street and a few surrounding blocks in South Pattaya — a small fraction of a city sprawling 15 km along the coast. Where you stay determines your experience almost entirely." } },
                                { "@type": "Question", "name": "Is Pattaya suitable for families with children?", "acceptedAnswer": { "@type": "Answer", "text": "Yes — it has arguably the highest density of family attractions in Thailand. Base yourself in Jomtien or Naklua and the nightlife districts are irrelevant to your trip." } },
                                { "@type": "Question", "name": "Are Pattaya's beaches any good?", "acceptedAnswer": { "@type": "Answer", "text": "Pattaya Beach itself is mediocre. Jomtien is considerably better, and Koh Larn, 7 km offshore, has genuinely lovely turquoise water and white sand. For beaches, the Andaman coast serves you better." } }
                            ]
                        }
                    ]
                },
                fastFacts: [
                    { icon: 'Clock', label: 'From Bangkok', value: '2 hours (฿130 bus)' },
                    { icon: 'Star', label: 'Best For', value: 'Families, budget, short trips' },
                    { icon: 'AlertTriangle', label: 'Not For', value: 'Postcard beaches' }
                ]
            };

        case "sanctuary-of-truth-pattaya":
            return {
                title: "Sanctuary of Truth Pattaya: The Temple Designed Never to Be Finished (2026 Guide)",
                description: "A 105-metre all-teak temple built without a single nail, under continuous construction since 1981 — and deliberately never to be completed. Tickets ฿500, hard hats required, and why it's Pattaya's best thing.",
                heroImage: IMG.sanctuary,
                sections: [
                    {
                        title: "A Building That Is Not Meant to Be Finished",
                        icon: "History",
                        content: "Most extraordinary buildings are extraordinary because someone completed them. The **Sanctuary of Truth** is extraordinary because someone decided not to.\n\nConstruction began in **1981**, on a headland at Naklua in north Pattaya where the land meets the Gulf of Thailand. Forty-five years later, it is still going. Carvers still work on site every day. You will visit an active building site — which is why **hard hats are issued at the entrance and are not optional**.\n\nThis is not a delay, a funding problem, or Thai bureaucracy. **It is the design.** The man behind it, the Thai-Chinese businessman **Lek Viriyaphan**, did not want a finished monument. He wanted a structure in permanent creation, with new carvings added by each generation of craftsmen for as long as the wood lasts — an estimated **600 years** for the takien hardwood structural posts. A completed building is a museum piece. An unfinished one is a living craft tradition with a reason to keep existing, and a workshop that keeps teaching woodcarving to people who would otherwise have no reason to learn it.\n\nIf the name Lek Viriyaphan is familiar, it's because he also built the **Ancient City (Muang Boran)** outside Bangkok — the 200-acre open-air museum shaped like Thailand containing 116 replica monuments, which we cover in our [things to do in Bangkok guide](/thailand/bangkok/things-to-do-in-bangkok). He spent his fortune on two enormous acts of cultural preservation, and this is the stranger and more beautiful of them.",
                        tourCard: CARD.sanctuary,
                    },
                    {
                        title: "How It Was Built — No Nails, No Concrete, No Steel",
                        icon: "Info",
                        content: "The technical facts are the part people struggle to believe standing in front of it.\n\n**It is 105 metres tall** at its highest spire and covers over 2,100 square metres — the **largest all-wooden building in Thailand**, and among the largest anywhere in the world.\n\n**There are no nails.** Not \"very few\" — none. The entire structure is held together by **traditional Thai wooden joinery and dowel pegs**, the same techniques used to build temples and palaces centuries before modern fixings existed. Every joint is cut to interlock. In a building this size, the engineering discipline that requires is remarkable.\n\n**There is no concrete or structural steel.** The building sits on takien and mai daeng hardwood posts driven into the ground.\n\n**Every visible surface is hand-carved.** Not moulded, not cast, not machine-routed — carved, by hand, by craftsmen working from scaffolding. The carvings are the entire point of the building.\n\n**The maintenance problem is permanent.** Sea air, humidity, sun and termites attack wood relentlessly, and the sanctuary sits directly on the coast. Carvings weather and must be replaced. This is the practical reason the workshop can never stop — even if the design were declared complete, the building would need continuous re-carving simply to survive. Lek turned that necessity into the concept.\n\nThe result is a structure that looks, from a distance, like a Khmer temple crossed with a gothic cathedral, and up close like an enormous piece of furniture that someone spent four decades carving.",
                    },
                    {
                        title: "What the Carvings Actually Mean",
                        icon: "Star",
                        content: "It would be easy to read the sanctuary as decorative excess. It isn't — the whole building is an argument, and the carvings are its sentences.\n\nLek's stated purpose was to express **the idea that human civilisation is sustained by philosophy, religion and art**, and that a life without these is like a body without a soul. The building is organised as a physical map of that idea, drawing on **Buddhist, Hindu, Thai, Khmer, Chinese and Indian** cosmology simultaneously — which is unusual, and is what gives the interior its overwhelming density.\n\n**The four wings** each face a cardinal direction and take a theme:\n- **East** — the relationship between parents and children, and the moral obligations between generations.\n- **West** — Buddhist ideas of transcending suffering and the cycle of rebirth.\n- **South** — Hindu deities, and the ordering of the cosmos.\n- **North** — Chinese and Confucian influence, and the celestial hierarchy.\n\n**Inside**, look for the depictions of the elements, the zodiac, the *Ramakien* (the Thai Ramayana), and the great multi-armed figures rising through the central hall. The ceiling work is the part most visitors photograph and the hardest to take in properly — give it time.\n\n**The best advice for a visit**: don't try to decode everything. Pick one wing, read its themes, and look at it properly for fifteen minutes. The building rewards depth over breadth. If you can, **take a guide** — the free guided walks included with entry are genuinely worthwhile, because almost none of this is self-evident.",
                    },
                    {
                        title: "Tickets, Hours and Practical Details",
                        icon: "Ticket",
                        content: "**Entry (2026)**:\n- **Adults: ฿500** for the standard day ticket\n- **Sunset tour: ฿700** for adults\n- **Children under 110 cm: ฿250** (day) / **฿350** (sunset)\n- Entry generally includes a guided walk, and a Thai cultural performance and elephant-viewing area on the grounds\n\n**Opening hours**: roughly **8:00 AM to 6:00 PM**, with the sunset session later. Cultural shows run at set times through the day — check the board on arrival so you don't miss one.\n\n**Hard hats are mandatory** and issued at the entrance. This is an active construction site and material does occasionally fall. Wear the hat properly.\n\n**Dress code**: this is a religious-themed site and modest dress is required — **shoulders and knees covered**. Sarongs are available to borrow at the entrance if needed.\n\n**How long to allow**: **1.5–2 hours** is right for the building, the grounds and a show. Photographers will want longer.\n\n**Getting there**: the sanctuary is on the headland at **Naklua, north Pattaya**, about 10–15 minutes from central Pattaya. A songthaew (the blue shared trucks) along Beach Road toward Naklua costs ฿10–20 plus a short walk; a Grab or taxi is ฿100–200 from central Pattaya. Parking is available if you drive.\n\n**Best time of day**: **late afternoon**. The teak takes on a deep warm colour in low sun, the heat drops, and the sea behind the building turns gold. The sunset ticket exists for good reason. Mid-morning is the second-best option; midday is hot and the light is flat and unflattering on the carvings.\n\n**Extras on site**: horse and carriage rides, speedboat trips, elephant viewing and Thai cultural shows are offered at additional cost. The building is the reason to come; treat the rest as optional.",
                        tourCard: CARD.bigBuddha,
                    },
                    {
                        title: "Is It Worth It? And What to Pair It With",
                        icon: "CheckCircle2",
                        content: "**Yes — unreservedly.** If you visit one thing in Pattaya, visit this. It is the single most impressive structure on Thailand's eastern seaboard and one of the more remarkable buildings anywhere in Southeast Asia, and at ฿500 it is inexpensive for what it is.\n\n**The honest caveats:**\n\n- **It is not an ancient temple**, and some visitors arrive expecting one. It is a contemporary work begun in 1981. That does not make it less impressive — it arguably makes it more so, since you can watch it being made — but adjust your expectations.\n- **The commercial add-ons** (carriage rides, photo packages, souvenir stalls) are more present than you'd like at a site of this quality. Ignore them.\n- **It's an active site**, so parts may be scaffolded or closed on any given day.\n- **The heat**. Much of the visit is outdoors or in unconditioned wooden halls. Go late afternoon.\n\n**What to pair it with.** The sanctuary sits in north Pattaya, which makes it easy to combine into a strong half-day:\n\n- **Naklua fish market and seafood lunch**, ten minutes away — the best eating in Pattaya.\n- **Wat Phra Yai (Big Buddha Hill)** and the **Pratumnak viewpoint** for sunset over the bay, then the **marina night market** — a [three-hour sunset circuit](/thailand/pattaya/pattaya-marina-night-market-sunset-tour) covers all three.\n- **[Nong Nooch Tropical Garden](/thailand/pattaya/nong-nooch-tropical-garden-pattaya-cultural-tour)** for a full culture-and-gardens day, though it's 20 km south so allow travel time.\n\nAnd if you're still deciding whether Pattaya deserves a slot in your itinerary at all, our [honest assessment of the city](/thailand/pattaya/is-pattaya-worth-visiting) lays out who it suits and who it doesn't — the Sanctuary of Truth is exhibit A for the defence.",
                    }
                ],
                faqs: [
                    { q: "How much does the Sanctuary of Truth cost in 2026?", a: "**฿500 for adults** on the standard day ticket and **฿700** for the sunset tour. Children under 110 cm pay ฿250 (day) or ฿350 (sunset). Entry generally includes a guided walk and access to the cultural performances on the grounds." },
                    { q: "Is the Sanctuary of Truth finished?", a: "**No — and it never will be.** Construction began in 1981 and continues daily by design. Its founder, Lek Viriyaphan, wanted a building in permanent creation, with new carvings added by each generation for as long as the takien hardwood posts last — an estimated 600 years. You visit an active building site." },
                    { q: "Why do you have to wear a hard hat at the Sanctuary of Truth?", a: "Because it is a genuine, active construction site with carvers working on scaffolding above visitor areas, and material occasionally falls. Hard hats are issued at the entrance and wearing them is mandatory, not ceremonial." },
                    { q: "Is the Sanctuary of Truth really built without nails?", a: "Yes. The entire 105-metre structure is held together by **traditional Thai wooden joinery and dowel pegs** — no nails, no structural steel, no concrete. Every visible surface is hand-carved. It's the largest all-wooden building in Thailand." },
                    { q: "How long do you need at the Sanctuary of Truth?", a: "**1.5–2 hours** covers the building, the grounds and a cultural show comfortably. Photographers will want longer. Visit in **late afternoon**, when low sun brings out the colour of the teak and the heat has dropped — the sunset ticket exists for good reason." },
                    { q: "How do you get to the Sanctuary of Truth?", a: "It's on the headland at **Naklua in north Pattaya**, 10–15 minutes from the city centre. Take a blue songthaew along Beach Road toward Naklua (฿10–20 plus a short walk), or a Grab/taxi for ฿100–200. Parking is available if you drive." }
                ],
                jsonLd: {
                    "@context": "https://schema.org",
                    "@graph": [
                        {
                            "@type": "FAQPage",
                            "mainEntity": [
                                { "@type": "Question", "name": "How much does the Sanctuary of Truth cost in 2026?", "acceptedAnswer": { "@type": "Answer", "text": "฿500 for adults on the standard day ticket and ฿700 for the sunset tour. Children under 110 cm pay ฿250 day or ฿350 sunset. Entry generally includes a guided walk." } },
                                { "@type": "Question", "name": "Is the Sanctuary of Truth finished?", "acceptedAnswer": { "@type": "Answer", "text": "No — and it never will be. Construction began in 1981 and continues by design. Founder Lek Viriyaphan wanted a building in permanent creation, with new carvings added each generation for as long as the takien posts last, an estimated 600 years." } },
                                { "@type": "Question", "name": "Is the Sanctuary of Truth really built without nails?", "acceptedAnswer": { "@type": "Answer", "text": "Yes. The entire 105-metre structure uses traditional Thai wooden joinery and dowel pegs — no nails, no structural steel, no concrete. It is the largest all-wooden building in Thailand." } },
                                { "@type": "Question", "name": "How long do you need at the Sanctuary of Truth?", "acceptedAnswer": { "@type": "Answer", "text": "1.5–2 hours covers the building, grounds and a cultural show. Visit in late afternoon when low sun brings out the colour of the teak." } }
                            ]
                        }
                    ]
                },
                fastFacts: [
                    { icon: 'Ticket', label: 'Entry 2026', value: '฿500 day / ฿700 sunset' },
                    { icon: 'History', label: 'Under Construction', value: 'Since 1981 — by design' },
                    { icon: 'AlertTriangle', label: 'Required', value: 'Hard hat + covered knees' }
                ]
            };

        case "koh-larn-island-guide":
            return {
                title: "Koh Larn (Coral Island) Guide 2026: Ferries, Beaches & How to Do It Right",
                description: "Koh Larn is 7 km off Pattaya and looks nothing like it. Ferry times and the new ฿40 fare, all six beaches compared, how to avoid the tour-group crush, and what to skip.",
                heroImage: IMG.kohLarn,
                sections: [
                    {
                        title: "The Island That Redeems Pattaya",
                        icon: "Star",
                        content: "Pattaya's beaches are, honestly, not why anyone should come to Thailand. Then you take a forty-five minute ferry seven kilometres offshore and find water that is properly turquoise, sand that is properly white, and headlands covered in green — and the whole calculation about the region changes.\n\n**Koh Larn** — officially *Koh Lan*, and marketed relentlessly as **\"Coral Island\"** — is a small island of about 4 km² off Pattaya's coast, with six beaches, a handful of villages, some genuinely good seafood and a resident population that has lived there long before tourism arrived. It is the single best thing you can do from Pattaya for under ฿500, and it is what makes a Pattaya trip worthwhile for a lot of visitors.\n\nIt is also **extremely popular**, and that's the tension you need to plan around. Chinese, Indian and Russian tour groups arrive by the boatload; the main beach can be shoulder to shoulder by 11 AM; and the jet-ski and banana-boat trade is loud and constant on the busiest sand. The island is genuinely beautiful *and* genuinely crowded, and which one dominates your day depends almost entirely on **which beach you go to and what time you arrive**.\n\nThe good news is that avoiding the crush is easy once you know how — most day-trippers go to exactly one beach and never leave it.",
                        tourCard: CARD.kohLarn,
                    },
                    {
                        title: "Getting There: Ferries, Speedboats and the New Fare",
                        icon: "Ticket",
                        content: "**The public ferry** leaves from **Bali Hai Pier** at the southern end of Pattaya Beach (the far end of Walking Street — this is one of the few reasons most visitors go near it).\n\n**The fare went up in 2026.** From **10 April 2026**, a **flat ฿40 per person** applies to all passengers departing Bali Hai Pier — an increase from the ฿30 fare that had held for sixteen years, driven by fuel costs. It remains one of the best-value boat rides in Thailand.\n\n**Typical departures from Bali Hai Pier**: 7:00, 10:00, 12:00, 14:00, 15:30, 17:00 and 18:30. **Returns from Koh Larn's Tawaen Beach pier** run roughly hourly in the early afternoon — around 13:00, 14:00, 15:00 and 16:00 — with services from Na Baan (the main village pier) running later.\n\n**Crossing time**: the public ferry takes roughly **45 minutes**. Chartered **speedboats** do it in about **15**, and cost substantially more (฿1,500–3,000 for the boat, depending on size and negotiation).\n\n**Which pier you land at matters.** Ferries go to either **Na Baan** (the main village, from which you take onward transport) or **Tawaen Beach** (the busiest beach directly). Check which one your ferry serves before boarding.\n\n**Critical practical warning: check the last return ferry time and treat it seriously.** Missing it means either chartering a speedboat back at a painful price or staying the night. Timetables shift with season and weather, so confirm the final departure when you arrive, not from a website.\n\n**Or take an organised trip.** A [speedboat day trip with lunch and hotel pickup](/thailand/pattaya/koh-larn-coral-island-full-day-tour) removes the pier logistics, the return-ferry anxiety and the onward-transport haggling — which for a first visit is worth a lot.",
                    },
                    {
                        title: "The Six Beaches, Honestly Compared",
                        icon: "Map",
                        content: "This is the part that determines your day.\n\n**Tawaen Beach** — The main one, and where virtually every tour group lands. Longest stretch of sand, every facility (loungers, restaurants, showers, shops), and every watersport: jet skis, parasailing, banana boats, sea walking. It is also **by far the most crowded and the loudest**, and the constant jet-ski traffic makes swimming less pleasant. Fine if you want facilities and activity; avoid if you want calm.\n\n**Samae Beach** — The best all-rounder for most visitors. Softer sand, clearer and calmer water than Tawaen, decent restaurants, still busy but noticeably less frantic. If you only move one beach from the default, move here.\n\n**Nual Beach (Monkey Beach)** — The prettiest on the island and the quietest of the accessible ones, tucked on the southern end. Smaller, with limited facilities, which is precisely why it stays pleasant. Best swimming water.\n\n**Tien Beach** — Quiet, west-facing, and the sunset beach. Reasonable facilities, far fewer people, and a good spot to end the day if you're on a late ferry.\n\n**Thong Lang Beach** — Rocky, undeveloped, very few visitors. Not a swimming beach — come for solitude and views.\n\n**Ta Yai Beach** — Small, quiet, minimal facilities.\n\n**Getting between them**: **songthaews** meet the ferries and run to the main beaches for **฿20–40 per person**. **Motorbike taxis** cost a little more. **Renting a scooter (฿200–300/day)** is the popular option and gives you the whole island — but the roads are steep, narrow and have genuinely dangerous sections, accidents are common, and helmet and licence rules apply. If you're not a confident rider, don't start here.",
                    },
                    {
                        title: "Timing It: How to Avoid the Crush",
                        icon: "Clock",
                        content: "Koh Larn's crowding is highly predictable, which makes it easy to dodge.\n\n**Take the 7:00 AM ferry.** This single decision transforms the day. You'll be on the island by around 8:00, with two to three hours of near-empty beaches before the tour-group boats arrive around 10:30–11:00. The water is calmest in the morning and the light is best.\n\n**Or go late.** Take the 15:30 or 17:00 ferry, watch sunset from Tien Beach and stay overnight — there are guesthouses and small resorts on the island. **Staying a night on Koh Larn is the island's best-kept secret**: after the last day-tripper ferry leaves around 6 PM, the place empties out entirely and you get one of the more peaceful nights on the eastern seaboard.\n\n**Avoid weekends and Thai public holidays.** Bangkok comes down for these and the island fills accordingly. Weekdays are dramatically better.\n\n**Best season**: **November to February**, when the Gulf is calm and the water clearest. March–May is very hot. June–October brings monsoon swell, which can make the crossing rough and occasionally cancels services.\n\n**Skip the \"Coral Island\" snorkelling sales pitch.** Boats will offer snorkelling stops billed around coral viewing. The reefs immediately around Koh Larn have been substantially damaged by decades of boat traffic, anchors and sunscreen, and the snorkelling is mediocre compared to Thailand's Andaman coast. If underwater time is your priority, the [outer islands by catamaran](/thailand/pattaya/monkey-island-chonburi-boat-tour) — Koh Sak and Koh Phai — are clearer and quieter, and the Andaman side of the country is another league entirely.\n\n**The realistic pitch for Koh Larn** is not world-class snorkelling. It's a genuinely lovely beach day, twenty minutes and ฿40 from a city that doesn't have one.",
                        tourCard: CARD.catamaran,
                    },
                    {
                        title: "Practical Notes, Costs and Etiquette",
                        icon: "Wallet",
                        content: "**What a day costs** (per person, doing it independently):\n- Return ferry: **฿80**\n- Songthaew to your beach and back: ฿40–80\n- Sun lounger and umbrella: ฿100–150 for the day\n- Seafood lunch at a beach restaurant: ฿200–400\n- **Total: roughly ฿450–700 (about $13–20)** for a full day. Very few beach days anywhere cost less.\n\nWatersports add up fast: jet ski ฿800–1,500 per 30 minutes, parasailing ฿400–600 per flight, banana boat ฿200–300. **Agree the price and duration before you get on anything**, and photograph any jet ski before you ride it — damage-claim disputes are a known problem across Thai beach resorts, Pattaya included.\n\n**What to bring**: cash (card acceptance is patchy), reef-safe mineral sunscreen, a hat, water, and a dry bag. There are ATMs in Na Baan village but don't rely on them.\n\n**Food**: the beach restaurants are decent and reasonably priced for grilled seafood, som tam and fried rice. **Na Baan village** has cheaper and better local food than any of the beaches if you're willing to walk.\n\n**Respect that people live here.** Koh Larn has a permanent community, a school and temples. Beachwear is for the beach — cover up in the village. Take your rubbish with you; waste management on a small island under heavy day-tripper load is a genuine problem, and the island periodically struggles with it.\n\n**Wat Khao Yai**, the hilltop temple, and the island's viewpoints are worth the scooter or songthaew trip if you have a full day — the view back across the water to Pattaya's skyline is the best perspective you'll get on the whole bay.\n\nBuilding out the rest of your trip? See [where to stay in Pattaya](/thailand/pattaya/where-to-stay-in-pattaya) and our [honest take on the city](/thailand/pattaya/is-pattaya-worth-visiting).",
                    }
                ],
                faqs: [
                    { q: "How much is the ferry to Koh Larn in 2026?", a: "**฿40 per person each way** from Bali Hai Pier. The flat ฿40 rate took effect on **10 April 2026**, replacing a ฿30 fare that had held for sixteen years. The public ferry takes about 45 minutes; chartered speedboats do it in roughly 15 for ฿1,500–3,000 per boat." },
                    { q: "What is the ferry schedule from Pattaya to Koh Larn?", a: "Departures from **Bali Hai Pier** typically run at 7:00, 10:00, 12:00, 14:00, 15:30, 17:00 and 18:30. Returns from Tawaen Beach pier run roughly hourly in the early afternoon (around 13:00–16:00), with later services from Na Baan. **Always confirm the last return time on arrival** — missing it is expensive." },
                    { q: "Which is the best beach on Koh Larn?", a: "**Samae Beach** is the best all-rounder — clearer, calmer water and softer sand than the main beach, with decent facilities. **Nual (Monkey) Beach** is the prettiest and quietest. **Tawaen** is the biggest and has every facility and watersport, but it's where all the tour groups land and is by far the most crowded." },
                    { q: "How do I avoid the crowds on Koh Larn?", a: "**Take the 7:00 AM ferry** — you'll get two to three hours of near-empty beaches before the tour boats arrive around 10:30. Avoid weekends and Thai public holidays. Better still, **stay overnight**: after the last day-tripper ferry leaves around 6 PM the island empties out completely." },
                    { q: "Is the snorkelling good at Koh Larn?", a: "Not especially. The reefs around Koh Larn have been substantially damaged by decades of boat traffic and anchoring, despite the \"Coral Island\" marketing. The outer islands (Koh Sak, Koh Phai) are clearer, and Thailand's Andaman coast is in a different league. Come to Koh Larn for the beach day, not the reef." },
                    { q: "How much does a day on Koh Larn cost?", a: "About **฿450–700 ($13–20)** independently: ฿80 return ferry, ฿40–80 songthaew, ฿100–150 for a lounger and umbrella, and ฿200–400 for a seafood lunch. Watersports cost extra — always agree the price and duration before getting on anything." }
                ],
                jsonLd: {
                    "@context": "https://schema.org",
                    "@graph": [
                        {
                            "@type": "FAQPage",
                            "mainEntity": [
                                { "@type": "Question", "name": "How much is the ferry to Koh Larn in 2026?", "acceptedAnswer": { "@type": "Answer", "text": "฿40 per person each way from Bali Hai Pier. The flat ฿40 rate took effect on 10 April 2026, replacing a ฿30 fare held for sixteen years. The public ferry takes about 45 minutes; speedboats roughly 15." } },
                                { "@type": "Question", "name": "Which is the best beach on Koh Larn?", "acceptedAnswer": { "@type": "Answer", "text": "Samae Beach is the best all-rounder with clearer, calmer water than the main beach. Nual (Monkey) Beach is the prettiest and quietest. Tawaen has every facility but is where all the tour groups land." } },
                                { "@type": "Question", "name": "How do I avoid the crowds on Koh Larn?", "acceptedAnswer": { "@type": "Answer", "text": "Take the 7:00 AM ferry for two to three hours of near-empty beaches before tour boats arrive around 10:30. Avoid weekends and Thai holidays, or stay overnight — the island empties after the last ferry around 6 PM." } },
                                { "@type": "Question", "name": "Is the snorkelling good at Koh Larn?", "acceptedAnswer": { "@type": "Answer", "text": "Not especially — the reefs have been substantially damaged by decades of boat traffic and anchoring despite the Coral Island marketing. The outer islands are clearer, and the Andaman coast is far better." } }
                            ]
                        }
                    ]
                },
                fastFacts: [
                    { icon: 'Ticket', label: 'Ferry Fare', value: '฿40 each way (from Apr 2026)' },
                    { icon: 'Clock', label: 'Crossing', value: '45 min ferry / 15 min speedboat' },
                    { icon: 'Star', label: 'Best Beach', value: 'Samae (or Nual for quiet)' }
                ]
            };

        case "where-to-stay-in-pattaya":
            return {
                title: "Where to Stay in Pattaya 2026: Every Area Compared (Jomtien, Naklua, Pratumnak & More)",
                description: "In Pattaya the neighbourhood decides the holiday. Jomtien, Naklua, Pratumnak, Wongamat, Central and South Pattaya compared honestly — who each suits and which to avoid.",
                heroImage: IMG.bigBuddha,
                sections: [
                    {
                        title: "Why This Decision Matters More Here Than Anywhere",
                        icon: "AlertTriangle",
                        content: "In most beach destinations, picking the wrong neighbourhood costs you convenience. In Pattaya it can cost you the entire trip.\n\nThe city stretches roughly **15 kilometres** along the Gulf coast, and its districts are startlingly different from one another. Within a twenty-minute drive you can go from a quiet Thai seafood village where nothing happens after 9 PM, to a family beach lined with long-stay condos, to a 500-metre strip of neon that is among the most notorious nightlife districts in the world.\n\nAll of these are \"Pattaya.\" Booking a hotel because it looked nice and was cheap, without checking which of them it sits in, is how people end up writing furious reviews about a city that other people love.\n\nSo before anything else, answer one question: **what do you want your evenings to sound like?** Everything follows from that.\n\nThe areas, running **north to south**:\n\n- **Naklua** — quiet, Thai, seafood, families\n- **Wongamat** — upscale beachfront, resorts, couples\n- **Central Pattaya** — convenient, busy, shopping, mixed\n- **Pratumnak Hill** — the green buffer zone, the best compromise\n- **South Pattaya / Walking Street** — the nightlife district\n- **Jomtien** — long beach, families and long-stayers\n- **Na Jomtien & Bang Saray** — quiet, resort-y, further out\n\nIf you're still deciding whether to come at all, start with our [honest assessment of Pattaya](/thailand/pattaya/is-pattaya-worth-visiting).",
                    },
                    {
                        title: "The Quiet North: Naklua & Wongamat",
                        icon: "CheckCircle2",
                        content: "**Naklua — the local choice.** The northern end of the city, and the part that most resembles what Pattaya was before the 1960s: a working Thai coastal community with a large fresh fish market, temples, and streets where the signage is in Thai rather than five alphabets. There is **essentially no nightlife**, which is the point.\n\n*Stay here if*: you want quiet, you're travelling with family, and you care about food. Naklua's seafood is the best in the city — buying fish at the market and having a restaurant cook it is a genuine Pattaya highlight.\n*Downsides*: the beach here is unremarkable, and you'll rely on songthaews or Grab to get anywhere else.\n*Bonus*: the [Sanctuary of Truth](/thailand/pattaya/sanctuary-of-truth-pattaya) is here, on the headland.\n\n**Wongamat — quiet with a good beach.** Immediately south of Naklua, this is Pattaya's upscale beachfront strip: a genuinely decent stretch of sand backed by five-star resorts and high-end condos, with none of the central chaos. Fifteen minutes from the middle of town when you want it.\n\n*Stay here if*: you want a resort holiday with a real beach, you're a couple, or you want quiet without giving up sand. This is where most \"I didn't expect to like Pattaya\" reviews come from.\n*Downsides*: the most expensive area in the city, and you're eating in your hotel unless you travel.\n\n**Both areas** are excellent for families and for anyone whose main association with Pattaya is the thing they want to avoid. From here, the nightlife districts are a deliberate 20-minute trip rather than something happening under your window.",
                        tourCard: CARD.sanctuary,
                    },
                    {
                        title: "The Middle: Central Pattaya, Pratumnak & South",
                        icon: "Map",
                        content: "**Central Pattaya — maximum convenience, mixed atmosphere.** The commercial heart: Central Festival mall, Beach Road, the widest choice of hotels at every price point, restaurants of every nationality, and the shortest distance to everything. Beach Road has been rebuilt and widened in recent years and is better than its reputation.\n\n*Stay here if*: you want to walk to shops, restaurants and transport, you're on a short trip, or you want the cheapest good-value hotels.\n*Downsides*: **Pattaya Beach itself is the city's weakest** — narrow, busy, unimpressive water. Traffic and noise are constant. Some streets off Beach Road shade into the adult nightlife scene, so check your hotel's exact soi, not just \"Central Pattaya.\"\n\n**Pratumnak Hill — the smart compromise, and our general pick.** A green headland separating central Pattaya from Jomtien, with quiet residential streets, small coves like **Cosy Beach**, the Big Buddha temple (Wat Phra Yai), and the best viewpoint in the city. Ten minutes from central Pattaya, ten from Jomtien, and completely removed from both in character.\n\n*Stay here if*: you want quiet and a decent beach but still want easy access to the city. For most visitors who aren't sure what they want, **this is the right answer**.\n*Downsides*: it's a hill — walking is limited, so you'll use Grab or a scooter. Fewer restaurants than central.\n\n**South Pattaya / Walking Street — for those who came for it.** The nightlife district. Walking Street itself is pedestrianised after 6 PM and runs until very late, and the noise carries for blocks.\n\n*Stay here only if*: this is specifically and knowingly why you came.\n*Otherwise avoid* — including for the practical reason that sleep is genuinely difficult in the surrounding sois until 3 AM. Note that **Bali Hai Pier**, for [Koh Larn ferries](/thailand/pattaya/koh-larn-island-guide), is at the far southern end of Walking Street, which is why most visitors pass through here at least once in daylight.",
                        tourCard: CARD.bigBuddha,
                    },
                    {
                        title: "The South: Jomtien, Na Jomtien & Bang Saray",
                        icon: "Star",
                        content: "**Jomtien — the family and long-stay beach.** A 6 km stretch of beach south of Pratumnak, and the most popular alternative base to central Pattaya. **The beach is considerably better than Pattaya Beach** — wider, cleaner, with a proper palm-lined promenade. The atmosphere is relaxed and residential: condo towers, long-stay Europeans and Russians, families, a big weekend Thai crowd, and Thailand's largest night market at Jomtien Night Market.\n\n*Stay here if*: you're with children, staying a week or more, want a real beach day-to-day, or want good value. It's the most common recommendation for families, and rightly.\n*Downsides*: it's spread out, so where on the 6 km you land matters — the northern end is livelier and closer to town, the southern end quieter. It's also 20–30 minutes from north Pattaya's attractions.\n*Watersports*: the kitesurfing, jet-ski and parasail infrastructure here is the best in the region.\n\n**Na Jomtien** — further south again, quieter still, dominated by newer resorts and condos. Good for a resort holiday where you don't intend to leave much. You will need transport for everything.\n\n**Bang Saray** — 20 minutes south of Jomtien, a genuine fishing village with a pier, seafood restaurants over the water, and almost no tourism infrastructure. **This is where to stay if you want the coast without the city at all** — and it's within easy reach of [Nong Nooch Tropical Garden](/thailand/pattaya/nong-nooch-tropical-garden-pattaya-cultural-tour) and the elephant sanctuaries inland.\n\n*Stay here if*: you want quiet, seafood and local atmosphere, and you have a car or don't mind Grab fares.\n*Downsides*: genuinely remote from Pattaya's attractions; not a base for a short trip.",
                        tourCard: CARD.elephants,
                    },
                    {
                        title: "Quick Picks, Prices and Getting Around",
                        icon: "Wallet",
                        content: "**Choose by traveller type:**\n\n- **First-timers, unsure** → **Pratumnak Hill**\n- **Families with kids** → **Jomtien** or **Naklua**\n- **Couples, resort holiday** → **Wongamat** or Na Jomtien\n- **Short trip, want convenience** → **Central Pattaya** (check the soi)\n- **Budget travellers** → **Central Pattaya** back streets or **Jomtien**\n- **Long stays / remote work** → **Jomtien**\n- **Quiet, food, local feel** → **Naklua** or **Bang Saray**\n- **Nightlife** → **South Pattaya** (and only if deliberate)\n\n**What accommodation costs** — Pattaya is significantly cheaper than Phuket or Samui for equivalent quality:\n- Budget guesthouse/hotel: **฿500–1,000/night**\n- Good 3–4 star with pool: **฿1,200–2,500**\n- Beachfront 5-star (Wongamat, Na Jomtien): **฿3,500–8,000**\n- Monthly condo rental with sea view: **฿12,000–25,000**\n\n**High season is November–February**, when the Gulf is calm and prices peak — book 3–4 weeks ahead, more over Christmas and New Year. Low season (June–October) brings substantial discounts.\n\n**Getting around**: **songthaews** (the blue shared trucks) run fixed loops along Beach Road and Second Road for **฿10–20** — hop on, press the buzzer to get off. Don't ask the price first; if you do, the driver may quote a private charter rate. **Grab** works well and is transparent (฿60–150 across town). **Motorbike taxis** for short hops. **Scooter rental** ฿200–300/day, but Pattaya traffic is genuinely dangerous and police checks are frequent — most travel insurance is void without a motorcycle licence.\n\n**One last tip**: check on a map exactly where your hotel sits relative to Walking Street before booking. \"Pattaya Beach Road\" covers several kilometres and a very wide range of experiences.",
                    }
                ],
                faqs: [
                    { q: "What is the best area to stay in Pattaya?", a: "**Pratumnak Hill** for most visitors — a quiet green headland with small beaches, ten minutes from both central Pattaya and Jomtien, and removed from the nightlife entirely. Choose **Jomtien** or **Naklua** for families, **Wongamat** for an upscale beach resort, and **Central Pattaya** if you want maximum convenience." },
                    { q: "Where should families stay in Pattaya?", a: "**Jomtien** — a 6 km beach that's considerably better than Pattaya Beach, with a palm-lined promenade, relaxed residential atmosphere and good value — or **Naklua** in the north, which is quiet, Thai and has the city's best seafood. Both are far removed from the nightlife districts." },
                    { q: "Which part of Pattaya should I avoid?", a: "**South Pattaya around Walking Street**, unless the nightlife is specifically why you're coming. Beyond the atmosphere, the practical issue is noise — the street is pedestrianised from 6 PM and runs until very late, and sleep in the surrounding sois is genuinely difficult until around 3 AM." },
                    { q: "Is Jomtien better than Pattaya Beach?", a: "For staying, yes for most people. **Jomtien's beach is wider, cleaner and backed by a proper promenade**, and the area is calmer and more residential. Pattaya Beach is narrow and busy with unimpressive water, though Central Pattaya wins on convenience and choice of restaurants and shops." },
                    { q: "How much does a hotel cost in Pattaya?", a: "**฿500–1,000** for a budget hotel, **฿1,200–2,500** for a good 3–4 star with a pool, and **฿3,500–8,000** for beachfront five-star in Wongamat or Na Jomtien. Monthly condo rentals with sea views run ฿12,000–25,000. Pattaya is meaningfully cheaper than Phuket or Samui for equivalent quality." },
                    { q: "How do you get around Pattaya?", a: "**Songthaews** (blue shared trucks) run fixed loops along Beach Road and Second Road for ฿10–20 — hop on and press the buzzer to stop. Don't ask the price first, or you may be quoted a private charter rate. **Grab** is transparent at ฿60–150 across town. Scooters are ฿200–300/day but the traffic is genuinely dangerous." }
                ],
                jsonLd: {
                    "@context": "https://schema.org",
                    "@graph": [
                        {
                            "@type": "FAQPage",
                            "mainEntity": [
                                { "@type": "Question", "name": "What is the best area to stay in Pattaya?", "acceptedAnswer": { "@type": "Answer", "text": "Pratumnak Hill for most visitors — a quiet green headland with small beaches, ten minutes from both central Pattaya and Jomtien. Jomtien or Naklua for families, Wongamat for an upscale beach resort, Central Pattaya for convenience." } },
                                { "@type": "Question", "name": "Where should families stay in Pattaya?", "acceptedAnswer": { "@type": "Answer", "text": "Jomtien — a 6 km beach considerably better than Pattaya Beach, relaxed and residential — or Naklua in the north, which is quiet, Thai and has the best seafood. Both are far from the nightlife districts." } },
                                { "@type": "Question", "name": "Which part of Pattaya should I avoid?", "acceptedAnswer": { "@type": "Answer", "text": "South Pattaya around Walking Street, unless nightlife is specifically why you're coming. Walking Street is pedestrianised from 6 PM and runs very late, making sleep difficult in surrounding sois until around 3 AM." } },
                                { "@type": "Question", "name": "How much does a hotel cost in Pattaya?", "acceptedAnswer": { "@type": "Answer", "text": "฿500–1,000 budget, ฿1,200–2,500 for a good 3–4 star with pool, ฿3,500–8,000 for beachfront five-star. Monthly condo rentals run ฿12,000–25,000. Cheaper than Phuket or Samui for equivalent quality." } }
                            ]
                        }
                    ]
                },
                fastFacts: [
                    { icon: 'Star', label: 'Best All-Round', value: 'Pratumnak Hill' },
                    { icon: 'CheckCircle2', label: 'Families', value: 'Jomtien or Naklua' },
                    { icon: 'AlertTriangle', label: 'Avoid Unless Deliberate', value: 'South Pattaya' }
                ]
            };

        default:
            return null;
    }
}
