// Tokyo authority pages (2026-08). Same CityInfoData shape as cityInfoContent.ts.
// Reached via getJapanInfoContent() -> getCityInfoContent().
//
// Every price, date and rule here was verified against a primary source in
// August 2026. Two traps worth knowing if you edit this file:
//   - Tokyo Skytree scrapped weekday/holiday and advance/same-day pricing on
//     2026-04-01 and went to per-day variable pricing. Most third-party guides
//     still publish the dead table.
//   - The Hachiko statue did NOT move in 2023. Its last move was May 1989.
import type { CityInfoData } from './cityInfoContent';

const IMG = {
    walking: "https://res.cloudinary.com/dx2fxyaft/image/upload/v1786740171/asiabylocals/tours/tokyo-private-walking-tour-local-guide/hq_tour_img_1.jpg",
    ebike: "https://res.cloudinary.com/dx2fxyaft/image/upload/v1786740232/asiabylocals/tours/tokyo-ebike-city-highlights-3-hours/hq_tour_img_1.jpg",
    kart: "https://res.cloudinary.com/dx2fxyaft/image/upload/v1786740222/asiabylocals/tours/tokyo-go-kart-shibuya-crossing-photo-stop/hq_tour_img_1.png",
    neon: "https://res.cloudinary.com/dx2fxyaft/image/upload/v1786740190/asiabylocals/tours/tokyo-shibuya-neon-night-photo-walk/hq_tour_img_1.jpg",
    yanaka: "https://res.cloudinary.com/dx2fxyaft/image/upload/v1786740245/asiabylocals/tours/tokyo-ebike-hidden-neighbourhoods-3-hours/hq_tour_img_1.jpg",
    food: "https://res.cloudinary.com/dx2fxyaft/image/upload/v1787169079/asiabylocals/tours/togoshi-ginza-hidden-food-tour/hq_tour_img_1.jpg",
    kartEast: "https://res.cloudinary.com/dx2fxyaft/image/upload/v1786740200/asiabylocals/tours/tokyo-go-kart-asakusa-skytree-akihabara/hq_tour_img_1.png",
};

const CARD = {
    walking: { slug: "shibuya-crossing-walking-tour", title: "Tokyo Your Way: Private Walking Day with a Local Guide", description: "Six hours with no fixed route — the day is built around what you actually want to see.", price: "From $85", duration: "6 hours", image: IMG.walking },
    halfDay: { slug: "meiji-shrine-half-day-tour", title: "Your Tokyo, Your Route: Private Half-Day", description: "Four hours covering Meiji Shrine, Shibuya and either Asakusa or Nakano Broadway.", price: "From $50", duration: "4 hours", image: IMG.walking },
    ebike: { slug: "imperial-palace-bike-tour", title: "Central Tokyo by E-Bike", description: "Imperial Palace moat, Nihonbashi, Ginza and Tsukiji — four times the ground a walking tour covers.", price: "From $63", duration: "3 hours", image: IMG.ebike },
    yanaka: { slug: "yanaka-backstreets-bike-tour", title: "Tokyo Backstreets by E-Bike: Yanaka", description: "The shitamachi lanes that survived both 1923 and the firebombing.", price: "From $63", duration: "3 hours", image: IMG.yanaka },
    kart: { slug: "shibuya-crossing-crossing-photography-tour", title: "Shibuya Crossing Go-Kart Ride with Photo Stops", description: "Street-legal kart through the scramble itself, costume and photos included.", price: "From $79", duration: "1 hour", image: IMG.kart },
    kartEast: { slug: "tokyo-skytree-spiritual-tour", title: "Asakusa to Akihabara Go-Kart Run", description: "Old Tokyo, the Sumida under Skytree, then Electric Town — the quieter east-side route.", price: "From $81", duration: "70 minutes", image: IMG.kartEast },
    neon: { slug: "shibuya-crossing-photography-tour", title: "Shibuya After Dark: Private Neon Photo Walk", description: "A local photographer shoots you through the crossing and the lantern-lit back alleys.", price: "From $116", duration: "1 hour", image: IMG.neon },
    nightBike: { slug: "tokyo-tower-bike-tour", title: "Tokyo After Dark by Bike", description: "Omotesando and Roppongi to a floodlit Tokyo Tower, finishing in Aoyama Cemetery's silence.", price: "From $48", duration: "2 hours", image: IMG.ebike },
    food: { slug: "togoshi-ginza-shotengai-food-tour", title: "Togoshi Ginza Food Walk", description: "Tokyo's longest shopping street — 1.3 km, 400 shops, no other tour groups.", price: "From $113", duration: "3 hours", image: IMG.food },
};

export function getTokyoInfoContent(slug: string): CityInfoData | null {
    switch (slug) {

        case "best-time-to-visit-tokyo":
            return {
                title: "Best Time to Visit Tokyo: Month-by-Month Weather, Sakura & Crowd Guide (2026)",
                seoTitle: "Best Time to Visit Tokyo (2026 Month Guide)",
                description: "Tokyo's wettest month is October, not June. JMA climate normals month by month, real 2026 cherry blossom dates, rainy season truths, and the exact holiday weeks to avoid.",
                heroImage: IMG.walking,
                sections: [
                    {
                        title: "The Short Answer",
                        icon: "Star",
                        content: "**Late March to early April** and **late October to early December** are Tokyo's two best windows, and they are best for opposite reasons.\n\n**Spring** buys you cherry blossom and mild days — Tokyo's April normal is 19.4°C high, 9.8°C low. It also buys you the heaviest crowds of the year and the highest hotel rates.\n\n**Late autumn** is the quietly better deal. November averages a 16.7°C high with just **96.3 mm of rain and 64% humidity** — the driest, clearest stretch of the year — and the ginkgo and maple peak runs from late November into early December.\n\nThe months to think hard about are **July and August**, which are genuinely punishing now, and **September and October**, which most guides wrongly sell as \"dry autumn.\"\n\nEvery figure on this page comes from the Japan Meteorological Agency's 1991–2020 climate normals for Tokyo station 47662."
                    },
                    {
                        title: "Month-by-Month: The Actual Numbers",
                        icon: "Clock",
                        content: "JMA 1991–2020 normals for Tokyo. High and low are °C, rain in mm, humidity as a percentage.\n\n| Month | High | Low | Rain | Humidity |\n|---|---|---|---|---|\n| January | 9.8 | 1.2 | 59.7 | 51% |\n| February | 10.9 | 2.1 | 56.5 | 52% |\n| March | 14.2 | 5.0 | 116.0 | 57% |\n| April | 19.4 | 9.8 | 133.7 | 62% |\n| May | 23.6 | 14.6 | 139.7 | 68% |\n| June | 26.1 | 18.5 | 167.8 | 75% |\n| July | 29.9 | 22.4 | 156.2 | 76% |\n| August | 31.3 | 23.5 | 154.7 | 74% |\n| **September** | 27.5 | 20.3 | **224.9** | 75% |\n| **October** | 22.0 | 14.8 | **234.8** | 71% |\n| November | 16.7 | 8.8 | 96.3 | 64% |\n| December | 12.0 | 3.8 | 57.9 | 56% |\n\n**The number that surprises everyone: October is Tokyo's wettest month, and September is second.** Not June, not the rainy season. That rain is typhoon rain, and it arrives in heavy bursts rather than the steady drizzle of tsuyu. Most travel pages get this backwards.\n\nOne caveat if you cross-check elsewhere: Tokyo's thermometer moved from Otemachi to Kitanomaru Park in **December 2014**, and the new site runs about 0.9°C cooler in daily mean. JMA rebased the normals to the new site, so don't mix these figures with older 1981–2010 tables still floating around."
                    },
                    {
                        title: "Cherry Blossom: What Actually Happened in 2026",
                        icon: "Star",
                        image: IMG.neon,
                        content: "Tokyo's **long-term normal is 24 March for first bloom (kaika) and 31 March for full bloom (mankai)**. Pages still quoting 26 March and 3 April are using the retired 1981–2010 normals.\n\n**2026 was an early year: first bloom 19 March, full bloom 28 March** — five days ahead of normal. For context on how much this moves:\n\n| Year | First bloom | Full bloom |\n|---|---|---|\n| 2023 | 14 March | 22 March |\n| 2024 | 29 March | 4 April |\n| 2025 | 24 March | 30 March |\n| **2026** | **19 March** | **28 March** |\n\nThat is a **15-day spread in first-bloom dates across four years**, which is exactly why booking flights around sakura a year ahead is a gamble.\n\n**How the date is decided:** Tokyo's declaration hangs on specific Somei-Yoshino sample trees at **Yasukuni Shrine**. Kaika is called the first day **five or six blossoms** are open; mankai when about **80% of buds** are. On 18 March 2026 two blossoms had opened and JMA held off; the next day it counted 61 and declared.\n\n**Forecasts are good but late.** Japan Meteorological Corporation's first 2026 forecast, issued 18 December 2025, called 19 March for Tokyo and was exactly right. Weathernews moved between 18 and 22 March across five revisions. Expect accuracy within one to three days, but only from **early March**.\n\n**If you miss peak:** [Shinjuku Gyoen](/japan/tokyo) holds over 1,000 trees including early and late varieties, which stretches the usable window by a week either side of the Yasukuni date."
                    },
                    {
                        title: "The Rainy Season Is Not What You Think",
                        icon: "AlertTriangle",
                        content: "Kanto's tsuyu normally runs **around 7 June to around 19 July**. JMA always writes *around* — these are never sharp dates.\n\nBut here is the trap almost every English page falls into. **JMA announces tsuyu twice.** A preliminary call is made live during the season from forecasts; a **confirmed value is issued in early September** after reviewing what the weather actually did. In 2025 that revision moved the start **19 days earlier** (10 June → 22 May) and the end **20 days earlier** (18 July → 28 June), making 2025 the earliest tsuyu end since records began in 1951. Any page still saying \"the 2025 rainy season ended 18 July\" is quoting a dead number.\n\n**2026's preliminary dates are around 7 June to around 20 July**, and the confirmed values were not out at the time of writing. Tokyo recorded 299.0 mm across that period against a 253.0 mm normal.\n\nWhat tsuyu actually feels like: humidity in the mid-70s, grey skies, and rain that comes and goes rather than falling all day. Temples photograph beautifully in it, hydrangeas are at their peak, and hotel rates are noticeably softer. It is a genuinely underrated time to visit if you are not chasing blue sky."
                    },
                    {
                        title: "Summer: Be Honest With Yourself",
                        icon: "AlertTriangle",
                        content: "August normals are a **31.3°C high with 23.5°C nights and 74% humidity**, and July is barely gentler at 29.9°C. Those are the *normals* — recent summers have run hotter.\n\nThe part the numbers don't convey is the nights. A 23.5°C average low means the city never really cools, and walking days that would be pleasant in April become genuinely draining. If your itinerary is temples and neighbourhoods on foot, July and August will cut what you actually manage to see.\n\n**If you are locked into summer**, the workarounds are real: start at first light and stop by 11:00, move the afternoon indoors or underground, and put the walking back in after 18:00 when the city is at its best anyway. Evening activities — a [night bike ride](/japan/tokyo/tokyo-tower-bike-tour), a [neon photo walk](/japan/tokyo/shibuya-crossing-photography-tour) — are not a consolation prize in Tokyo summer, they are the correct plan."
                    },
                    {
                        title: "Typhoons: Real, But Usually a 24-Hour Problem",
                        icon: "AlertTriangle",
                        content: "JMA's 1991–2020 normals: **25.1 typhoons form per year, 11.7 approach Japan, 3.0 make landfall.** Formation peaks in **August** (5.7), but **landfall peaks in September** (1.0) — September storms are the likelier ones to actually hit.\n\nWatch the definitions before you panic. JMA counts an *approach* as passing within **300 km of any Japanese observatory nationwide**, which includes an Okinawa near-miss 1,500 km from Tokyo. *Landfall* excludes Okinawa entirely.\n\nTwo 2026 storms show the realistic range. **Typhoon Jangmi (3 June)** cancelled around 900 flights affecting some 90,000 passengers, halted shinkansen and metro services and triggered evacuation advisories — but most JR East lines were running again by 22:48 the same evening. **Typhoon No. 15 (11–12 August)** cancelled 64 flights and no shinkansen at all.\n\nThe honest framing: a typhoon usually costs you a **12 to 36 hour window**, not a trip. Build one flexible day into a September or October itinerary and you will almost certainly be fine."
                    },
                    {
                        title: "Autumn Colour: Late November into December",
                        icon: "Star",
                        image: IMG.yanaka,
                        content: "Tokyo's koyo runs **later than most visitors expect** — central Tokyo peaks **late November to early December**, weeks behind Kyoto and well behind the mountains.\n\nJMA's Tokyo specimen trees sit in **Kitanomaru Park**. Recent observations: ginkgo yellowing on 3 December 2024 and 22 November 2025; maple reddening 3 December 2024 and 23 November 2025. Those describe one tree each, which is not the same as a garden looking its best, but they anchor the timing.\n\n**Where to go:**\n\n| Spot | Typical peak | Why |\n|---|---|---|\n| Meiji Jingu Gaien ginkgo avenue | late Nov – early Dec | 146 trees over 300 m, grown from 1908 Shinjuku Gyoen seed |\n| Rikugien | late Nov – early Dec | Evening light-up, historically late Nov to early Dec |\n| Showa Kinen Park | ginkgo mid-Nov, maples to mid-Dec | Katarai avenue 98 trees, Canale 106 trees |\n| Mt Takao | mid-Nov – early Dec | Momiji festival, and an easy half-day from Shinjuku |\n| Koishikawa Korakuen, Shinjuku Gyoen | late Nov – early Dec | Central, and reachable between other plans |\n\nOne correction worth knowing: **the Jingu Gaien Ginkgo Festival has not run since 2019** — COVID, then the Gaien redevelopment. A light-up ran in late November 2025 instead. Don't plan around festival dates you find on older pages."
                    },
                    {
                        title: "The Weeks to Avoid — and One to Target",
                        icon: "Wallet",
                        content: "Three periods move domestic prices and fill trains. All dates below are from the Cabinet Office holiday register.\n\n**Golden Week.** 2026 was split — a lone Wednesday on 29 April, then a five-day run from 2 to 6 May (6 May was a substitute holiday because Constitution Day fell on a Sunday). **2027 is worse**: Shōwa Day falls Thursday 29 April, and anyone taking Friday 30 April off gets a **seven-day run to 5 May**. Expect that to be the peak congestion window of 2027.\n\n**Obon, 13–16 August.** Not a public holiday, but customary leave, and one of Japan's three great travel crushes. A Tokyo quirk worth knowing: **central Tokyo observes its own Bon on 15 July**, while the August travel chaos hits Tokyo as residents *leave* for ancestral hometowns. In 2027 Obon falls Friday to Monday with Mountain Day on Wednesday 11 August — a heavy 11–16 August period.\n\n**New Year, 1–3 January.** The one time attractions and shops close *despite* peak season. Meiji Shrine alone draws several million hatsumōde visitors across the three days.\n\n**And one to target: Silver Week, 19–23 September 2026.** Respect for the Aged Day on Monday 21st and the Autumnal Equinox on Wednesday 23rd sandwich Tuesday the 22nd, which becomes a citizens' holiday automatically. It is the **first true Silver Week since 2015** and the next is 2037. Domestic travel will be heavy — but if you want to see Japan on a genuine holiday, this is the rare one."
                    }
                ],
                faqs: [
                    { q: "What is the single best month to visit Tokyo?", a: "**November.** It has the lowest rainfall of the good-weather months (96.3 mm), comfortable 16.7°C days, 64% humidity, and autumn colour arriving late in the month — without spring's crowds or prices." },
                    { q: "When is cherry blossom season in Tokyo?", a: "The **normal is 24 March first bloom, 31 March full bloom**, but it swings widely — 14 March in 2023, 29 March in 2024, 19 March in 2026. Forecasts only become reliable in **early March**, so treat any date booked further ahead as a gamble." },
                    { q: "Is the rainy season a reason to avoid Tokyo?", a: "Not really. Tsuyu runs roughly **7 June to 19 July** with humid, grey, on-and-off rain rather than all-day downpours. Hotel rates soften, hydrangeas peak, and temples look their best wet. **September and October are the genuinely wetter months** — 224.9 mm and 234.8 mm against June's 167.8 mm." },
                    { q: "How bad is Tokyo in summer?", a: "August normals are **31.3°C days, 23.5°C nights, 74% humidity** — and the nights are the problem, because the city never cools. Walking itineraries suffer badly. If you must come in summer, front-load mornings, move afternoons indoors, and put the sightseeing back after 18:00." },
                    { q: "Will a typhoon ruin my trip?", a: "Unlikely. Japan sees about **3 landfalls a year**, peaking in September. A typhoon typically costs a **12–36 hour window** — 2026's Jangmi halted trains and cancelled ~900 flights but most lines ran again the same evening. Leave one flexible day in a September or October itinerary." },
                    { q: "When does Tokyo's autumn colour peak?", a: "**Late November into early December** for central Tokyo — noticeably later than Kyoto. JMA's Kitanomaru Park specimens turned on 22–23 November in 2025 and 3 December in 2024." },
                    { q: "Which dates should I avoid?", a: "**Golden Week** (late April to early May — 2027's runs 29 April to 5 May), **Obon 13–16 August**, and **New Year 1–3 January**, when things close despite the crowds. **Silver Week 19–23 September 2026** is busy too, but it is the first since 2015, so it may be worth being there for." }
                ],
                fastFacts: [
                    { icon: 'Star', label: 'Best Months', value: 'Late March–early April, late Oct–early Dec' },
                    { icon: 'AlertTriangle', label: 'Wettest Month', value: 'October (234.8 mm) — not June' },
                    { icon: 'Clock', label: '2026 Sakura', value: 'Bloom 19 Mar, peak 28 Mar' },
                    { icon: 'Wallet', label: 'Avoid', value: 'Golden Week, Obon, 1–3 Jan' }
                ]
            };

        case "tokyo-3-day-itinerary":
            return {
                title: "Tokyo in 3 Days: A Realistic Itinerary With Booking Deadlines (2026)",
                seoTitle: "Tokyo 3-Day Itinerary 2026 (What to Book First)",
                description: "A 3-day Tokyo plan built around what you must book ahead — Shibuya Sky releases only 14 days out, teamLab tickets drop on the 1st, and museums close Mondays.",
                heroImage: IMG.walking,
                sections: [
                    {
                        title: "Read This Before You Plan Anything",
                        icon: "AlertTriangle",
                        content: "Most Tokyo itineraries fail for one of two reasons: something was sold out, or something was shut on the day you turned up. Both are avoidable.\n\n**The booking deadlines that matter:**\n\n| Attraction | When tickets release | Why it bites |\n|---|---|---|\n| **Shibuya Sky** | **Only 14 days ahead**, 00:00 JST | You physically cannot book it months out. The 15:00+ sunset slots are the premium tier |\n| **teamLab Borderless** | **12:00 JST on the 1st of each month**, covering that month plus two | Peak and weekend slots go weeks ahead |\n| **teamLab Planets** | Timed entry, **no refunds once bought** | Entry time changeable up to 2 hours before, max 3 changes |\n| **Tokyo Skytree** | Long window, rarely a bottleneck | Book online anyway to dodge the ¥500 counter fee |\n\n**The closure days that ruin plans:**\n\n- **Mondays**: Tokyo National Museum, National Museum of Nature and Science, National Museum of Western Art, Ueno Zoo, Edo-Tokyo Museum. When Monday is a public holiday they open and close Tuesday instead.\n- **teamLab Borderless**: 1st and 3rd **Tuesday**.\n- **teamLab Planets**: irregular single weekdays — check your exact date.\n- **Toyosu Market**: every **Sunday**, most holidays, and selected Wednesdays.\n- **Tsukiji Outer Market**: same calendar, roughly.\n\n**Mori Art Museum is open Mondays** and is the standard fallback when the rest of the city's museums are shut.\n\nTwo 2026 items worth knowing: **Edo-Tokyo Museum reopened 31 March 2026** after four years of renovation, and **Miraikan closes 1 October 2026 to 22 April 2027** for refurbishment — which kills a common Odaiba plan for anyone travelling after September."
                    },
                    {
                        title: "Day 1 — Old Tokyo, East Side",
                        icon: "Map",
                        image: IMG.kartEast,
                        content: "Start where the city started.\n\n**Morning: Asakusa.** **Senso-ji** has stood here since **645**, making it Tokyo's oldest temple. Come before the coaches — by ten the Nakamise-dori approach is a shuffle rather than a walk. Allow ninety minutes including the outer streets, which stayed low-rise and are the most atmospheric part.\n\n**Late morning: Tokyo Skytree.** Twenty minutes from Asakusa on foot or one stop by train. At **634 metres** it is the tallest tower on earth.\n\nSkytree pricing changed fundamentally on **1 April 2026**. It scrapped the weekday/holiday split, the advance/same-day split and the 12–17 age band, and moved to **per-day variable pricing**. Adult Tembo Deck now runs **¥1,800–¥3,600** depending on the date, with the deck-plus-galleria combo at ¥3,000–¥4,800. **Buying at the counter adds a flat ¥500.** Any guide still showing you a ¥2,100 weekday advance fare is quoting a dead table.\n\n**Afternoon: Yanaka.** This is the part that separates a good Tokyo day from a checklist. Yanaka **escaped both the 1923 earthquake and the wartime firebombing** that flattened most of eastern Tokyo, so its wooden houses, temple walls and shopping street are genuinely old rather than rebuilt. Yanaka Ginza is a working local high street — butchers, pickle shops, croquette stands — not a tourist one.\n\n**Evening: Ueno or back to Asakusa.** Ameyoko's market alleys under the train tracks, or the riverside.\n\nIf you would rather cover more ground, the east side works well **[by kart](/japan/tokyo/tokyo-skytree-spiritual-tour)** or **[by e-bike through the backstreets](/japan/tokyo/yanaka-backstreets-bike-tour)** — the lanes here are too narrow for coaches, which is exactly why they are worth riding."
                    },
                    {
                        title: "Day 2 — Shrine, Scramble, Skyline",
                        icon: "Map",
                        image: IMG.neon,
                        content: "**Morning: Meiji Shrine.** The forest around it is roughly **100,000 trees, every one donated from across Japan and planted by hand in the 1920s** — designed to look, a century on, exactly as it does now. It is free, it opens at sunrise, and it is the calmest hour you will get in central Tokyo.\n\n**Late morning: Harajuku.** Takeshita Street is five minutes and a hundred years from the shrine gate. That contrast is the single most useful thing Tokyo teaches you about itself.\n\n**Lunch and afternoon: Omotesando and Shibuya.** Omotesando's zelkova avenue carries flagship stores by **Ando, SANAA and Herzog & de Meuron** — worth walking slowly and looking up. Then down into Shibuya for the [crossing](/japan/tokyo/shibuya-crossing-guide).\n\n**Sunset: Shibuya Sky — if you booked it.** ¥2,700 web for entry before 15:00, **¥3,400 from 15:00** (that ¥700 gap is the official sunset premium). Remember the **14-day release window**: if you are reading this more than two weeks before your trip, you cannot book it yet. Set a reminder for 00:00 JST on the day it opens.\n\nIf you missed it, **Tokyo Tower** is the underrated alternative — **¥1,500** for the Main Deck with **no online/walk-up price difference**, and it stays open latest of the three, with last entry at **22:30**.\n\n**Evening: the back alleys.** **Nonbei Yokocho** behind the station, or Shinjuku's Omoide Yokocho and Golden Gai. A **[neon photo walk](/japan/tokyo/shibuya-crossing-photography-tour)** is the efficient way to do this if you want images you would actually print."
                    },
                    {
                        title: "Day 3 — Pick One Thing and Do It Properly",
                        icon: "Star",
                        image: IMG.ebike,
                        content: "Three days is not enough to see Tokyo, so day three is better spent going deep than wide. Four options that each justify a full day.\n\n**Digital art.** **teamLab Planets** in Toyosu is barefoot, mirrored-floor, water-based, and runs to **end-2027** — despite persistent rumours it is closing, which are a confusion with *Borderless*, the one that genuinely relocated to Azabudai Hills in February 2024. Adults from **¥3,600** at both. Planets is a barefoot venue with mirrored floors, so skirts are a problem; free rental shorts are provided. **No refunds once you buy.**\n\n**Food.** A market morning at **Tsukiji Outer Market**, which kept trading fish, knives and tamagoyaki after the wholesale auction moved to Toyosu in 2018. Or go the other way entirely and eat somewhere no tour goes — **[Togoshi Ginza](/japan/tokyo/togoshi-ginza-shotengai-food-tour)** is Tokyo's longest shopping street at 1.3 km and around 400 shops, in residential Shinagawa, with no English menus and no other groups.\n\n**Central Tokyo by bike.** The Imperial Palace moat sits on the old Edo Castle site; **Nihonbashi** carries the marker every road distance in Japan is measured from. A **[three-hour e-bike loop](/japan/tokyo/imperial-palace-bike-tour)** covers this properly — Tokyo is flat and the side streets are near-empty.\n\n**Get out of the city.** [Mount Fuji, Hakone or Nikko](/japan/tokyo/mount-fuji-day-trip-from-tokyo) are all day-trippable, though each eats the whole day.\n\n**A note on trying to add Kyoto.** Don't, on a three-day trip. A Tokyo–Kyoto round trip is about ¥27,700 and two half-days of travel."
                    },
                    {
                        title: "Practical Notes That Save Money",
                        icon: "Wallet",
                        content: "**Do not buy a JR Pass for this trip.** The 7-day pass is ¥50,000 and excludes Tokyo Metro and Toei entirely — the two networks you will use most. See [getting around Tokyo](/japan/tokyo/getting-around-tokyo) for the arithmetic. Get a **Suica or Pasmo** instead; budget ¥1,000–¥1,400 a day.\n\n**Fares changed in March 2026.** JR East raised Tokyo fares for the first time since 1987 and abolished the discounted inside-Yamanote table. On several routes **Tokyo Metro is now cheaper than JR** — Shinjuku to Tokyo Station is ¥209 on the Marunouchi Line against ¥253 on JR.\n\n**Two taxes to expect.** Japan's **departure tax tripled to ¥3,000 on 1 July 2026**, bundled into your ticket. Tokyo's lodging tax is currently ¥100–¥200 per person per night depending on room rate, with stays under ¥10,000 exempt — that changes to 3% of the lodging fee from April 2027.\n\n**Cash still matters** at shrines, small restaurants and older shops, even though cards are widely taken now.\n\n**Sequence your days by closures, not by geography.** If one of your three days is a Monday, put the museum-free plan on it. If it is a Sunday, don't plan Toyosu."
                    }
                ],
                faqs: [
                    { q: "What should I book before I arrive?", a: "**teamLab** (tickets drop 12:00 JST on the 1st of each month for Borderless) and any restaurant you care about. **Shibuya Sky cannot be booked more than 14 days out** — it releases at 00:00 JST fourteen days before your entry date, so set a reminder rather than trying early." },
                    { q: "Is 3 days enough for Tokyo?", a: "It is enough to understand the city, not to see it. Three days covers old Tokyo, the Shibuya/Harajuku axis, and one thing done properly. Trying to add Kyoto costs about ¥27,700 and two half-days of travel — not worth it on a three-day trip." },
                    { q: "How much has Tokyo Skytree changed in 2026?", a: "Completely. On **1 April 2026** it abolished weekday/holiday and advance/same-day pricing and the 12–17 age band, moving to **per-day variable pricing** of ¥1,800–¥3,600 for the adult Tembo Deck. **Counter purchase adds a flat ¥500.** Most third-party guides still show the dead table." },
                    { q: "Shibuya Sky, Skytree or Tokyo Tower?", a: "**Shibuya Sky** for the crossing directly below and an open-air rooftop — but it needs the 14-day booking. **Skytree** is by far the highest, though it sits ~5 km east so you look back at the skyline rather than over it. **Tokyo Tower** is cheapest at ¥1,500, needs no booking, and has the latest entry at 22:30." },
                    { q: "Is teamLab Planets closing?", a: "**No.** It runs to end-2027. The closure story is a confusion with **teamLab Borderless**, which did relocate — Odaiba to Azabudai Hills, reopening February 2024." },
                    { q: "What if one of my days is a Monday?", a: "Most major museums shut — Tokyo National Museum, Nature and Science, Western Art, Ueno Zoo, Edo-Tokyo. **Mori Art Museum stays open Mondays.** Put your outdoor, neighbourhood or market day there instead." },
                    { q: "Do I need a JR Pass?", a: "No. It is ¥50,000 for seven days, excludes Tokyo Metro and Toei, and needs roughly two intercity round trips to break even. A **Suica or Pasmo** at ¥1,000–¥1,400 a day is the right answer for a Tokyo trip." }
                ],
                fastFacts: [
                    { icon: 'AlertTriangle', label: 'Book First', value: 'Shibuya Sky — only 14 days ahead' },
                    { icon: 'Clock', label: 'teamLab Tickets', value: '12:00 JST on the 1st monthly' },
                    { icon: 'Info', label: 'Museums Closed', value: 'Mondays (Mori stays open)' },
                    { icon: 'Wallet', label: 'Transport', value: 'IC card, ¥1,000–¥1,400/day' }
                ]
            };

        case "getting-around-tokyo":
            return {
                title: "Getting Around Tokyo: IC Cards, JR Pass and the 2026 Fare Changes",
                seoTitle: "Getting Around Tokyo 2026: Suica, Fares & Passes",
                description: "JR East raised Tokyo fares in March 2026 — the first real revision since 1987. What Suica, Pasmo and the JR Pass actually cost now, and why the pass is wrong for a Tokyo-only trip.",
                heroImage: IMG.ebike,
                sections: [
                    {
                        title: "Start Here: Two Things Changed in 2026",
                        icon: "AlertTriangle",
                        content: "If you are reading fare advice written before this year, most of it is out of date.\n\n**1. JR East raised fares on 14 March 2026** — its first real revision since 1987. Crucially, it **abolished the discounted Tokyo zones**. The old *densha tokutei kukan* (Tokyo special zone) and *Yamanote-sen nai* (inside-Yamanote) cheap fare tables are gone, merged into the standard nationwide trunk-line table. Inside-Yamanote ordinary fares rose **16.4%**.\n\n**2. The JR Pass rises again on 1 October 2026** — six weeks from now, at the time of writing.\n\nThe practical upshot of the first change is that **Tokyo Metro is now cheaper than JR on several routes where JR used to win.** Shinjuku to Tokyo Station on JR went from ¥208 to ¥253; the Marunouchi Line does the same trip for ¥209. That reverses the standard advice."
                    },
                    {
                        title: "Get an IC Card. That Is the Whole Answer.",
                        icon: "CheckCircle2",
                        content: "For a Tokyo trip, a **Suica or Pasmo** covers essentially everything: JR, Tokyo Metro, Toei, private railways, buses, convenience stores, vending machines and most coin lockers. Tap in, tap out, stop thinking about it.\n\n**The 2023 card shortage is over.** Sales of unregistered Suica and Pasmo were suspended in June 2023 during a global chip shortage; registered cards returned in September 2024 and **unregistered sales resumed on 1 March 2025**. In 2026 anyone can walk up to a Tokyo ticket machine and buy one.\n\n**Regular Suica:** ¥500 deposit, refundable. The refund is deposit plus balance minus a ¥220 handling fee — but the fee is capped at your balance, so a card you have spent down to zero still returns the full ¥500. Balance cap ¥20,000. Refunds only at JR East ticket offices; a Suica cannot be refunded at a Pasmo operator or vice versa.\n\n**Welcome Suica** (physical, tourists): **no deposit**, so the whole purchase price is spendable. Sold in fixed amounts from ¥1,000 to ¥10,000. **Valid 28 days and the balance is NOT refundable** — spend it down before you fly. Available at Narita T1 and T2·3, Haneda T3, and JR East Travel Service Centers at Shinjuku, Shibuya, Ikebukuro, Ueno and Yokohama.\n\n**Welcome Suica Mobile** is the better option **if you have an iPhone**. Launched March 2025, valid **180 days** rather than 28, accepts foreign credit cards through Apple Pay, and can be issued and loaded before you land.\n\n**Android travellers have no equivalent** — Google Wallet Suica needs a Japan-market handset. Several travel blogs present Welcome Suica Mobile as the Android workaround. It is not. Buy a physical card."
                    },
                    {
                        title: "Pasmo Passport Is Gone. It Is TOURIST PASMO Now.",
                        icon: "Info",
                        content: "**PASMO PASSPORT was discontinued in 2024 and replaced by TOURIST PASMO, which launched in May 2026.** Any page still telling you to buy a Pasmo Passport is out of date.\n\nNo deposit and no service charge, sold in ¥1,000 to ¥10,000 denominations, **valid 28 days**, and the **remaining value is not refundable**. If the card is lost it cannot be reissued. Sold at Haneda (Keikyu) and Narita (Keisei) airport station machines and information counters.\n\nFunctionally Suica and Pasmo are interchangeable across Tokyo. Pick whichever you find first."
                    },
                    {
                        title: "A ¥50 Trap: Don't Tap a Credit Card",
                        icon: "Wallet",
                        content: "Tokyo Metro's own fare table has two columns: **IC card**, and **credit-card tap or paper ticket**.\n\nIC fares are calculated to the yen. Paper and contactless-credit fares are **rounded up to the nearest ten**. Tapping your Visa instead of a Suica quietly costs you a couple of yen every single journey, and the paper column is what you pay.\n\nIt is small per trip and irritating across a week. Load an IC card.\n\nOne more foreign-card quirk: for topping up a Suica in Apple Wallet, **Mastercard and Amex are the reliable choice** — foreign-issued Visa is widely reported to fail at network level. Sources differ on how absolute that is, so carry an alternative."
                    },
                    {
                        title: "What Journeys Actually Cost Now",
                        icon: "Clock",
                        content: "Post-14 March 2026 fares. Metro times and fares below are from Tokyo Metro's own published table.\n\n| Journey | Line | Time | IC fare |\n|---|---|---|---|\n| Shibuya → Asakusa | Ginza Line, direct | 33 min | ¥252 |\n| Shibuya → Shinjuku | Fukutoshin express | 6 min | ¥178 |\n| Shinjuku → Tokyo Station | Marunouchi, direct | 18 min | ¥209 |\n| Shinjuku → Tokyo Station | JR Chuo Rapid | ~14 min | ¥253 |\n| Ueno → Asakusa | Ginza Line | 5 min | ¥178 |\n| Ginza → Asakusa | Ginza Line | 17 min | ¥209 |\n| Shinjuku → Harajuku | JR Yamanote, 2 stops | ~5 min | ¥155 |\n\n**The JR Yamanote minimum is now ¥155 IC** (was ¥146). Tokyo Metro's minimum is ¥178 and did **not** change in 2026 — Metro's general fares have been unchanged since March 2023.\n\nA realistic day of five or six journeys lands around **¥1,000 to ¥1,400**. That number is what decides whether any pass is worth buying, and usually it isn't."
                    },
                    {
                        title: "The JR Pass Is Wrong for a Tokyo Trip",
                        icon: "AlertTriangle",
                        content: "This is the single most common expensive mistake visitors make, so here is the arithmetic.\n\nThe **7-day ordinary pass costs ¥50,000** (it was ¥29,650 before the October 2023 increase — a 69% jump). A Tokyo–Kyoto round trip on a Hikari, which the pass covers, costs about **¥27,700**.\n\nSo **one Tokyo–Kyoto round trip recovers barely 55% of the pass.** You need roughly *two* long-distance round trips inside seven days to break even. A Tokyo-only visitor makes none.\n\nWorse, the pass covers **only JR lines**. Tokyo Metro and Toei — the two networks you will actually ride most — are excluded entirely. In Tokyo it buys you the Yamanote loop, the Chuo/Sobu lines, the Narita Express and the Haneda monorail. That's it.\n\n**It rises again on 1 October 2026:** 7-day ordinary ¥50,000 → **¥53,000**, 14-day ¥80,000 → ¥84,000, 21-day ¥100,000 → ¥105,000. Sources differ on whether the official website holds pre-October pricing for a window while agency prices rise — check japanrailpass.net if you are close to the date.\n\n**Buy the pass only if** your itinerary has multiple intercity legs. For Tokyo plus one day trip, an IC card wins by a wide margin."
                    },
                    {
                        title: "When a Pass Does Make Sense",
                        icon: "CheckCircle2",
                        image: IMG.walking,
                        content: "There are narrow cases where a pass beats pay-as-you-go, and they are all about **density, not distance**.\n\nThe **Tokyo Subway Ticket** (24, 48 or 72 hours) covers all Tokyo Metro and Toei lines and is sold to short-stay foreign visitors at the airports and major stations. It pays for itself if you are making six or more subway journeys a day — realistic on a packed sightseeing day, unrealistic on a relaxed one.\n\nThe honest rule of thumb: if your day looks like **three or four journeys**, an IC card is cheaper and simpler. If it looks like **seven or eight**, price the subway ticket. Most visitors overestimate how much they will move.\n\nA different way to cut fares entirely is to stop using trains for the short hops. Central Tokyo is flat and the side streets carry almost no traffic — a [three-hour e-bike loop](/japan/tokyo/imperial-palace-bike-tour) covers ground that would otherwise be four or five separate paid journeys, and you see the bits between the stations."
                    },
                    {
                        title: "Practical Things Nobody Tells You",
                        icon: "Info",
                        content: "**Carry some cash.** Japan is far more card-friendly than its reputation, but shrine offerings, small restaurants, older shops and some markets remain cash-only.\n\n**Tap out, always.** Japanese fares are distance-based, so failing to tap out leaves the system unable to calculate your fare and will block the card until a staff member fixes it.\n\n**Know which company you are on.** Tokyo's network is run by JR East, Tokyo Metro, Toei and several private railways. Transferring between operators means **paying two base fares**, which is why an apparently short trip sometimes costs double. Where an all-Metro routing exists, it is usually cheaper than a mixed one — Shibuya to Asakusa on the Ginza Line is a single ¥252 fare the whole way.\n\n**Luggage.** Large suitcases are awkward on rush-hour trains and many older stations have stairs only. Coin lockers at major stations take IC cards, and **takkyubin** courier services will move a suitcase hotel-to-hotel overnight for a modest fee — the standard move for anyone changing cities mid-trip."
                    }
                ],
                faqs: [
                    { q: "Suica or Pasmo — which should I get?", a: "Either. They are functionally interchangeable across Tokyo's trains, subways, buses and shops. Suica is JR East, Pasmo is the private railways and subways, and both work on all of it. Buy whichever machine you reach first." },
                    { q: "Is the JR Pass worth it for Tokyo?", a: "**No.** The 7-day pass is ¥50,000 and one Tokyo–Kyoto round trip only recovers about ¥27,700 of that. It also excludes Tokyo Metro and Toei entirely. You need roughly two intercity round trips in seven days to break even." },
                    { q: "Did Tokyo train fares go up in 2026?", a: "**JR East did, on 14 March 2026** — its first real revision since 1987, and it abolished the discounted Tokyo zones. Inside-Yamanote ordinary fares rose 16.4%; the Yamanote minimum went ¥146 → ¥155 IC. **Tokyo Metro did not** — its fares are unchanged since March 2023." },
                    { q: "Can I still buy a Suica card as a tourist?", a: "Yes. The 2023 shortage is over — unregistered sales resumed **1 March 2025**. You can buy a regular Suica at any Tokyo ticket machine, or a no-deposit Welcome Suica at the airports." },
                    { q: "Can I use Suica on my phone?", a: "On **iPhone**, yes — Welcome Suica Mobile launched in March 2025, is valid 180 days rather than 28, and takes foreign cards via Apple Pay. On **Android there is no tourist equivalent**; Google Wallet Suica needs a Japan-market handset. Android users should buy a physical card." },
                    { q: "Should I just tap my credit card at the gate?", a: "No. Metro's fare table charges **contactless credit taps at the rounded-up paper fare**, not the to-the-yen IC fare. It is a few yen per trip that adds up, and IC cards work in more places." },
                    { q: "What happened to the Pasmo Passport?", a: "It was **discontinued in 2024** and replaced by **TOURIST PASMO**, which launched in May 2026 — no deposit, ¥1,000–¥10,000 denominations, valid 28 days, and the balance is non-refundable." },
                    { q: "How much should I budget for transport per day?", a: "A typical sightseeing day of five or six journeys costs **¥1,000–¥1,400**. If you expect seven or more, price a 24/48/72-hour Tokyo Subway Ticket instead." }
                ],
                fastFacts: [
                    { icon: 'CheckCircle2', label: 'Best Option', value: 'Suica or Pasmo IC card' },
                    { icon: 'AlertTriangle', label: 'JR Fares Rose', value: '14 March 2026, first since 1987' },
                    { icon: 'Wallet', label: 'Daily Budget', value: '¥1,000–¥1,400' },
                    { icon: 'Info', label: 'JR Pass', value: 'Not worth it for Tokyo-only' }
                ]
            };

        case "shibuya-crossing-guide":
            return {
                title: "Shibuya Crossing: The Complete Guide (Viewpoints, Hachiko & the Drinking Ban)",
                seoTitle: "Shibuya Crossing Guide 2026: Views & Rules",
                description: "Five crosswalks, one diagonal, a 140-second signal cycle. Where to photograph it free, what Shibuya Sky really costs, the year-round street-drinking ban, and Hachiko's real story.",
                heroImage: IMG.neon,
                sections: [
                    {
                        title: "What You Are Actually Looking At",
                        icon: "Star",
                        content: "Everyone calls it **Shibuya Scramble Crossing**. Its official designation with the road authority is duller and more useful to know: **Shibuya-ekimae Kosaten**, \"Shibuya Station Front Intersection.\" Scramble phasing was introduced in **1973**.\n\nIt is a **five-way junction where ten traffic lanes meet, with five marked crosswalks — exactly one of which is diagonal**, running from the Hachiko plaza corner to the QFRONT building. That single diagonal is the detail most write-ups get wrong; this is not an X-type scramble with two diagonals, and pages claiming six or seven crosswalks are counting the neighbouring station-side crossings.\n\nThe diagonal itself is roughly **36 metres**. Treat any other width figure you read with suspicion — no engineering source publishes the intersection's dimensions, and the numbers in travel blogs are invented.\n\n**The signal cycle is where almost every guide is wrong.** You will read that \"the walk signal lasts two minutes.\" It does not. Direct stopwatch observation gives a **full cycle of about 140 seconds — 2 minutes 20 — of which the all-walk scramble phase is around 37 seconds**. The two-minute figure is the whole cycle, garbled. The Metropolitan Police do not publish official timings, and the cycle shifts by time of day, so treat 35–40 seconds as the working number.\n\nCrowd figures deserve the same scepticism. \"3,000 people per green\" and daily totals from 260,000 to 500,000 circulate widely and **none of them traces to an actual count**. It is unquestionably one of the busiest pedestrian crossings on earth. Beyond that, be wary of precision."
                    },
                    {
                        title: "Where to Photograph It — Free and Paid",
                        icon: "Map",
                        image: IMG.neon,
                        content: "**Free, at street level.** Stand on the Hachiko-side kerb and shoot along the diagonal. The crossing empties completely between phases, which is its own shot — an eight-lane junction with nobody on it, in the middle of Tokyo.\n\n**Free, elevated.** The connecting walkways and upper floors around the station give you height without a ticket. Staff move people along at the busiest spots, so don't set up a tripod and settle in.\n\n**Shibuya Sky** is the paid view, and the one worth planning around. Current pricing:\n\n| Ticket | Entry 10:00–14:59 | Entry 15:00–21:20 |\n|---|---|---|\n| Adult (12+), web | **¥2,700** | **¥3,400** |\n| Adult, at the counter | ¥3,000 | ¥3,700 |\n| Child (6–11), counter only | ¥1,200 | ¥1,200 |\n| 5 and under | Free | Free |\n\nFour things that catch people out:\n\n1. **Tickets only go on sale two weeks ahead**, at 00:00 JST on the day 14 days before your entry date. You cannot book Shibuya Sky months in advance. Set an alarm.\n2. Pricing splits by **entry time, not by advance versus walk-up**. The 15:00-onward slot is the official sunset premium at **¥700 more**.\n3. Buying at the window costs **¥300 more**, and if adults sell out online the counter is sold out too — same inventory.\n4. The **open-air rooftop closes** in strong wind, rain, snow, approaching thunderstorms and extreme heat. The indoor gallery stays open. If the rooftop is shut at your entry time you can cancel free on the day, before entering.\n\n**Rooftop rules are strict** because nothing may blow off a 229-metre roof: no bags of any kind, no tripods or selfie sticks, no hats, no earphones, no food or drink. Cameras and phones only, cameras on a neck strap. Lockers are provided on 46F."
                    },
                    {
                        title: "The Street-Drinking Ban Is Real — and Carries No Fine",
                        icon: "AlertTriangle",
                        content: "Since **1 October 2024**, drinking alcohol in public around Shibuya Station is prohibited **18:00 to 05:00, every night, year-round**. Before that amendment the restriction applied only at Halloween and New Year.\n\nThe zone covers the Shibuya Station area including **Center-gai, Dogenzaka, Udagawacho, Maruyamacho and Miyamasuzaka**, and \"public place\" includes **parks and plazas**, not just streets. The ward publishes the boundary as a map rather than a list — check it if you are close to the edge.\n\n**There is no fine.** This is the single most misreported fact about the ordinance: it contains no penalty clause at all. Enforcement is ward officials and contracted multilingual security guards issuing warnings and asking people to stop or bin the drink. Compliance is voluntary, and the ward has said it may seek legislation with real penalties if that stops working.\n\nSo any page telling you street drinking in Shibuya carries a ¥X fine is wrong. But being repeatedly asked to stop by security is a poor way to spend an evening — and roughly two-thirds of those cautioned are foreign visitors.\n\n**Shinjuku is not the same.** Its ordinance covers **only 31 October and 1 November**, in parts of Shinjuku 3-chome and Kabukicho, and is likewise penalty-free. Do not assume the two wards work alike."
                    },
                    {
                        title: "Halloween: Do Not Plan Around It",
                        icon: "AlertTriangle",
                        content: "Shibuya's mayor, **Ken Hasebe**, first told visitors publicly not to come for Halloween in **2023**, with the line \"Shibuya is not a Halloween event venue.\" The reasons given were post-COVID crowd volumes and **crush risk**.\n\nWhat happens each Halloween now: the **Hachiko statue is boxed in behind hoarding** for roughly 30 October to 1 November; around 125 contracted guards plus ward staff deploy; **convenience stores and retailers are asked to suspend alcohol sales** 18:00–05:00; police impose traffic restrictions; e-scooter stations are switched off; and Miyashita Park closes at 15:00.\n\nIt has worked. Peak street crowds went from roughly **40,000 in 2019 to 18,000 in 2024 to about 4,500 in 2025** — the lowest since counting began. Worth noting the mayor himself credited the **rain** as the dominant factor in 2025, not policy.\n\n**New Year is the same story.** The Shibuya Countdown has been **cancelled every year since 2020** — the 2025→26 New Year was the sixth consecutive cancellation. The Hachiko statue is enclosed from the morning of 31 December to about 01:00 on 1 January. If seeing the statue matters, come before 30 December or after New Year's morning."
                    },
                    {
                        title: "Hachiko: The Story, Correctly Told",
                        icon: "History",
                        content: "The statue outside the station is the reason half the crowd is there, and the popular version of the story is roughly right but wrong in the details.\n\n**Hachiko was born in November 1923** near Odate, Akita, and came to Tokyo as a puppy to **Professor Hidesaburo Ueno**, who held the agricultural engineering chair at Tokyo Imperial University and effectively founded the discipline in Japan.\n\n**Ueno collapsed and died suddenly at the university on 21 May 1925**, about sixteen months later. Hachiko kept returning to Shibuya Station. He was cared for afterwards by a gardener who had worked at the Ueno house, and became nationally famous after an **Asahi Shimbun article in October 1932**.\n\nThe famous \"nine years and nine months\" is arithmetic from the two dates rather than a sourced figure — **Shibuya's own library says seven years, and the 1932 Asahi headline says seven** too. Both versions have a claim.\n\n**He died on 8 March 1935**, found near Inari-bashi over the Shibuya River, roughly where the Shibuya Stream car-park entrance is now. Sources give his age as 11 or 13 depending on whether they count in the Japanese style.\n\n**The cause of death was corrected in 2011.** University of Tokyo researchers re-examined his organs, preserved in formalin for 76 years, using MRI and histology. Filariasis had been recorded in 1935 as the sole cause; the 2011 work found an extensive **carcinosarcoma originating in the lung with metastasis to the heart**, alongside the parasites. The tumour was, in their words, also important as a cause of death.\n\n**The statue you see is not the original.** Andō Teru's 1934 statue — unveiled 21 April 1934, with Hachiko himself present at a ceremony of about 300 people — was surrendered under wartime metal requisition in 1944 and melted down in August 1945. The current one, by **Andō Takeshi, the original sculptor's son**, was unveiled on **15 August 1948**.\n\nOne correction worth making, because it circulates widely: **the statue did not move in 2023.** Its last relocation was **May 1989**, when it shifted about eight metres west and was turned from north-facing to east-facing. What did change is the **JR Hachiko ticket gate, relocated in January 2025**, so it no longer opens directly onto the square. The whole square is due to be rebuilt by **FY2034**, so a future move is plausible — but nothing has been announced.\n\nHachiko's taxidermied body is on display at the **National Museum of Nature and Science** in Ueno, Japan Gallery 2F. Admission ¥630, free under 18, 9:00–17:00, closed Mondays."
                    },
                    {
                        title: "Doing It Properly",
                        icon: "CheckCircle2",
                        image: IMG.kart,
                        content: "The crossing takes about ninety seconds to experience and most people are done with it in ten minutes. What makes Shibuya worth a proper visit is everything one street back.\n\n**Nonbei Yokocho** — \"Drunkard's Alley\" — is a minute from the scramble: a few dozen tiny bars along two narrow lanes, most seating six or seven people, lit by lanterns and vending machines. It feels like a different decade and almost nobody who photographs the crossing walks into it.\n\n**Center-gai** supplies the neon. **Omotesando**, ten minutes north, is a run of flagship stores by Ando, SANAA and Herzog & de Meuron — an open-air museum of contemporary Japanese architecture that most visitors walk past without looking up.\n\nThree ways to see it beyond standing on the kerb:\n\n- **[A go-kart run through the crossing](/japan/tokyo/shibuya-crossing-crossing-photography-tour)** — the scramble at road level with pedestrians flooding past on all sides. Requires a Geneva-Convention IDP, arranged before you fly.\n- **[An evening photo walk](/japan/tokyo/shibuya-crossing-photography-tour)** with a local photographer, covering the crossing and then the back alleys where the good frames actually are.\n- **[A bike tour of the backstreets](/japan/tokyo/shibuya-backstreets-bike-tour)**, which covers the parts of Shibuya and Harajuku that walking tours never reach.\n\n**On timing:** the crossing is busiest on weekday evening commute and Friday and Saturday nights. Early morning gives you near-empty frames. Be aware that the confident hour-by-hour advice you find elsewhere is photographer consensus rather than measurement — no dataset publishes a pedestrian curve for this junction."
                    }
                ],
                faqs: [
                    { q: "How long is the walk signal at Shibuya Crossing?", a: "About **37 seconds**, within a full cycle of roughly **140 seconds**. The widely quoted \"two-minute walk signal\" is the whole cycle misread. Timings vary by hour and the police do not publish them officially." },
                    { q: "How many crosswalks are there?", a: "**Five, and exactly one is diagonal** — Hachiko plaza to QFRONT, roughly 36 metres. Claims of six or seven count the neighbouring station-side crossings as part of the same junction." },
                    { q: "What's the best place to see Shibuya Crossing from above?", a: "**Shibuya Sky** — ¥2,700 web before 15:00, ¥3,400 after. Its open-air rooftop is the draw, but it closes in bad weather. **Tickets only release two weeks ahead at 00:00 JST**, so it cannot be booked months in advance. There are free elevated views from the station walkways if you'd rather not pay." },
                    { q: "Is drinking on the street illegal in Shibuya?", a: "Yes — **18:00 to 05:00, year-round, since 1 October 2024**, covering Center-gai, Dogenzaka, Udagawacho, Maruyamacho and Miyamasuzaka, including parks and plazas. But **there is no fine**: the ordinance has no penalty clause and enforcement is warnings by security staff. Pages quoting a fine are wrong." },
                    { q: "Should I visit Shibuya at Halloween?", a: "The ward has publicly asked visitors not to. The Hachiko statue gets boxed in, alcohol sales are suspended 18:00–05:00, and heavy security deploys. Crowds fell from ~40,000 in 2019 to about 4,500 in 2025. If Halloween is your reason for coming, pick a different night." },
                    { q: "Is the Hachiko statue the original?", a: "No. The 1934 original was surrendered for wartime metal in 1944 and melted down in August 1945. The current statue, by the **original sculptor's son**, was unveiled **15 August 1948**. Its last move was 1989 — despite what several pages claim, it did not move in 2023." },
                    { q: "Can I see the real Hachiko?", a: "Yes. His taxidermied body is displayed at the **National Museum of Nature and Science** in Ueno, Japan Gallery 2F — ¥630, free under 18, 9:00–17:00, closed Mondays. His preserved organs are at the University of Tokyo's Museum of Agriculture." },
                    { q: "What else is worth doing around the crossing?", a: "**Nonbei Yokocho**, a lantern-lit alley of tiny bars a minute from the scramble, is the one most visitors miss entirely. **Center-gai** for neon and **Omotesando** for flagship architecture are both within a short walk." }
                ],
                fastFacts: [
                    { icon: 'Clock', label: 'Signal Cycle', value: '~140 sec, ~37 sec walk phase' },
                    { icon: 'Map', label: 'Crosswalks', value: '5, one diagonal (~36 m)' },
                    { icon: 'Ticket', label: 'Shibuya Sky', value: '¥2,700 / ¥3,400 after 15:00' },
                    { icon: 'AlertTriangle', label: 'Street Drinking', value: 'Banned 18:00–05:00, no fine' }
                ]
            };

        case "tokyo-go-kart-guide":
            return {
                title: "Tokyo Street Go-Karting: The Licence Rules That Get People Turned Away",
                seoTitle: "Tokyo Go-Kart Guide 2026: IDP Rules & Booking",
                description: "You need a 1949 Geneva Convention IDP to drive a street kart in Tokyo — and six countries need a JAF translation instead. What to arrange before you fly, and why the costumes changed.",
                heroImage: IMG.kart,
                sections: [
                    {
                        title: "Sort the Licence Before You Book Anything",
                        icon: "AlertTriangle",
                        content: "This is the single reason travellers get turned away at the shop door, having paid, with no refund. Read this section before you book.\n\nThese are **road-registered vehicles on public streets**, not an amusement ride. That is what makes them interesting, and it is why the paperwork is real.\n\n**Japan accepts exactly two things:**\n\n1. A **Japanese driving licence**, or\n2. An **International Driving Permit issued under the 1949 Geneva Convention on Road Traffic**\n\n**IDPs issued under the 1968 Vienna Convention are not valid in Japan.** This catches out a lot of European drivers, because plenty of countries issue the Vienna version by default. Check which convention your permit cites before you travel.\n\n**Six countries are the exception.** Licences from **Switzerland, Germany, France, Belgium, Monaco and Taiwan** are accepted with an **official Japanese translation** instead of an IDP. JAF — the Japan Automobile Federation — issues these at branches nationwide and through an online application, and the translation is valid for one year from your date of entry.\n\nIf you are from one of those six, you do **not** need an IDP. If you are from anywhere else, you do, and it must be the 1949 Geneva version.\n\n**What you physically carry to the shop:**\n\n- The **physical IDP** — not a scan, not a photo on your phone\n- The **home licence it was issued against** (an IDP alone is not valid)\n- Your **passport**\n\n**Arrange it in your own country before you fly.** No shop in Tokyo can issue you an IDP, and the JAF translation route takes time. Minimum age is **18**."
                    },
                    {
                        title: "Why Nobody Says \"Mario Kart\" Any More",
                        icon: "History",
                        content: "If you remember these tours as \"MariCar\" with drivers dressed as Mario and Luigi, that ended in court.\n\n**Nintendo sued MariCar** — the company's name is, in katakana, exactly the Japanese fan nickname for the Mario Kart series. The Tokyo District Court awarded ¥10 million in September 2018. On appeal the **Intellectual Property High Court raised it fivefold to ¥50 million in 2019**, and ordered the company to stop the unfair competition. The company appealed again; **Japan's Supreme Court dismissed it in December 2020**, making Nintendo's win final.\n\nThe result: the **MariCar name is gone** and so are the Nintendo character costumes. The operator now trades as **Street Kart**.\n\nCostumes are still part of it — every operator provides them — they are simply not Nintendo's characters. If a listing is still advertising Mario costumes in 2026, treat that as a sign the operator is not paying attention to the rules generally."
                    },
                    {
                        title: "Which Route to Pick",
                        icon: "Map",
                        image: IMG.kartEast,
                        content: "Tokyo's kart routes fall into two families, and they are genuinely different experiences.\n\n**West side — Shibuya, Harajuku, Tokyo Tower.** This is the famous one, and the reason most people book: crossing the **Shibuya scramble** at road level with pedestrians flooding past on every side. **Omotesando** gives the guide clean, wide space for action photos, and **Tokyo Tower** floodlit at 333 metres is the other headline shot. Busier traffic, more spectators, the pictures everyone recognises.\n\n**East side — Asakusa, Skytree, Akihabara.** Fewer operators run it and the roads are quieter. You get **Asakusa's low wooden streets** around the city's oldest temple, the Sumida riverside with **Tokyo Skytree at 634 metres** filling the windscreen, then **Akihabara's Electric Town**, where the shopfronts throw more light onto the road than the streetlamps do. Three completely different versions of Tokyo inside about seventy minutes.\n\n**On length.** A 45-minute or 1-hour run gets you one landmark cluster and the signature shot. Two hours buys something specific: **time to actually stop and shoot** rather than drive past, and the ability to **run the crossing again** if the light cycle empties it at the wrong moment. If you only care about one photograph, take the short one.\n\nOur Tokyo kart options: **[Shibuya Crossing with photo stops](/japan/tokyo/shibuya-crossing-crossing-photography-tour)** (1 hour), **[Asakusa to Akihabara](/japan/tokyo/tokyo-skytree-spiritual-tour)** (70 min), **[the premium two-hour route](/japan/tokyo/tokyo-tower-premium-tour)** covering both Tokyo Tower and Shibuya, an **[evening Tokyo Tower run](/japan/tokyo/shibuya-crossing-evening-tour)**, and a **[45-minute Shibuya sprint](/japan/tokyo/shibuya-crossing-premium-tour)**."
                    },
                    {
                        title: "What It Is Actually Like",
                        icon: "Info",
                        content: "**You drive your own.** The karts are **single-seat** — there is no passenger option, so everyone in your group needs valid documents. Couples cannot share.\n\n**Check-in takes about twenty minutes** before you move: licence verification first, then costume, helmet, and a briefing on the controls and the hand signals your guide uses in traffic. Most operators run a short practice loop on quiet streets before joining real roads.\n\n**They are slower than they feel.** These are low-powered automatics. What makes them intense is sitting roughly twenty centimetres off the tarmac in live Tokyo traffic, not speed.\n\n**Your guide rides with the group**, sets the pace, and photographs you at the stops. Photos are handed over at the garage afterwards and are included.\n\n**Weather:** tours run in **light rain with ponchos provided** and are only cancelled in heavy weather, with a refund or reschedule. From late autumn through winter, two hours in an open vehicle is genuinely cold — dress warmer than you think.\n\n**What to wear:** closed shoes and trousers. The karts are open and low.\n\n**A word on courtesy.** These tours are a live irritation to some Tokyo residents and drivers, and the scene has attracted real regulatory attention. Follow your guide's signals, don't hold up traffic for photographs, and keep the noise down in residential stretches. It is the difference between the tours continuing to exist and not."
                    },
                    {
                        title: "Before You Book: A Checklist",
                        icon: "CheckCircle2",
                        content: "**Weeks before you travel**\n\n- Confirm your country issues **1949 Geneva Convention** IDPs, not 1968 Vienna\n- If you hold a **Swiss, German, French, Belgian, Monégasque or Taiwanese** licence, apply to JAF for the **official Japanese translation** instead\n- Apply for the IDP at home — it cannot be obtained in Japan\n\n**Packing**\n\n- Physical IDP **and** your home licence **and** your passport, all three\n- Closed shoes, trousers\n- A warm layer if you are travelling October to March\n\n**Choosing the tour**\n\n- **One photo is the goal** → shortest Shibuya route\n- **Both Tokyo Tower and Shibuya** → the two-hour premium route\n- **Something less crowded** → the east-side Asakusa/Skytree/Akihabara run\n- **Best light** → an evening departure, when the tower is lit and Shibuya is at its most dramatic\n\n**On the day**\n\n- Arrive **20 minutes early** for the licence check\n- Expect to be refused with no refund if the paperwork is wrong — this is not negotiable at the counter\n\nIf the licence rules rule you out, the equivalent thrill without paperwork is the **[Wangan and Daikoku PA night drive](/japan/tokyo/daikoku-parking-area-evening-tour)**, where you ride as a passenger, or a **[night bike tour](/japan/tokyo/tokyo-tower-bike-tour)** through the same streets at a slower pace."
                    }
                ],
                faqs: [
                    { q: "Do I need an International Driving Permit to go-kart in Tokyo?", a: "**Yes, unless you hold a Japanese licence.** It must be issued under the **1949 Geneva Convention** — 1968 Vienna Convention permits are **not valid in Japan**. Bring the physical IDP, your home licence and your passport. Scans and phone photos are refused." },
                    { q: "Which countries don't need an IDP?", a: "**Switzerland, Germany, France, Belgium, Monaco and Taiwan.** Those six licences are accepted with an **official Japanese translation from JAF** instead, valid one year from your date of entry. Every other country needs the Geneva-Convention IDP." },
                    { q: "Can I get an IDP after I arrive in Japan?", a: "**No.** It must be issued in your own country before you travel. The JAF translation route for the six exception countries also takes time, so start early." },
                    { q: "Can two people share one kart?", a: "No. They are **single-seat**, so everyone taking part drives and everyone needs valid documents. There is no passenger option." },
                    { q: "Why aren't they Mario costumes any more?", a: "Nintendo sued MariCar. The **IP High Court raised damages to ¥50 million in 2019** and Japan's **Supreme Court finalised the win in December 2020**. The MariCar name and Nintendo character costumes are gone; the operator now trades as **Street Kart**. Costumes are still included — just not Nintendo's." },
                    { q: "Are the karts fast?", a: "Not particularly — they are low-powered automatics. The intensity comes from sitting about twenty centimetres off the road **in live Tokyo traffic**, which is a completely different sensation to speed." },
                    { q: "What happens if it rains?", a: "Tours **run in light rain and ponchos are provided**. Only heavy weather causes cancellation, with a refund or reschedule offered." },
                    { q: "Which route should I choose?", a: "**Shibuya/Harajuku/Tokyo Tower** for the famous shots and the scramble at road level. **Asakusa/Skytree/Akihabara** for quieter roads and three distinct versions of the city. Take a **two-hour** route only if you want time to stop and shoot properly rather than drive past." }
                ],
                fastFacts: [
                    { icon: 'AlertTriangle', label: 'Licence', value: '1949 Geneva IDP — not 1968 Vienna' },
                    { icon: 'Info', label: 'Exceptions', value: 'CH, DE, FR, BE, MC, TW — JAF translation' },
                    { icon: 'Ticket', label: 'Bring', value: 'IDP + home licence + passport' },
                    { icon: 'Clock', label: 'Minimum Age', value: '18' }
                ]
            };

        case "mount-fuji-day-trip-from-tokyo":
            return {
                title: "Mount Fuji Day Trip from Tokyo: Where to Go and When You'll Actually See It",
                seoTitle: "Mt Fuji Day Trip from Tokyo (2026 Guide)",
                description: "Fuji is visible 84% of mornings in December and 23% in July. Real visibility data, 2026 climbing rules and the ¥4,000 fee, plus what a Kawaguchiko day trip costs from Shinjuku.",
                heroImage: IMG.walking,
                sections: [
                    {
                        title: "The Cruel Irony: Climbing Season Is When You Can't See It",
                        icon: "AlertTriangle",
                        content: "Fuji City has recorded whether Mount Fuji is visible at **08:00 every single day for over three decades**. Averaged across 1991–2023, the results demolish most travel advice:\n\n| Month | Visible |\n|---|---|\n| **December** | **84%** |\n| October – February | all above 65% |\n| May – August | all below 50% |\n| **July** | **23%** |\n\n**The climbing season, July to early September, is precisely when the mountain is least visible.** If your goal is to *see* Fuji rather than stand on it, come between **October and February** — and December is the single best month.\n\nAcross all of 2025 the whole mountain was visible at the 08:00 observation on **136 days, or 37.3% of the year**. That is the honest baseline: on any random day you have roughly a one-in-three chance.\n\n**Go early.** Fuji City's own multi-decade analysis found the **08:00 observation has the highest full-visibility rate of any hour** — cloud builds through the day. A first-train or first-bus departure from Shinjuku is not just about beating crowds; it materially changes whether you see anything.\n\nOne caveat: these are Fuji City figures, taken from the Shizuoka side. The pattern holds everywhere, but they are not Kawaguchiko-specific. Be sceptical of English blogs claiming \"near 100% visibility in December\" — they contradict the official record."
                    },
                    {
                        title: "Where to Actually Go",
                        icon: "Map",
                        content: "Almost every Fuji day trip means **Lake Kawaguchiko**, which is the hub for the Fuji Five Lakes area and the arrival point for every Shinjuku bus.\n\n**Getting there from Shinjuku:**\n\n| Mode | Time | Cost one-way |\n|---|---|---|\n| **Highway bus** from Busta Shinjuku | ~1h 45m | **¥2,200** (¥2,000 online) |\n| **Fuji Excursion** limited express, direct | ~1h 55m | **¥4,200** |\n| JR Chuo → Otsuki → Fujikyu Railway | 2h 05m – 2h 35m | ~¥2,500–4,000 |\n\n**Take the bus.** It is roughly half the price, the same journey time, runs about **twice an hour**, and drops you at the same station. Book online — it sells out on weekends and through autumn.\n\nThe **Fuji Excursion** earns its premium in two situations: you have luggage, or you want a guaranteed reserved seat with no transfer. All seats are reserved and there are no unreserved carriages, so booking is mandatory. Only **four round trips a day**, with outbound in the morning and returns in the evening.\n\n**A JR Pass does not help here.** It covers neither the highway buses, nor the Fujikyu Railway section, nor Odakyu — so pass holders still pay for the final leg.\n\n**Once you arrive**, the Fujikyu sightseeing bus loops cover the lakeside: a two-day Red + Green pass is **¥1,300**, or ¥1,500 including the Blue line."
                    },
                    {
                        title: "The Viewpoints, Ranked by Effort",
                        icon: "Star",
                        image: IMG.neon,
                        content: "**Chureito Pagoda** (Arakurayama Sengen Park) is the shot — five-storey pagoda, cherry trees, Fuji behind. Note it is **not** at Kawaguchiko: the nearest station is **Shimoyoshida** on the Fujikyu line, about two hours total from Shinjuku. From the station it is a **ten-minute walk then roughly 400 steps**. Budget half an hour station-to-viewpoint. **Free, open 24 hours.**\n\n**Lake Kawaguchiko itself** gives you the classic mountain-over-water view with almost no effort, plus the northern shore path and the ropeway.\n\n**Oshino Hakkai** is a village of eight spring-fed ponds fed by Fuji snowmelt — genuinely clear water, and Fuji behind on a good day. Direct bus from Shinjuku takes about **2h 20m**, or 25–30 minutes by bus from Kawaguchiko Station. The village is **free**; the deep-blue Nakaike pond sits on private land and costs about **¥300**.\n\n**Hakone** is the different option — Fuji seen distantly across Lake Ashi or from the ropeway, wrapped in an onsen day. Odakyu Romancecar from Shinjuku to Hakone-Yumoto is **~80 minutes, ¥2,420** on a digital ticket. The **2-day Hakone Freepass is ¥7,100**, covering the round trip plus unlimited local transport — but **not** the Romancecar surcharge.\n\n**Gotemba** suits shoppers: the Premium Outlets have a well-known Fuji backdrop, roughly 1h 35m–2h by bus from Shinjuku for about ¥1,800–2,200."
                    },
                    {
                        title: "The Lawson Photo Spot: Not Blocked Any More",
                        icon: "Info",
                        content: "In **May 2024**, Fujikawaguchiko town put up a **2.5-metre by 20-metre black mesh screen** to kill the viral \"Mt Fuji above a Lawson convenience store\" photograph. The reasons were real: jaywalking, litter, and tourists trespassing on a neighbouring dental clinic's property.\n\nVisitors **poked holes in it** within weeks. The screen came down in **August 2024**, officially ahead of Typhoon Ampil, and was never re-erected.\n\n**In August 2025 a different barrier went up** — about **1.4 metres, brown tarp**, positioned to keep people out of the road rather than to hide the mountain.\n\n**Current status: the view is intact.** You shoot over the low barrier. The store is the **Lawson Kawaguchiko-ekimae**, walkable from Kawaguchiko Station. The town has said it will act again if behaviour deteriorates — so stay on the pavement and off the clinic's land.\n\nWatch out for headlines claiming the barrier is \"back up\": they refer to the low 2025 crowd barrier, not the view-blocking screen."
                    },
                    {
                        title: "If You Want to Climb: 2026 Rules Are Much Stricter",
                        icon: "AlertTriangle",
                        content: "Climbing Fuji is **not** a day trip from Tokyo, and the rules changed substantially.\n\n**2026 season dates:**\n\n| Trail | Side | Opens | Closes |\n|---|---|---|---|\n| Yoshida | Yamanashi | **1 July** | 10 September |\n| Subashiri | Shizuoka | **1 July** (moved forward) | 10 September |\n| Gotemba | Shizuoka | 10 July | 10 September |\n| Fujinomiya | Shizuoka | 10 July | 10 September |\n\n**The fee is now ¥4,000 per climb on all four trails.** The history matters if you are reading older pages: Yoshida charged ¥2,000 in 2024, Yamanashi doubled it to ¥4,000 for 2025, and Shizuoka introduced its own ¥4,000 fee across its three trails in **2025**. There is no cheap route any more.\n\n**What is now mandatory:**\n\n- **A pre-climb e-learning module and comprehension test.** Shizuoka runs it through the free *FUJI NAVI* app; Yamanashi runs its own. Do it before you travel — doing it at the trailhead is slow.\n- **Advance online reservation** producing a **QR-code permit**, scanned at the 5th Station gate for a wristband.\n- **Gates close 14:00 to 03:00** on both sides. The only exception is climbers with a confirmed mountain hut booking. This exists specifically to stop *dangan tozan* — overnight \"bullet climbing\" without sleep.\n- **New for 2026 on Yoshida: a physical equipment check.** Rangers verify **proper hiking footwear, two-piece rain gear and cold-weather clothing**. Without all three you are turned back even holding a paid reservation.\n\n**The 4,000-climbers-per-day cap** still applies on Yoshida only; the Shizuoka trails have none. Worth knowing that the cap **was not actually reached on any day in 2024 or 2025**, so it is rarely the binding constraint."
                    },
                    {
                        title: "Making the Day Work",
                        icon: "CheckCircle2",
                        image: IMG.ebike,
                        content: "**Leave early — the data says so.** Morning visibility beats afternoon by a clear margin, and the last buses back fill up. A 07:00 departure from Busta Shinjuku puts you at Kawaguchiko before 09:00 with the best odds of the day.\n\n**Have a plan for cloud.** On roughly two days in three you will not get the full mountain, and there is nothing to be done about it. Oshino Hakkai's ponds, the Kawaguchiko ropeway, an onsen and the lakeside are all worth the trip on their own — build the day so a hidden summit doesn't ruin it.\n\n**Check the season.** Cherry blossom at Chureito is late March to mid-April; autumn colour around the lakes runs late October into November. Winter gives you the best visibility and a snow-capped summit, which is the postcard image most people actually have in mind.\n\n**If you would rather not manage it yourself**, a private car removes the transfers and the last-bus anxiety — our **[Nagano day trip](/japan/tokyo/jigokudani-monkey-park-full-day-tour)** works the same way for the snow monkeys, and for the Fuji area a **[private JDM day around Fuji Speedway](/japan/tokyo/fuji-motorsports-museum-private-tour)** covers the mountain's southern side with photo stops built in.\n\n**One thing not to do:** do not try to combine a Fuji day trip with anything else. It is a full day, and rushing it in cloud season is how people end up with three hours of bus and no mountain."
                    }
                ],
                faqs: [
                    { q: "What month gives the best chance of seeing Mount Fuji?", a: "**December, at 84% visibility** in Fuji City's 33-year record. October through February all exceed 65%. **July is worst at 23%** — which means the climbing season is exactly when the mountain is least visible." },
                    { q: "How do I get to Kawaguchiko from Tokyo?", a: "**Highway bus from Busta Shinjuku: ~1h 45m, ¥2,200** (¥2,000 online), about twice an hour. That is the sensible default. The direct **Fuji Excursion** train takes ~1h 55m for **¥4,200** — worth it only for luggage or a guaranteed seat. A JR Pass does **not** cover the buses or the Fujikyu line." },
                    { q: "Is the Mt Fuji Lawson photo spot still blocked?", a: "**No.** The 2.5 m black screen went up in May 2024 and came down in **August 2024**. A low **1.4 m brown barrier** was added in August 2025 to keep people out of the road — **the view is intact** and you shoot over it." },
                    { q: "How much does it cost to climb Mount Fuji in 2026?", a: "**¥4,000 per climb on all four trails.** Yoshida was ¥2,000 in 2024 before Yamanashi doubled it for 2025, and Shizuoka introduced its own ¥4,000 fee across Fujinomiya, Gotemba and Subashiri that same year." },
                    { q: "When is the 2026 climbing season?", a: "**Yoshida and Subashiri: 1 July to 10 September. Gotemba and Fujinomiya: 10 July to 10 September.** Subashiri moved forward to 1 July for 2026. All dates are weather-dependent." },
                    { q: "What are the new climbing rules?", a: "A **mandatory e-learning module and test**, an **advance QR-code permit**, **gates closed 14:00–03:00** unless you hold a mountain hut booking, and — new for 2026 on Yoshida — a **physical equipment check** for hiking footwear, two-piece rain gear and cold-weather clothing. Fail it and you are turned back with a paid reservation." },
                    { q: "Can I climb Fuji as a day trip from Tokyo?", a: "No. The gate closure from 14:00 exists specifically to prevent overnight climbs without rest. Plan an overnight in a mountain hut, or make it a two-day trip." },
                    { q: "What if the mountain is hidden by cloud?", a: "Expect it — on about two days in three you will not get the full summit. **Oshino Hakkai's spring ponds, the Kawaguchiko ropeway, an onsen and the lakeside** all stand on their own. Build the day so a hidden summit is a disappointment, not a wasted trip." }
                ],
                fastFacts: [
                    { icon: 'Star', label: 'Best Visibility', value: 'December (84%) — worst July (23%)' },
                    { icon: 'Wallet', label: 'Bus from Shinjuku', value: '¥2,200, ~1h 45m' },
                    { icon: 'Ticket', label: 'Climbing Fee 2026', value: '¥4,000 all four trails' },
                    { icon: 'Clock', label: 'Best Time of Day', value: 'Morning — cloud builds later' }
                ]
            };

        case "tokyo-food-guide":
            return {
                title: "Tokyo Food Guide: What This City Eats That Nowhere Else Does",
                seoTitle: "Tokyo Food Guide 2026: Edomae, Monja & Markets",
                description: "Edomae sushi, monjayaki, Edo soba and the Toyosu tuna auction lottery. Tokyo has 160 Michelin-starred restaurants — and the best food is often ¥150 at a konbini.",
                heroImage: IMG.food,
                sections: [
                    {
                        title: "Edomae Sushi: Every Technique Was Once a Workaround",
                        icon: "Star",
                        content: "**Edomae** means \"in front of Edo\" — fish from the waters of Tokyo Bay, directly in front of the city. It is Tokyo's own style, and it exists in opposition to Kansai's pressed sushi.\n\nNigiri as we know it took shape in the **Bunsei era, roughly 1804–1830**, and is traditionally credited to **Hanaya Yohei**, who set up a stall near **Ryogoku Bridge around 1824**. His innovation was impatience: rather than wait days for fermented or pressed sushi, he laid the topping straight onto a hand-moulded ball of vinegared rice.\n\n**It was fast food for labourers.** Edo burned down constantly and was a permanent building site full of workers, and sushi carts fed them on the promise of *fast, cheap, delicious*. Edo-period nigiri was **noticeably bigger than modern nigiri**, sized to fill a hungry man for a few sen.\n\nHere is the part worth knowing, because it changes how you taste it. **There was no ice.** Every signature Edomae technique began as a preservation problem:\n\n| Technique | Applied to | Why |\n|---|---|---|\n| ***Zuke*** — soy marinade | tuna | shelf life, and it deepens the flavour |\n| ***Sujime*** — salt then vinegar cure | kohada (gizzard shad) | the signature Edomae fish |\n| ***Niru*** — simmering in sweet sauce | anago (conger eel) | cooked and glazed, served warm |\n\nEven the vinegar in the rice was doing two jobs — sharpening flavour and slowing spoilage. Edo-period shops used ***akazu***, a red vinegar made from sake lees, and some top Tokyo counters still do.\n\nSo when a chef hands you cured kohada rather than raw fish, that is not fussiness. **It is the oldest thing on the menu.**"
                    },
                    {
                        title: "Monjayaki: Tokyo's Own, and Nothing Like Okonomiyaki",
                        icon: "Info",
                        content: "If you have eaten okonomiyaki in Osaka and assume monja is the Tokyo version, you are in for a surprise. **The difference is water.**\n\nMonja batter is loaded with dashi, so it **never sets into a cake** — it stays gooey, almost liquid, on the griddle. You do not plate it. You scrape small amounts off the hot iron with a tiny spatula called a ***hagashi*** and eat straight from the teppan as the edges caramelise. Okonomiyaki is a thick pancake you cut with a spatula; monja is a communal, slightly chaotic thing you pick at for an hour.\n\n**The name is wonderful.** It comes from *mojiyaki* — \"grilled letters.\" Postwar, with paper scarce, children at penny-candy shops were given a small iron plate and flour-and-water batter to **write letters with**, then eat their handwriting.\n\n**Why Tsukishima.** The dish took root in *shitamachi* candy shops in the **1950s**, and Tsukishima's gradually turned into monja restaurants. Today **Monja Street** (Tsukishima Nishinaka-dori) has **over 80 monja specialists** on one strip. Tsukishima Station, Yurakucho or Toei Oedo lines; most places run roughly 11:00 to 20:00.\n\nIt is not refined and it is not photogenic. It is one of the few genuinely Tokyo things left on a plate."
                    },
                    {
                        title: "Why Tokyo Eats Soba and Osaka Eats Udon",
                        icon: "History",
                        content: "*Soba in the East, udon in the West* is a real divide with two real causes.\n\n**The agronomy.** Buckwheat is a famine crop — it grows in poor soil and cooler climates, which suits Kanto. Wheat, and therefore udon, prefers the warmer west.\n\n**The disease.** This is the better story. Soba consumption took off in Edo around **1600** partly as a defence against **beriberi**, a thiamine deficiency. Beriberi came from a diet dependent on **polished white rice**, which is stripped of thiamine — and the cruel twist is that **Edo's population was wealthier than the countryside and so ate more white rice**, making city dwellers *more* vulnerable, not less. It was nicknamed ***Edo wazurai***, \"the Edo affliction.\" Buckwheat is thiamine-rich. The city's noodle of choice was, partly, medicine.\n\n**And the water.** Kanto's water is harder; Kansai's is softer, and soft water pulls umami out of kombu better. So Kanto dashi leans on **katsuobushi** and Kansai on **kombu** — which is exactly why Tokyo soba broth is dark, salty and bonito-forward while Kansai's is pale.\n\nUnder the Tokugawa, every neighbourhood had a soba shop or two, most serving sake as well. They were the local café.\n\n**Old shops still trading:**\n\n| Shop | Founded |\n|---|---|\n| Sarashina Horii, Azabu-Juban | **1789** |\n| Toranomon Osakaya Sunaba | 1872 |\n| Kanda Yabu Soba | 1880 |\n| Kanda Matsuya | 1884 |"
                    },
                    {
                        title: "Tsukiji Did Not Close",
                        icon: "AlertTriangle",
                        image: IMG.food,
                        content: "This is the most common misunderstanding about eating in Tokyo, so it is worth being blunt: **only the inner wholesale market moved to Toyosu in October 2018.** The **Tsukiji Outer Market never moved.** It is exactly where it always was, and it is thriving.\n\nAround **460 shops, restaurants and stalls** line the streets — knives, dried goods, tamagoyaki, sea urchin, tuna, produce. The official branding is *Japan's Food Town*, and it still functions as a place professionals shop, not only a tourist strip.\n\n**Hours:** roughly **06:00–09:00 for trade buyers**, **09:00–14:00 for the general public**, winding down after that. Most shops open around 05:00 and are finished by early afternoon — **come in the morning or don't come**.\n\n**Closed** every **Sunday**, a handful of **Wednesdays** each year following the Tokyo Central Wholesale Market calendar, and around **30 December to 4 January**. Individual shops set their own days too. Check the official calendar for your date rather than trusting a blog's list.\n\nA historical footnote that explains the location: the market moved to Tsukiji in **1935**, after the **1923 Great Kanto Earthquake** destroyed the original at Nihonbashi."
                    },
                    {
                        title: "The Toyosu Tuna Auction: Two Ways In",
                        icon: "Ticket",
                        content: "The auction itself moved to **Toyosu**, and visitors can still watch. There are two tiers and most people don't know about the second.\n\n**Upper observation walkway — free, no booking.** Turn up from **05:00**. You watch through **sealed glass** one floor above the auction floor, with the auctioneers' calls piped through speakers. No lottery, no paperwork.\n\n**Lower deck — free, lottery only.** Down at auction level with **no glass between you and the floor**. Around **100–120 people** get in per morning, rotated through in **10-minute slots between 05:45 and 06:15**, and winners must arrive by **05:30**.\n\n**How the lottery works:** apply at **toyosu.jcdlotterysite.jp**. Applications open roughly **a month ahead — in the first week of the month, for the following month** — and the window runs about seven days. You nominate up to three preferred dates. **Selection is purely random**, not first-come. Winners are notified the week after the window closes, and **assigned dates cannot be changed**. Bring the printed confirmation and your passport.\n\n**Timing:** the auction runs about **05:30–06:30, Monday to Saturday** on market business days. Toyosu is closed **Sundays**, public holidays and certain Wednesdays. Access is Yurikamome to **Shijo-mae**, directly connected.\n\n**If Toyosu felt sterile to you, that changed.** **Toyosu Senkyaku Banrai** opened on **1 February 2024** — an Edo-styled open-air food and shopping street of around **70 stores**, built with timber from Tokyo's Tama region and roof tiles from Awaji Island, plus an onsen complex using hot spring water trucked in from Hakone and Yugawara. It gives Toyosu the browsable street life the old inner market lost."
                    },
                    {
                        title: "160 Michelin Stars — and a ¥150 Rice Ball",
                        icon: "Star",
                        content: "**Tokyo has 160 starred restaurants in the 2026 Michelin Guide** — 12 with three stars, 26 with two, 122 with one. Paris, in the same year's guide, has **127**, with 9 three-stars. Tokyo has held the world's highest star count for **over fifteen years**.\n\nTwo corrections, because both errors are everywhere. You will see \"194 restaurants, 251 stars\" quoted — that counts a wider region and mixes guide editions. And you will see \"more stars than Paris and New York combined,\" which simply **fails arithmetic**. The accurate claim is strong enough: **more starred restaurants than any other city, and more three-star restaurants than Paris.**\n\nNow the other end of the scale, which matters more to most visitors.\n\n**Convenience store food in Japan is genuinely good, and there is a structural reason.** Each store takes **three to four deliveries of fresh prepared food every 24 hours**, with same-day or next-morning expiry — what is on the shelf is hours old. And the big three compete head-on: **7-Eleven** (21,248 stores), **FamilyMart** (16,047) and **Lawson** (13,779) hold about 90% of a 56,000-store market and launch premium lines annually.\n\nWhat to actually buy: **7-Eleven** for onigiri and the *tamago sando* egg sandwich. **Lawson** for desserts — the Premium Roll Cake has sold over **400 million units** since 2009 — and *Karaage-kun* fried chicken. **FamilyMart** for **Famichiki**.\n\nA ¥150 konbini onigiri is not a compromise. It is one of the things Japan is quietly best at."
                    },
                    {
                        title: "Standing Bars and the Alleys",
                        icon: "Map",
                        image: IMG.neon,
                        content: "***Tachinomi*** means standing drinking: no seats, no reservations, no minimum. You stand at the counter, order small, and leave. Roughly **¥300 house wine, ¥400 beer, ¥350 sake** — some of the cheapest decent alcohol in the city, busiest right after work.\n\nThe format has a specific origin. Wartime **alcohol rationing from 1943** forced bars onto a ticket system and **banned patrons from sitting on chairs**, deliberately, to cut how long they stayed. The rationing ended; the standing stayed.\n\n**The four alleys worth your evening:**\n\n| Alley | Where | Size | What it is |\n|---|---|---|---|\n| **Golden Gai** | Shinjuku | **~280 bars**, six alleys | Bars seating 5–12; many themed, some members-only |\n| **Omoide Yokocho** | Shinjuku west | roughly 60–80 shops | Yakitori and offal, smoky, food-led |\n| **Nonbei Yokocho** | beside Shibuya Stn | ~40 bars | Two lanes of wooden two-storey shacks |\n| **Ameyoko** | Ueno–Okachimachi | 400+ shops | Daytime market street with standing bars |\n\nAll four grew from the **postwar black markets**. Omoide Yokocho was nicknamed \"Piss Alley\" because the alley had no toilets; a **1999 fire** destroyed much of it and it was rebuilt. Nonbei Yokocho's shacks were **built informally on JR-owned land**. Ameyoko's name means \"Candy Store Alley,\" after the sweet stalls that appeared during the sugar shortage of the 1940s.\n\n**Golden Gai has posted visitor rules** and they are enforced: **no street smoking, no street drinking, and photography requires permission**. Most bars open around 20:00 and many charge a cover.\n\n**[Nonbei Yokocho](/japan/tokyo/shibuya-crossing-guide)** is the one to walk into if you only do one — it is sixty seconds from Shibuya Crossing and almost nobody who photographs the scramble turns down it."
                    },
                    {
                        title: "Three Things That Matter, and a Lot That Doesn't",
                        icon: "CheckCircle2",
                        content: "There is a great deal of anxious etiquette advice about Japan online. Most of it is not worth carrying around. Three things genuinely matter.\n\n**1. Do not tip.** It is not expected anywhere and it confuses staff — it can even read as *\"I was not satisfied.\"* Say **arigatou gozaimasu**. That is the tip.\n\n**2. Carry cash, specifically for the good places.** Japan's cashless ratio reached **58% in 2025**, which means **more than four yen in every ten is still cash**. And the businesses most likely to refuse cards are exactly the ones you came for: independent family-run izakaya, ramen shops with ticket machines, market stalls. A card covers perhaps 85% of tourist spending — but the 15% it misses is disproportionately the memorable food.\n\n**3. At a counter sushi place, be on time.** Courses are synchronised across every seat, so arriving late disrupts the whole room. Beyond that: **eat nigiri with your fingers**, **dip fish-side down** rather than rice-first, eat it immediately, and skip strong cologne.\n\n**And genuinely don't worry about:** slurping — it is **expected** with ramen, soba and udon, and it cools and aerates the noodles. Chopstick minutiae. Whether you bow deeply enough. Nobody is grading you.\n\nThe best way to eat in Tokyo is still to get away from the places that have English menus. A **[food walk through Togoshi Ginza](/japan/tokyo/togoshi-ginza-shotengai-food-tour)** — Tokyo's longest shopping street at 1.3 km and around 400 shops, in residential Shinagawa — is the version of this city where nobody is catering to you, which is rather the point."
                    }
                ],
                faqs: [
                    { q: "Did Tsukiji Market close?", a: "**No.** Only the **inner wholesale market** moved to Toyosu in October 2018. The **Tsukiji Outer Market** never moved — around **460 shops** still trade there. Go **09:00–14:00** for the public window; it is closed Sundays, some Wednesdays and around 30 Dec–4 Jan." },
                    { q: "Can I still see the tuna auction?", a: "Yes, two ways. The **upper observation walkway is free with no booking** — turn up from 05:00 and watch through glass. The **lower deck, at floor level with no glass, is lottery-only**: about 100–120 people a morning, applied for roughly a month ahead at toyosu.jcdlotterysite.jp, selected at random." },
                    { q: "What food is Tokyo specifically known for?", a: "**Edomae sushi** (the Tokyo Bay style, cured and marinated rather than raw), **monjayaki** (a runny griddle dish unique to Tokyo, 80+ shops on Tsukishima's Monja Street), and **soba** — Tokyo is a soba city where Osaka is an udon city." },
                    { q: "What's the difference between monjayaki and okonomiyaki?", a: "**Water.** Monja batter is full of dashi so it **never sets** — it stays gooey and you scrape it off the griddle with a small spatula and eat straight from the iron. Okonomiyaki is a thick pancake you cut and plate. Monja is Tokyo; okonomiyaki is Osaka and Hiroshima." },
                    { q: "How many Michelin stars does Tokyo have?", a: "**160 starred restaurants in the 2026 guide** — 12 three-star, 26 two-star, 122 one-star — against Paris's 127. Tokyo has led the world for over fifteen years. Ignore the \"194 restaurants\" and \"more than Paris and New York combined\" figures; both are wrong." },
                    { q: "Do I need cash in Tokyo?", a: "**Yes.** Japan's cashless ratio was **58% in 2025**, so over 40% of payments are still cash — and card refusal is most likely at small independent izakaya, ramen ticket machines and market stalls. A card covers most spending, but the gap is disproportionately the best food." },
                    { q: "Should I tip in Japan?", a: "**No.** Tipping is not expected anywhere and can be read as dissatisfaction. A spoken *arigatou gozaimasu* is the correct thanks." },
                    { q: "Is it rude to slurp noodles?", a: "The opposite — **slurping ramen, soba and udon is expected**, signals enjoyment, and cools and aerates the noodles as you eat." },
                    { q: "Is convenience store food actually good?", a: "Genuinely, yes. Stores take **three to four fresh-food deliveries every 24 hours** with same-day expiry, and the big three compete hard on quality. Try **7-Eleven** onigiri and egg sandwiches, **Lawson** desserts, **FamilyMart** Famichiki." }
                ],
                fastFacts: [
                    { icon: 'Star', label: 'Michelin Stars', value: '160 restaurants — most of any city' },
                    { icon: 'Map', label: 'Tsukiji Outer', value: 'Never moved — ~460 shops' },
                    { icon: 'Ticket', label: 'Tuna Auction', value: 'Free upper deck, lottery for lower' },
                    { icon: 'Wallet', label: 'Cash', value: '42% of payments — carry some' }
                ]
            };

        default:
            return null;
    }
}
