// Thailand density batch reviews (2026-09), keyed by DB slug. Generated by th/gen_reviews_map.py.
import type { TourReviewData } from './tourReviews';
export const THAILAND_REVIEWS: Record<string, TourReviewData> = {
};
