// Thailand tour FAQs (2026-09 density batch), keyed by DB slug. Generated by th/gen_faqs.py + th/faq_map.py.
export const THAILAND_FAQS: Record<string, { question: string; answer: string }[]> = {
};
