// Generated from uae_itineraries_content.json — do not hand-edit.
// Every tour URL here was checked against the live tour list before writing,
// so a reader clicking through from a day never lands on a 404.
import type { ItineraryData } from './japanItineraries';

export const UAE_ITINERARIES: Record<string, ItineraryData> = {
  "3-days": {
    days: 3,
    title: "3 Days in the UAE",
    metaTitle: "3 Days in the UAE: A Realistic Dubai Itinerary",
    metaDescription: "A workable three-day UAE itinerary: Old Dubai and Downtown on day one, the Marina and the desert on day two, Abu Dhabi on day three.",
    routeSummary: "Old Dubai and Downtown → the Marina, the Palm and the desert → Abu Dhabi, sleeping in Dubai all three nights",
    intro: "Three days works well here, because the UAE is compact and almost everything is within ninety minutes. The mistake people make is not distance between cities but distance within Dubai: it runs seventy kilometres along the coast, and an itinerary that crosses it three times a day loses two hours to traffic each time. Give each day one end. Nights all in Dubai — changing hotels for two nights in Abu Dhabi is not worth the packing.",
    bestFor: "Stopovers, long weekends, and first visits where Dubai is the point.",
    quickAnswer: "With three days, stay in Dubai and give each day one end of the city. Day 1: Al Fahidi, the abra across the creek, the souks, then the Burj Khalifa timed for sunset. Day 2: the Marina and the Palm from the water in the morning, then a desert safari from mid-afternoon. Day 3: a day trip to Abu Dhabi for the Sheikh Zayed Grand Mosque and Qasr Al Watan. Three days is enough for Dubai plus one Abu Dhabi day — not for the east coast.",
    days_detail: [
      {
        day: 1,
        base: "Dubai",
        heading: "Old Dubai, the creek and Downtown",
        narrative: "Start in Al Fahidi while the lanes are still cool — coral-and-gypsum houses under wind towers that genuinely work, which is why the quarter is several degrees cooler than the street outside. Then the abra across Dubai Creek, a wooden commuter boat that costs a dirham, and into the souks: gold first, spice after. Lunch in Deira, where the food is better and a third of the Downtown price.\n\nLate afternoon, cross to Downtown. Book the Burj Khalifa for about ninety minutes before sunset so you go up in daylight and come down into a lit city, then the Dubai Fountain at the base — free from the promenade, better from a boat on the lake.",
        tours: ["https://www.asiabylocals.com/uae/dubai/old-dubai-walking-tour-with-souks-street-food-and-abra-ride", "https://www.asiabylocals.com/uae/dubai/burj-khalifa-124-125-and-dubai-aquarium-combo-ticket", "https://www.asiabylocals.com/uae/dubai/dubai-fountain-abra-lake-ride-at-the-burj-khalifa"],
        travel: null,
        tip: "",
      },
      {
        day: 2,
        base: "Dubai",
        heading: "The Marina, the Palm and the desert",
        narrative: "Morning on the water. The Palm Jumeirah is a road system from the ground and only becomes the shape it was drawn as from the sea, and the light before eleven is far better than the afternoon. A speedboat is quicker and cheaper; a yacht has shade and somewhere to sit.\n\nMidday at JBR — beach, lunch, out of the sun.\n\nMid-afternoon the desert safari collects you: dune bashing across the red dunes, sunset, then a camp with dinner and shows. Back around nine. That shape — water in the morning, shade at noon, sand in the evening — is the right way to spend a Dubai day in any month.",
        tours: ["https://www.asiabylocals.com/uae/dubai/dubai-speedboat-tour-marina-palm-atlantis-and-burj-al-arab", "https://www.asiabylocals.com/uae/dubai/dubai-red-dune-evening-safari-with-camel-ride-and-bbq-camp", "https://www.asiabylocals.com/uae/dubai/dubai-marina-yacht-tour-with-breakfast-or-barbecue"],
        travel: null,
        tip: "",
      },
      {
        day: 3,
        base: "Dubai",
        heading: "Abu Dhabi: the mosque and the palace",
        narrative: "Ninety minutes down the coast, and three hours of the day go on the road — so three sites, not five. The Sheikh Zayed Grand Mosque takes the largest share and deserves it: forty thousand capacity, the largest hand-knotted carpet in the world, and a courtyard whose marble inlay most people walk across without looking down. Free to enter; an abaya is provided at the door.\n\nThen Qasr Al Watan, a working presidential palace rather than a former one, and the Corniche with the Etihad Towers deck at 300 metres.\n\nIf your third day is a Friday, the mosque moves to the afternoon — it does not admit visitors on Friday mornings.",
        tours: ["https://www.asiabylocals.com/uae/dubai/abu-dhabi-full-day-tour-from-dubai-with-grand-mosque-and-corniche", "https://www.asiabylocals.com/uae/dubai/louvre-abu-dhabi-and-grand-mosque-day-trip-from-dubai"],
        travel: null,
        tip: "",
      },
    ],
    logistics: [
      { heading: "Getting around", content: "Dubai runs about seventy kilometres along the coast and the two areas you most want — Downtown with the Burj Khalifa, and the Marina with the Palm — are half an hour apart on a good day. Plan each day around one end of the city rather than crossing repeatedly. The metro's Red Line follows Sheikh Zayed Road and connects the airport, Downtown, the Marina and Expo City; it is faster than a car at rush hour and needs a Nol card, sold at every station. Taxis are metered, plentiful and cheap by European standards, and Careem is the local ride app. For anything outside the city — the desert, Abu Dhabi, the east coast — book a vehicle with a driver rather than metering a taxi." },
      { heading: "Abu Dhabi from Dubai", content: "Ninety minutes each way by road. That is three hours of a day gone, which leaves about seven for the city — enough for three major sites, not five. If Abu Dhabi is genuinely the reason for the trip, stay there rather than day-tripping: the mosque at sunrise and the palace lit at night are the versions worth having, and no day trip reaches either." },
      { heading: "Two closures that ruin plans", content: "Sheikh Zayed Grand Mosque does not admit visitors on Friday mornings. Louvre Abu Dhabi is closed all day Monday. Between them these catch out an extraordinary number of visitors, because a day trip has no second chance. Qasr Al Watan adds a third, less predictable risk — it shuts at short notice for state functions, and that is not published in advance. Give us your dates and we check all three with the operator before you pay." },
      { heading: "What to wear", content: "In malls, souks and public areas, shoulders and knees covered is the norm and swimwear stays at the beach or pool. At the Grand Mosque the code is enforced on everyone including men: no shorts, nothing tight or sheer, and hair covered for women — an abaya is provided free at the door. Shoes come off inside prayer halls and the marble outside gets painfully hot by midday, so carry socks." },
      { heading: "Heat, and how it shapes a trip", content: "November to March is the season. Between June and September the temperature reaches the mid-forties with humidity off the Gulf, and anything outdoors between ten in the morning and five in the evening becomes an endurance test. The city is built for it — three of the four Yas Island parks, the aquarium, the Green Planet and every mall are fully air-conditioned — but a summer plan has to be front-loaded before nine and restarted at dusk." },
      { heading: "Alcohol, Ramadan and the working week", content: "Alcohol is served in licensed hotels, bars and restaurants and is not sold in ordinary supermarkets. Drinking in public is an offence. During Ramadan, eating, drinking and smoking in public during daylight is restricted, though hotels serve guests throughout the day and visitors are not expected to fast; iftar at sunset is the most sociable hour of the year and worth planning for rather than around. The working week is Monday to Friday with Saturday and Sunday the weekend, so attractions are busiest at weekends exactly as they are elsewhere." },
    ],
    faqs: [
      { question: "Is Dubai or Abu Dhabi the better base?", answer: "Dubai, for a first visit. It has more to do, better transport and a wider choice of hotels, and Abu Dhabi is a comfortable day trip from it. Base yourself in Abu Dhabi if the museums and the Grand Mosque are the actual reason for the trip, or if you are here for the Grand Prix." },
      { question: "How many days do I need in the UAE?", answer: "Three days covers Dubai's essentials. Five gets you Dubai properly plus a full Abu Dhabi day. Seven adds the east coast or a second Abu Dhabi day and is about the point of comfortable saturation — beyond that most visitors are better off adding Oman than staying put." },
      { question: "Do I need a visa?", answer: "Many nationalities receive a visa on arrival; others must apply in advance. Rules vary considerably by passport, so check the official UAE government guidance for yours rather than a summary. Passports generally need six months of validity remaining." },
      { question: "Is the UAE expensive?", answer: "It can be either. Hotels and alcohol are expensive; taxis, the metro, food outside the tourist strips and most attractions are reasonable. Eating where residents eat — Deira and Karama in Dubai, the older parts of Abu Dhabi — costs a fraction of a Downtown restaurant for better food." },
      { question: "Can I fit the east coast into three days?", answer: "No. Fujairah and Khorfakkan are two hours across the country each way, which makes them a full day. With three days that day has to come out of Dubai or Abu Dhabi, and neither is a good trade on a first visit." },
    ],
  },
  "4-days": {
    days: 4,
    title: "4 Days in the UAE",
    metaTitle: "4 Days in the UAE: Dubai, the Desert and Abu Dhabi",
    metaDescription: "A four-day UAE itinerary with Dubai's two halves, a desert night and a full Abu Dhabi day — including which day to make the mosque.",
    routeSummary: "Old Dubai and Downtown → the Marina and the Palm → the desert → Abu Dhabi, sleeping in Dubai throughout",
    intro: "The fourth day is the one that changes the trip. With three days everything is timed to the minute; with four, the desert gets its own day rather than being bolted onto an afternoon, and Abu Dhabi gets a proper visit rather than a drive-past. Still one hotel throughout — Dubai is the better base and Abu Dhabi is comfortably a day trip.",
    bestFor: "First visits with a weekend either side, and anyone who wants the desert without cutting the city short.",
    quickAnswer: "Four days lets you stop rushing. Day 1: Old Dubai, the creek and the souks. Day 2: the Marina, the Palm and the beach. Day 3: an overnight desert safari, or a standard evening one plus the Dubai Frame and the aquarium. Day 4: Abu Dhabi for the Grand Mosque, Qasr Al Watan and the Louvre. The fourth day is what turns a rushed three-day trip into a comfortable one.",
    days_detail: [
      {
        day: 1,
        base: "Dubai",
        heading: "Old Dubai and the souks",
        narrative: "Al Fahidi's wind-tower lanes in the morning, the abra across the creek, then the gold and spice souks with lunch in Deira. Afternoon at the Dubai Frame in Zabeel Park, which sits between the two halves of the city and frames the old town on one side of its deck and the skyline on the other — the clearest way to understand what happened here in fifty years.",
        tours: ["https://www.asiabylocals.com/uae/dubai/old-dubai-walking-tour-with-souks-street-food-and-abra-ride", "https://www.asiabylocals.com/uae/dubai/dubai-frame-tickets-with-old-town-creek-and-blue-mosque-tour"],
        travel: null,
        tip: "",
      },
      {
        day: 2,
        base: "Dubai",
        heading: "Downtown, the tower and the fountain",
        narrative: "A slower Downtown day. The Dubai Aquarium in the mall in the morning — the walk-through tunnel with rays and sharks overhead is better than the view from the shops suggests — then the mall itself, which is a destination whether or not you want it to be.\n\nBurj Khalifa timed for ninety minutes before sunset, then the fountain at the base, then dinner at Souk Al Bahar on the terrace over the lake rather than inside the mall.",
        tours: ["https://www.asiabylocals.com/uae/dubai/burj-khalifa-124-125-and-dubai-aquarium-combo-ticket", "https://www.asiabylocals.com/uae/dubai/dubai-fountain-abra-lake-ride-at-the-burj-khalifa", "https://www.asiabylocals.com/uae/dubai/dubai-aquarium-and-underwater-zoo-ticket"],
        travel: null,
        tip: "",
      },
      {
        day: 3,
        base: "Dubai and the desert",
        heading: "The Marina, the water and the desert",
        narrative: "Morning on the water out of Dubai Marina, then the beach at JBR, then the desert from mid-afternoon.\n\nWith four days, consider the overnight safari instead of the standard evening one. Everybody else leaves the camp around ten; if you stay, the generators go quiet and the sky over the Al Lahbab dunes becomes something you cannot see near the city. You sleep in a tent and get sunrise over the dunes, which almost nobody sees.",
        tours: ["https://www.asiabylocals.com/uae/dubai/dubai-marina-yacht-tour-with-breakfast-or-barbecue", "https://www.asiabylocals.com/uae/dubai/dubai-overnight-desert-safari-with-private-tent-and-stargazing", "https://www.asiabylocals.com/uae/dubai/dubai-red-dune-evening-safari-with-camel-ride-and-bbq-camp"],
        travel: null,
        tip: "",
      },
      {
        day: 4,
        base: "Dubai",
        heading: "Abu Dhabi: mosque, palace and the Louvre",
        narrative: "With a full day, the version worth taking pairs the Grand Mosque with Louvre Abu Dhabi and gives two hours to each, rather than the twenty-minute stops a general city tour allows.\n\nJean Nouvel's dome is nearly eight thousand metal stars dropping a shifting pattern across the plazas below, and the collection under it is hung chronologically across civilisations rather than split by country — an argument about shared history, made in objects.\n\nCheck your day: the Louvre closes on Mondays and the mosque shuts to visitors on Friday mornings.",
        tours: ["https://www.asiabylocals.com/uae/dubai/louvre-abu-dhabi-and-grand-mosque-day-trip-from-dubai", "https://www.asiabylocals.com/uae/dubai/abu-dhabi-full-day-tour-from-dubai-with-grand-mosque-and-corniche"],
        travel: null,
        tip: "",
      },
    ],
    logistics: [
      { heading: "Getting around", content: "Dubai runs about seventy kilometres along the coast and the two areas you most want — Downtown with the Burj Khalifa, and the Marina with the Palm — are half an hour apart on a good day. Plan each day around one end of the city rather than crossing repeatedly. The metro's Red Line follows Sheikh Zayed Road and connects the airport, Downtown, the Marina and Expo City; it is faster than a car at rush hour and needs a Nol card, sold at every station. Taxis are metered, plentiful and cheap by European standards, and Careem is the local ride app. For anything outside the city — the desert, Abu Dhabi, the east coast — book a vehicle with a driver rather than metering a taxi." },
      { heading: "Abu Dhabi from Dubai", content: "Ninety minutes each way by road. That is three hours of a day gone, which leaves about seven for the city — enough for three major sites, not five. If Abu Dhabi is genuinely the reason for the trip, stay there rather than day-tripping: the mosque at sunrise and the palace lit at night are the versions worth having, and no day trip reaches either." },
      { heading: "Two closures that ruin plans", content: "Sheikh Zayed Grand Mosque does not admit visitors on Friday mornings. Louvre Abu Dhabi is closed all day Monday. Between them these catch out an extraordinary number of visitors, because a day trip has no second chance. Qasr Al Watan adds a third, less predictable risk — it shuts at short notice for state functions, and that is not published in advance. Give us your dates and we check all three with the operator before you pay." },
      { heading: "What to wear", content: "In malls, souks and public areas, shoulders and knees covered is the norm and swimwear stays at the beach or pool. At the Grand Mosque the code is enforced on everyone including men: no shorts, nothing tight or sheer, and hair covered for women — an abaya is provided free at the door. Shoes come off inside prayer halls and the marble outside gets painfully hot by midday, so carry socks." },
      { heading: "Heat, and how it shapes a trip", content: "November to March is the season. Between June and September the temperature reaches the mid-forties with humidity off the Gulf, and anything outdoors between ten in the morning and five in the evening becomes an endurance test. The city is built for it — three of the four Yas Island parks, the aquarium, the Green Planet and every mall are fully air-conditioned — but a summer plan has to be front-loaded before nine and restarted at dusk." },
      { heading: "Alcohol, Ramadan and the working week", content: "Alcohol is served in licensed hotels, bars and restaurants and is not sold in ordinary supermarkets. Drinking in public is an offence. During Ramadan, eating, drinking and smoking in public during daylight is restricted, though hotels serve guests throughout the day and visitors are not expected to fast; iftar at sunset is the most sociable hour of the year and worth planning for rather than around. The working week is Monday to Friday with Saturday and Sunday the weekend, so attractions are busiest at weekends exactly as they are elsewhere." },
    ],
    faqs: [
      { question: "Is Dubai or Abu Dhabi the better base?", answer: "Dubai, for a first visit. It has more to do, better transport and a wider choice of hotels, and Abu Dhabi is a comfortable day trip from it. Base yourself in Abu Dhabi if the museums and the Grand Mosque are the actual reason for the trip, or if you are here for the Grand Prix." },
      { question: "How many days do I need in the UAE?", answer: "Three days covers Dubai's essentials. Five gets you Dubai properly plus a full Abu Dhabi day. Seven adds the east coast or a second Abu Dhabi day and is about the point of comfortable saturation — beyond that most visitors are better off adding Oman than staying put." },
      { question: "Do I need a visa?", answer: "Many nationalities receive a visa on arrival; others must apply in advance. Rules vary considerably by passport, so check the official UAE government guidance for yours rather than a summary. Passports generally need six months of validity remaining." },
      { question: "Is the UAE expensive?", answer: "It can be either. Hotels and alcohol are expensive; taxis, the metro, food outside the tourist strips and most attractions are reasonable. Eating where residents eat — Deira and Karama in Dubai, the older parts of Abu Dhabi — costs a fraction of a Downtown restaurant for better food." },
      { question: "Is the overnight desert safari worth the extra?", answer: "If you have a spare night, yes — it is a different trip rather than a longer one. The camp empties around ten and what is left is silence, a genuinely dark sky and sunrise over the dunes. If your days are tight, the standard evening safari covers the same dune driving and camp dinner in six hours." },
    ],
  },
  "5-days": {
    days: 5,
    title: "5 Days in the UAE",
    metaTitle: "5 Days in the UAE: Dubai, Abu Dhabi and the Desert",
    metaDescription: "Five days across Dubai and Abu Dhabi with a night in the capital, the Yas Island parks and a desert safari — a route built around the geography.",
    routeSummary: "Three nights Dubai → two nights Abu Dhabi, with the desert on the Dubai side and Yas Island on the capital side",
    intro: "At five days the calculation changes. Up to four, one hotel in Dubai is right and Abu Dhabi is a day trip. At five, two nights in the capital buys you the two things a day trip cannot: the Grand Mosque early in the morning when it is cool and empty, and Qasr Al Watan floodlit with its projection show after dark. It also puts Yas Island within reach without a three-hour round trip.",
    bestFor: "Anyone who wants both cities properly rather than one city and a long drive.",
    quickAnswer: "Five days is the first length where moving hotels pays for itself. Three nights in Dubai for Old Dubai, Downtown, the Marina and the desert, then two nights in Abu Dhabi for the Grand Mosque, Qasr Al Watan, the Louvre and Yas Island. Staying in Abu Dhabi gets you the mosque at sunrise and the palace lit at night, which no day trip reaches.",
    days_detail: [
      {
        day: 1,
        base: "Dubai",
        heading: "Old Dubai, the creek and the souks",
        narrative: "Al Fahidi in the morning, the abra across the creek, the gold and spice souks, and lunch in Deira. Afternoon at the Dubai Frame. An easy first day that beats jet lag and puts the city in context before you see any of the tall parts.",
        tours: ["https://www.asiabylocals.com/uae/dubai/old-dubai-walking-tour-with-souks-street-food-and-abra-ride", "https://www.asiabylocals.com/uae/dubai/dubai-frame-tickets-with-old-town-creek-and-blue-mosque-tour"],
        travel: null,
        tip: "",
      },
      {
        day: 2,
        base: "Dubai",
        heading: "Downtown and the tower",
        narrative: "The aquarium and the mall in the morning, the Burj Khalifa before sunset, and the fountain from the lake afterwards. If it is a hot month, this is the day that is almost entirely indoors and it is worth putting where the forecast is worst.",
        tours: ["https://www.asiabylocals.com/uae/dubai/burj-khalifa-124-125-and-dubai-aquarium-combo-ticket", "https://www.asiabylocals.com/uae/dubai/dubai-fountain-abra-lake-ride-at-the-burj-khalifa"],
        travel: null,
        tip: "",
      },
      {
        day: 3,
        base: "Dubai",
        heading: "The Marina, the Palm and the desert",
        narrative: "Water in the morning out of the Marina — speedboat for speed and photographs, yacht for shade and time. Beach and lunch at JBR. Desert safari from mid-afternoon: dune bashing, sunset, camp dinner and shows, back around nine.\n\nMove hotels to Abu Dhabi tomorrow morning rather than tonight; the safari finishes late and nobody enjoys checking in at eleven.",
        tours: ["https://www.asiabylocals.com/uae/dubai/dubai-speedboat-tour-marina-palm-atlantis-and-burj-al-arab", "https://www.asiabylocals.com/uae/dubai/dubai-red-dune-evening-safari-with-camel-ride-and-bbq-camp", "https://www.asiabylocals.com/uae/dubai/dubai-premium-desert-safari-al-khayma-camp-with-three-buffets"],
        travel: null,
        tip: "",
      },
      {
        day: 4,
        base: "Abu Dhabi",
        heading: "The mosque, the palace and the Corniche",
        narrative: "Drive down mid-morning and check in. The Grand Mosque in the afternoon, or first thing tomorrow if you would rather have it empty — this is the advantage of sleeping here.\n\nQasr Al Watan late in the day, timed so you are there as the floodlights come on and the projection show starts on the façade. Dinner along the Corniche, which is where the city actually goes in the evening.",
        tours: ["https://www.asiabylocals.com/uae/abu-dhabi/abu-dhabi-grand-mosque-qasr-al-watan-and-etihad-towers-tour", "https://www.asiabylocals.com/uae/abu-dhabi/abu-dhabi-grand-mosque-and-qasr-al-watan-private-transfer-tour", "https://www.asiabylocals.com/uae/abu-dhabi/abu-dhabi-half-day-city-tour-with-grand-mosque-and-heritage-village"],
        travel: null,
        tip: "",
      },
      {
        day: 5,
        base: "Abu Dhabi",
        heading: "Saadiyat or Yas — museums or parks",
        narrative: "Two ways to spend the last day and they do not combine.\n\nSaadiyat, if you want the Louvre — allow two to three hours, and go on a bright day for the rain of light through the dome. A kayak around the building beforehand shows you the side it was designed for and almost nobody sees.\n\nYas Island, if there are children or petrolheads in the group — Ferrari World, SeaWorld or Warner Bros. World, all within walking distance of each other, and a multi-park pass costs less than separate tickets.\n\nThe Louvre closes on Mondays. Plan the order around that.",
        tours: ["https://www.asiabylocals.com/uae/abu-dhabi/louvre-abu-dhabi-general-admission-ticket", "https://www.asiabylocals.com/uae/abu-dhabi/abu-dhabi-guided-kayak-tour-around-the-louvre", "https://www.asiabylocals.com/uae/abu-dhabi/yas-island-multi-park-pass-abu-dhabi-two-three-or-four-parks", "https://www.asiabylocals.com/uae/abu-dhabi/ferrari-world-abu-dhabi-entry-ticket"],
        travel: null,
        tip: "",
      },
    ],
    logistics: [
      { heading: "Getting around", content: "Dubai runs about seventy kilometres along the coast and the two areas you most want — Downtown with the Burj Khalifa, and the Marina with the Palm — are half an hour apart on a good day. Plan each day around one end of the city rather than crossing repeatedly. The metro's Red Line follows Sheikh Zayed Road and connects the airport, Downtown, the Marina and Expo City; it is faster than a car at rush hour and needs a Nol card, sold at every station. Taxis are metered, plentiful and cheap by European standards, and Careem is the local ride app. For anything outside the city — the desert, Abu Dhabi, the east coast — book a vehicle with a driver rather than metering a taxi." },
      { heading: "Abu Dhabi from Dubai", content: "Ninety minutes each way by road. That is three hours of a day gone, which leaves about seven for the city — enough for three major sites, not five. If Abu Dhabi is genuinely the reason for the trip, stay there rather than day-tripping: the mosque at sunrise and the palace lit at night are the versions worth having, and no day trip reaches either." },
      { heading: "Two closures that ruin plans", content: "Sheikh Zayed Grand Mosque does not admit visitors on Friday mornings. Louvre Abu Dhabi is closed all day Monday. Between them these catch out an extraordinary number of visitors, because a day trip has no second chance. Qasr Al Watan adds a third, less predictable risk — it shuts at short notice for state functions, and that is not published in advance. Give us your dates and we check all three with the operator before you pay." },
      { heading: "What to wear", content: "In malls, souks and public areas, shoulders and knees covered is the norm and swimwear stays at the beach or pool. At the Grand Mosque the code is enforced on everyone including men: no shorts, nothing tight or sheer, and hair covered for women — an abaya is provided free at the door. Shoes come off inside prayer halls and the marble outside gets painfully hot by midday, so carry socks." },
      { heading: "Heat, and how it shapes a trip", content: "November to March is the season. Between June and September the temperature reaches the mid-forties with humidity off the Gulf, and anything outdoors between ten in the morning and five in the evening becomes an endurance test. The city is built for it — three of the four Yas Island parks, the aquarium, the Green Planet and every mall are fully air-conditioned — but a summer plan has to be front-loaded before nine and restarted at dusk." },
      { heading: "Alcohol, Ramadan and the working week", content: "Alcohol is served in licensed hotels, bars and restaurants and is not sold in ordinary supermarkets. Drinking in public is an offence. During Ramadan, eating, drinking and smoking in public during daylight is restricted, though hotels serve guests throughout the day and visitors are not expected to fast; iftar at sunset is the most sociable hour of the year and worth planning for rather than around. The working week is Monday to Friday with Saturday and Sunday the weekend, so attractions are busiest at weekends exactly as they are elsewhere." },
    ],
    faqs: [
      { question: "Is Dubai or Abu Dhabi the better base?", answer: "Dubai, for a first visit. It has more to do, better transport and a wider choice of hotels, and Abu Dhabi is a comfortable day trip from it. Base yourself in Abu Dhabi if the museums and the Grand Mosque are the actual reason for the trip, or if you are here for the Grand Prix." },
      { question: "How many days do I need in the UAE?", answer: "Three days covers Dubai's essentials. Five gets you Dubai properly plus a full Abu Dhabi day. Seven adds the east coast or a second Abu Dhabi day and is about the point of comfortable saturation — beyond that most visitors are better off adding Oman than staying put." },
      { question: "Do I need a visa?", answer: "Many nationalities receive a visa on arrival; others must apply in advance. Rules vary considerably by passport, so check the official UAE government guidance for yours rather than a summary. Passports generally need six months of validity remaining." },
      { question: "Is the UAE expensive?", answer: "It can be either. Hotels and alcohol are expensive; taxis, the metro, food outside the tourist strips and most attractions are reasonable. Eating where residents eat — Deira and Karama in Dubai, the older parts of Abu Dhabi — costs a fraction of a Downtown restaurant for better food." },
      { question: "Is it worth changing hotels for two nights in Abu Dhabi?", answer: "At five days or more, yes. It buys the Grand Mosque at sunrise and Qasr Al Watan lit at night, neither of which a day trip reaches, and it removes three hours of driving from two separate days. At four days or fewer it is not worth the packing." },
    ],
  },
  "6-days": {
    days: 6,
    title: "6 Days in the UAE",
    metaTitle: "6 Days in the UAE: Both Cities and the East Coast",
    metaDescription: "Six days across Dubai, Abu Dhabi and the Gulf of Oman coast at Fujairah — including the mountain half of the country most visitors never see.",
    routeSummary: "Three nights Dubai → the east coast → two nights Abu Dhabi",
    intro: "At six days you can afford a day that is not in either city, and the one worth taking crosses the country to the other coast. The Hajar mountains rise out of the gravel plains, the road climbs through them, and on the far side is the Gulf of Oman — green water, no skyline, and mountains that surprise people who came expecting only sand. It is the half of the Emirates almost no visitor sees.",
    bestFor: "Second visits, and first visits by anyone who wants more than the two skylines.",
    quickAnswer: "Six days is where the UAE stops being two cities. Three nights in Dubai for the old town, Downtown, the Marina and the desert; a full day crossing to the Gulf of Oman at Fujairah and Khorfakkan, where the Hajar mountains come down to a green sea; then two nights in Abu Dhabi for the mosque, the palace, the Louvre and Yas Island.",
    days_detail: [
      {
        day: 1,
        base: "Dubai",
        heading: "Old Dubai and the souks",
        narrative: "Al Fahidi, the abra, the gold and spice souks, lunch in Deira, and the Dubai Frame in the afternoon.",
        tours: ["https://www.asiabylocals.com/uae/dubai/old-dubai-walking-tour-with-souks-street-food-and-abra-ride", "https://www.asiabylocals.com/uae/dubai/dubai-frame-tickets-with-old-town-creek-and-blue-mosque-tour"],
        travel: null,
        tip: "",
      },
      {
        day: 2,
        base: "Dubai",
        heading: "Downtown, the tower and the fountain",
        narrative: "Aquarium and mall in the morning, Burj Khalifa before sunset, fountain from the lake afterwards.",
        tours: ["https://www.asiabylocals.com/uae/dubai/burj-khalifa-124-125-and-dubai-aquarium-combo-ticket", "https://www.asiabylocals.com/uae/dubai/dubai-fountain-abra-lake-ride-at-the-burj-khalifa"],
        travel: null,
        tip: "",
      },
      {
        day: 3,
        base: "Dubai",
        heading: "The Marina, the Palm and the desert",
        narrative: "Morning on the water, afternoon at the beach, desert safari from mid-afternoon with dinner at the camp.",
        tours: ["https://www.asiabylocals.com/uae/dubai/dubai-marina-luxury-yacht-cruise-with-onboard-barbecue", "https://www.asiabylocals.com/uae/dubai/dubai-red-dune-evening-safari-with-camel-ride-and-bbq-camp"],
        travel: null,
        tip: "",
      },
      {
        day: 4,
        base: "Dubai",
        heading: "Across the country to the Gulf of Oman",
        narrative: "A long day and the best one. The road crosses the gravel plains and climbs into the Hajar mountains, and on the far side the Sheikh Zayed Mosque at Fujairah — a smaller, quieter sister to the famous one — and the Fujairah Museum with Bronze Age finds from this coast. Then the mountain road to Khorfakkan, an amphitheatre and waterfall built into the hillside above a curved beach.\n\nThe water on this coast is calm and clear in a way the Dubai side is not, so bring something to swim in. If snorkelling appeals, the Dibba boats go out onto reefs with rays and turtles.",
        tours: ["https://www.asiabylocals.com/uae/dubai/dibba-fujairah-snorkelling-day-trip-from-dubai"],
        travel: null,
        tip: "",
      },
      {
        day: 5,
        base: "Abu Dhabi",
        heading: "The mosque, the palace and the Corniche",
        narrative: "Drive down and check in. Grand Mosque, Qasr Al Watan timed for the evening lighting, and dinner along the Corniche.",
        tours: ["https://www.asiabylocals.com/uae/abu-dhabi/abu-dhabi-grand-mosque-qasr-al-watan-and-etihad-towers-tour", "https://www.asiabylocals.com/uae/abu-dhabi/abu-dhabi-grand-mosque-and-qasr-al-watan-private-transfer-tour"],
        travel: null,
        tip: "",
      },
      {
        day: 6,
        base: "Abu Dhabi",
        heading: "Saadiyat, Yas, or the water",
        narrative: "The Louvre and a kayak around it, or a Yas Island park, or — the option most visitors never consider — the mangroves and Reem Central Park's waterways, which run through the middle of the city and are almost silent once you are paddling.\n\nAbu Dhabi has more accessible water than Dubai and far fewer people using it, and after five days of buildings it is a good last morning.",
        tours: ["https://www.asiabylocals.com/uae/abu-dhabi/louvre-abu-dhabi-general-admission-ticket", "https://www.asiabylocals.com/uae/abu-dhabi/abu-dhabi-reem-central-park-guided-kayak-tour", "https://www.asiabylocals.com/uae/abu-dhabi/seaworld-abu-dhabi-general-admission-ticket"],
        travel: null,
        tip: "",
      },
    ],
    logistics: [
      { heading: "Getting around", content: "Dubai runs about seventy kilometres along the coast and the two areas you most want — Downtown with the Burj Khalifa, and the Marina with the Palm — are half an hour apart on a good day. Plan each day around one end of the city rather than crossing repeatedly. The metro's Red Line follows Sheikh Zayed Road and connects the airport, Downtown, the Marina and Expo City; it is faster than a car at rush hour and needs a Nol card, sold at every station. Taxis are metered, plentiful and cheap by European standards, and Careem is the local ride app. For anything outside the city — the desert, Abu Dhabi, the east coast — book a vehicle with a driver rather than metering a taxi." },
      { heading: "Abu Dhabi from Dubai", content: "Ninety minutes each way by road. That is three hours of a day gone, which leaves about seven for the city — enough for three major sites, not five. If Abu Dhabi is genuinely the reason for the trip, stay there rather than day-tripping: the mosque at sunrise and the palace lit at night are the versions worth having, and no day trip reaches either." },
      { heading: "Two closures that ruin plans", content: "Sheikh Zayed Grand Mosque does not admit visitors on Friday mornings. Louvre Abu Dhabi is closed all day Monday. Between them these catch out an extraordinary number of visitors, because a day trip has no second chance. Qasr Al Watan adds a third, less predictable risk — it shuts at short notice for state functions, and that is not published in advance. Give us your dates and we check all three with the operator before you pay." },
      { heading: "What to wear", content: "In malls, souks and public areas, shoulders and knees covered is the norm and swimwear stays at the beach or pool. At the Grand Mosque the code is enforced on everyone including men: no shorts, nothing tight or sheer, and hair covered for women — an abaya is provided free at the door. Shoes come off inside prayer halls and the marble outside gets painfully hot by midday, so carry socks." },
      { heading: "Heat, and how it shapes a trip", content: "November to March is the season. Between June and September the temperature reaches the mid-forties with humidity off the Gulf, and anything outdoors between ten in the morning and five in the evening becomes an endurance test. The city is built for it — three of the four Yas Island parks, the aquarium, the Green Planet and every mall are fully air-conditioned — but a summer plan has to be front-loaded before nine and restarted at dusk." },
      { heading: "Alcohol, Ramadan and the working week", content: "Alcohol is served in licensed hotels, bars and restaurants and is not sold in ordinary supermarkets. Drinking in public is an offence. During Ramadan, eating, drinking and smoking in public during daylight is restricted, though hotels serve guests throughout the day and visitors are not expected to fast; iftar at sunset is the most sociable hour of the year and worth planning for rather than around. The working week is Monday to Friday with Saturday and Sunday the weekend, so attractions are busiest at weekends exactly as they are elsewhere." },
    ],
    faqs: [
      { question: "Is Dubai or Abu Dhabi the better base?", answer: "Dubai, for a first visit. It has more to do, better transport and a wider choice of hotels, and Abu Dhabi is a comfortable day trip from it. Base yourself in Abu Dhabi if the museums and the Grand Mosque are the actual reason for the trip, or if you are here for the Grand Prix." },
      { question: "How many days do I need in the UAE?", answer: "Three days covers Dubai's essentials. Five gets you Dubai properly plus a full Abu Dhabi day. Seven adds the east coast or a second Abu Dhabi day and is about the point of comfortable saturation — beyond that most visitors are better off adding Oman than staying put." },
      { question: "Do I need a visa?", answer: "Many nationalities receive a visa on arrival; others must apply in advance. Rules vary considerably by passport, so check the official UAE government guidance for yours rather than a summary. Passports generally need six months of validity remaining." },
      { question: "Is the UAE expensive?", answer: "It can be either. Hotels and alcohol are expensive; taxis, the metro, food outside the tourist strips and most attractions are reasonable. Eating where residents eat — Deira and Karama in Dubai, the older parts of Abu Dhabi — costs a fraction of a Downtown restaurant for better food." },
      { question: "Is the east coast worth a whole day?", answer: "If you have six days or more, yes. It is three to four hours of driving in total, and what you get is mountains, a green sea and a coastline with no towers on it — the opposite of everything else on the trip. With five days or fewer, spend the day in Abu Dhabi instead." },
    ],
  },
  "7-days": {
    days: 7,
    title: "7 Days in the UAE",
    metaTitle: "7 Days in the UAE: A Complete Route",
    metaDescription: "A full week across Dubai, the east coast and Abu Dhabi, with a desert night, the Yas Island parks and time that is not spent in a car.",
    routeSummary: "Four nights Dubai (one of them in the desert) → the east coast → two nights Abu Dhabi",
    intro: "Seven days is the honest ceiling for the UAE as a single destination, and we would rather say so than sell you a ten-day page. What a week buys over five days is not more sights but more room: a night actually spent in the desert, a day on the other coast, and mornings that are not scheduled. That is the difference between seeing the country and moving through it.",
    bestFor: "A full holiday rather than a stopover, and anyone travelling far enough that a short trip is not worth the flight.",
    quickAnswer: "A week is comfortable saturation for the UAE. Four nights based in Dubai with one of them spent in a desert camp, a day crossing to the Gulf of Oman at Fujairah, and two nights in Abu Dhabi covering the Grand Mosque, Qasr Al Watan, the Louvre and Yas Island. Beyond seven days most visitors are better off adding Oman than staying put.",
    days_detail: [
      {
        day: 1,
        base: "Dubai",
        heading: "Old Dubai, the creek and the souks",
        narrative: "Al Fahidi's wind-tower lanes, the abra across the creek, gold and spice souks, lunch in Deira. An easy arrival day that puts the city in context before the tall parts.",
        tours: ["https://www.asiabylocals.com/uae/dubai/old-dubai-walking-tour-with-souks-street-food-and-abra-ride"],
        travel: null,
        tip: "",
      },
      {
        day: 2,
        base: "Dubai",
        heading: "Downtown, the tower and the fountain",
        narrative: "The aquarium and mall in the morning, the Dubai Frame in the early afternoon, the Burj Khalifa before sunset and the fountain from a boat on the lake afterwards.",
        tours: ["https://www.asiabylocals.com/uae/dubai/burj-khalifa-124-125-and-dubai-aquarium-combo-ticket", "https://www.asiabylocals.com/uae/dubai/dubai-frame-tickets-with-old-town-creek-and-blue-mosque-tour", "https://www.asiabylocals.com/uae/dubai/dubai-fountain-abra-lake-ride-at-the-burj-khalifa"],
        travel: null,
        tip: "",
      },
      {
        day: 3,
        base: "Dubai",
        heading: "The Marina, the Palm and the water",
        narrative: "A whole day at the western end. Morning on a yacht or speedboat past Ain Dubai, the Palm and the Burj Al Arab, with a swim stop if the boat has one. Beach and lunch at JBR. Late afternoon, a helicopter over the Palm if the budget stretches — it is the only way to see the shape properly — or parasailing off the Marina for a tenth of the price.",
        tours: ["https://www.asiabylocals.com/uae/dubai/dubai-superyacht-cruise-with-live-dj-swim-stop-and-open-bar", "https://www.asiabylocals.com/uae/dubai/dubai-helicopter-tour-over-the-palm-and-burj-al-arab", "https://www.asiabylocals.com/uae/dubai/dubai-parasailing-over-the-marina-with-palm-and-jbr-views"],
        travel: null,
        tip: "",
      },
      {
        day: 4,
        base: "The desert",
        heading: "A night in the desert",
        narrative: "The overnight safari, which with a week is unarguable. Dune bashing across the Al Lahbab red dunes in the afternoon, sandboarding, camel riding, sunset, and a camp evening with dinner and shows.\n\nThen everybody else leaves and you stay. The generators go quiet, the sky opens, and you sleep in a tent rather than driving back to a hotel. Sunrise over the dunes the next morning is the part almost no visitor to the UAE ever sees.",
        tours: ["https://www.asiabylocals.com/uae/dubai/dubai-overnight-desert-safari-with-private-tent-and-stargazing"],
        travel: null,
        tip: "",
      },
      {
        day: 5,
        base: "Dubai",
        heading: "Across to the Gulf of Oman",
        narrative: "The east coast day. Through the Hajar mountains to Fujairah and Khorfakkan — a smaller Sheikh Zayed Mosque, a museum of Bronze Age finds, an amphitheatre and waterfall above a curved beach, and a green sea with no skyline behind it.\n\nSnorkelling out of Dibba if the water appeals; the reefs here hold rays and turtles and the visibility is good most of the year.",
        tours: ["https://www.asiabylocals.com/uae/dubai/dibba-fujairah-snorkelling-day-trip-from-dubai"],
        travel: null,
        tip: "",
      },
      {
        day: 6,
        base: "Abu Dhabi",
        heading: "The mosque, the palace and the Corniche",
        narrative: "Move down mid-morning. The Grand Mosque, then Qasr Al Watan timed so you are there as the floodlights come on and the projection show starts. Dinner along the Corniche.\n\nStaying the night here is what makes tomorrow's early mosque visit possible, if you want it a second time when it is empty.",
        tours: ["https://www.asiabylocals.com/uae/abu-dhabi/abu-dhabi-grand-mosque-qasr-al-watan-and-etihad-towers-tour", "https://www.asiabylocals.com/uae/abu-dhabi/abu-dhabi-half-day-city-tour-with-grand-mosque-and-heritage-village"],
        travel: null,
        tip: "",
      },
      {
        day: 7,
        base: "Abu Dhabi",
        heading: "Saadiyat, Yas or the water",
        narrative: "The last day is a genuine choice rather than a leftover.\n\nSaadiyat for the Louvre and teamLab Phenomena, whose installations respond to air, water and the people moving through them — two hours minimum, and nothing is on a loop.\n\nYas Island for Ferrari World, SeaWorld or Warner Bros. World, three of which are fully indoors and are what residents do in summer.\n\nOr the water: kayaking the Reem Central Park waterways or around the Louvre's dome, which is quiet in a way nothing else on this trip has been.\n\nThe Louvre closes on Mondays.",
        tours: ["https://www.asiabylocals.com/uae/abu-dhabi/louvre-abu-dhabi-general-admission-ticket", "https://www.asiabylocals.com/uae/abu-dhabi/teamlab-phenomena-abu-dhabi-entry-ticket", "https://www.asiabylocals.com/uae/abu-dhabi/yas-island-multi-park-pass-abu-dhabi-two-three-or-four-parks", "https://www.asiabylocals.com/uae/abu-dhabi/abu-dhabi-guided-kayak-tour-around-the-louvre"],
        travel: null,
        tip: "",
      },
    ],
    logistics: [
      { heading: "Getting around", content: "Dubai runs about seventy kilometres along the coast and the two areas you most want — Downtown with the Burj Khalifa, and the Marina with the Palm — are half an hour apart on a good day. Plan each day around one end of the city rather than crossing repeatedly. The metro's Red Line follows Sheikh Zayed Road and connects the airport, Downtown, the Marina and Expo City; it is faster than a car at rush hour and needs a Nol card, sold at every station. Taxis are metered, plentiful and cheap by European standards, and Careem is the local ride app. For anything outside the city — the desert, Abu Dhabi, the east coast — book a vehicle with a driver rather than metering a taxi." },
      { heading: "Abu Dhabi from Dubai", content: "Ninety minutes each way by road. That is three hours of a day gone, which leaves about seven for the city — enough for three major sites, not five. If Abu Dhabi is genuinely the reason for the trip, stay there rather than day-tripping: the mosque at sunrise and the palace lit at night are the versions worth having, and no day trip reaches either." },
      { heading: "Two closures that ruin plans", content: "Sheikh Zayed Grand Mosque does not admit visitors on Friday mornings. Louvre Abu Dhabi is closed all day Monday. Between them these catch out an extraordinary number of visitors, because a day trip has no second chance. Qasr Al Watan adds a third, less predictable risk — it shuts at short notice for state functions, and that is not published in advance. Give us your dates and we check all three with the operator before you pay." },
      { heading: "What to wear", content: "In malls, souks and public areas, shoulders and knees covered is the norm and swimwear stays at the beach or pool. At the Grand Mosque the code is enforced on everyone including men: no shorts, nothing tight or sheer, and hair covered for women — an abaya is provided free at the door. Shoes come off inside prayer halls and the marble outside gets painfully hot by midday, so carry socks." },
      { heading: "Heat, and how it shapes a trip", content: "November to March is the season. Between June and September the temperature reaches the mid-forties with humidity off the Gulf, and anything outdoors between ten in the morning and five in the evening becomes an endurance test. The city is built for it — three of the four Yas Island parks, the aquarium, the Green Planet and every mall are fully air-conditioned — but a summer plan has to be front-loaded before nine and restarted at dusk." },
      { heading: "Alcohol, Ramadan and the working week", content: "Alcohol is served in licensed hotels, bars and restaurants and is not sold in ordinary supermarkets. Drinking in public is an offence. During Ramadan, eating, drinking and smoking in public during daylight is restricted, though hotels serve guests throughout the day and visitors are not expected to fast; iftar at sunset is the most sociable hour of the year and worth planning for rather than around. The working week is Monday to Friday with Saturday and Sunday the weekend, so attractions are busiest at weekends exactly as they are elsewhere." },
    ],
    faqs: [
      { question: "Is Dubai or Abu Dhabi the better base?", answer: "Dubai, for a first visit. It has more to do, better transport and a wider choice of hotels, and Abu Dhabi is a comfortable day trip from it. Base yourself in Abu Dhabi if the museums and the Grand Mosque are the actual reason for the trip, or if you are here for the Grand Prix." },
      { question: "How many days do I need in the UAE?", answer: "Three days covers Dubai's essentials. Five gets you Dubai properly plus a full Abu Dhabi day. Seven adds the east coast or a second Abu Dhabi day and is about the point of comfortable saturation — beyond that most visitors are better off adding Oman than staying put." },
      { question: "Do I need a visa?", answer: "Many nationalities receive a visa on arrival; others must apply in advance. Rules vary considerably by passport, so check the official UAE government guidance for yours rather than a summary. Passports generally need six months of validity remaining." },
      { question: "Is the UAE expensive?", answer: "It can be either. Hotels and alcohol are expensive; taxis, the metro, food outside the tourist strips and most attractions are reasonable. Eating where residents eat — Deira and Karama in Dubai, the older parts of Abu Dhabi — costs a fraction of a Downtown restaurant for better food." },
      { question: "Should I stay more than a week?", answer: "Most visitors should not. The UAE is two cities ninety minutes apart plus a coastline, and past seven days you are repeating yourself. If you have longer, the better move is to add Oman — Musandam is a couple of hours from Dubai and is a completely different country in every sense that matters." },
    ],
  },
};
