// Vietnam itineraries (2026-09). Same ItineraryData shape as the other sets.
// Vietnam is 1,600km end to end, so every route here is built around the
// domestic flights that make it possible rather than pretending the country
// can be driven.
import type { ItineraryData } from './japanItineraries';

const U = 'https://www.asiabylocals.com/vietnam';

export const VIETNAM_ITINERARIES: Record<string, ItineraryData> = {
  '3-days': {
    days: 3,
    quickAnswer: "With three days in Vietnam, stay in the north. Two days in Hanoi for the Old Quarter, the street food and a morning at the lake, and one full day out to Ha Long Bay. Do not attempt to add the centre or the south: the internal flights alone would eat a day of the three.",
    title: "3 Days in Vietnam: Hanoi and Ha Long Bay",
    metaTitle: "3-Day Vietnam Itinerary: Hanoi and Ha Long Bay 2026",
    metaDescription: "A realistic three-day Vietnam itinerary covering Hanoi's Old Quarter and a full day on Ha Long Bay, with the timings and the day-trip trade-off explained.",
    routeSummary: "Hanoi → Ha Long Bay → Hanoi",
    intro: "Three days is one region, and in Vietnam the north is the one that gives most in the time. Hanoi is compact enough to walk, and Ha Long is close enough to reach and return in a day. The temptation is to squeeze in Hoi An or Saigon; resist it, because each costs a flight and a half day of airports.",
    bestFor: "A first visit, a long weekend, or a stopover extended into something worth doing.",
    days_detail: [
      {
        day: 1,
        base: "Hanoi",
        heading: "The Old Quarter, on foot",
        narrative: "Start early. Hanoi is at its best before eight, when the markets are loudest and the pho stalls are busiest, and much of that has ended by nine.\n\nWalk the Old Quarter without a list. The thirty-six streets were each a trade guild and most still sell roughly what they always sold, so the goods on both sides change at almost every junction. That pattern is the sight.\n\nSpend the hot middle of the day indoors — the Temple of Literature or the women's museum — and come back out at five. In the evening, eat where there is a queue of locals; that rule serves better here than any list.",
        tours: [`${U}/hanoi/small-group-street-food-walking-tour-in-hanoi`, `${U}/hanoi/old-quarter-street-food-tour-with-12-tastings-in-hanoi`],
        travel: null,
        tip: "Cross the road at a slow, even pace and keep going. Motorbikes steer around you; stopping suddenly is what causes the problem.",
      },
      {
        day: 2,
        base: "Ha Long Bay",
        heading: "A full day on the water",
        narrative: "The drive is about two and a half hours each way on the expressway, so this is a twelve-hour day door to door, and a shared transfer adds an hour of hotel pickups on top.\n\nA day cruise puts you on the bay in the middle of the day, which is the busiest window and the flattest light. That is the honest trade: you see the karsts, you do not get them quietly. A typical day runs a cave, a kayak or bamboo-boat stop, a swim in season, and lunch aboard.\n\nIf you can move a night from Hanoi to the boat, do it. It is the single biggest upgrade available in three days.",
        tours: [`${U}/ha-long/ha-long-bay-day-cruise-swimming-meal-kayaking`, `${U}/ha-long/1-day-ha-long-bay-deluxe-cruise`],
        travel: "Hanoi to Ha Long: about 2.5 hours each way by road",
        tip: "Book a private transfer rather than a shared one. On two people or more it is the best-value change on this day and removes the pickup loop entirely.",
      },
      {
        day: 3,
        base: "Hanoi",
        heading: "Water puppets, coffee and a last walk",
        narrative: "Keep this day light, because you are probably flying. The water puppet theatre is an hour and is genuinely old rather than staged for visitors — the form comes from flooded rice paddies.\n\nEgg coffee is the other thing to do before leaving: whipped yolk and condensed milk over hot coffee, invented in Hanoi when milk was scarce, and closer to a dessert than a drink.\n\nIf your flight is late, add the craft villages an hour out of the city — Bat Trang for ceramics or Quang Phu Cau for incense.",
        tours: [`${U}/hanoi/guided-half-day-city-highlights-tour-with-transfers-in-hanoi`, `${U}/hanoi/maya-traditional-cooking-class-and-market-tour-in-hanoi`],
        travel: null,
        tip: "Noi Bai airport is about 45 minutes from the Old Quarter, longer in the evening peak. Leave more room than the map suggests.",
      },
    ],
    logistics: [
      { heading: "Getting around", content: "Hanoi is walkable in the centre and ride-hailing apps cover everything else cheaply. For Ha Long, book the transfer with the cruise rather than arranging it separately — the boats do not wait." },
      { heading: "When to come", content: "October to December and March to April are the best windows: dry, mild and clear. Summer is hot, humid and wet. January and February are cool and often drizzly, and the bay sits under a mist that is beautiful in person and photographs as a flat white sky." },
      { heading: "What this itinerary leaves out", content: "Everything south of Hanoi. Hoi An is a flight away, Saigon is two hours in the air, and Sapa is five to six hours each way by road. None of them fits into three days without turning the trip into transport." },
    ],
    faqs: [
      { question: "Can I add Sapa to three days?", answer: "No. Sapa is five to six hours each way from Hanoi, so a visit needs two nights to be worth anything, and that is most of this itinerary. Anything sold as a Sapa day trip from Hanoi is a bus ride with a short stop in the middle." },
      { question: "Is a Ha Long day trip worth it, or should I skip it?", answer: "It is worth it. A day cruise gives you the bay at its busiest hour and in its flattest light, but the scenery still carries it. The alternative worth considering is moving a Hanoi night onto an overnight boat, which buys you sunset and dawn on the water after the day fleet has gone." },
      { question: "Which airport should I fly into?", answer: "Hanoi, Noi Bai. Flying into Ho Chi Minh City for a three-day trip means either a domestic flight each way or an entirely different itinerary in the south." },
    ],
  },

  '5-days': {
    days: 5,
    quickAnswer: "Five days in Vietnam works best as the north plus one flight south. Two days in Hanoi, one on Ha Long Bay, then fly to Da Nang for two days built around Hoi An's old town and My Son. The alternative is to stay north and give two nights to Sapa instead.",
    title: "5 Days in Vietnam: Hanoi, Ha Long and Hoi An",
    metaTitle: "5-Day Vietnam Itinerary: Hanoi, Ha Long Bay and Hoi An 2026",
    metaDescription: "Five days in Vietnam done two ways: the classic Hanoi, Ha Long and Hoi An run, or the northern route with two nights in Sapa. Flights, timings and the trade-offs.",
    routeSummary: "Hanoi → Ha Long Bay → fly to Da Nang → Hoi An",
    intro: "Five days is enough for two regions if you accept one internal flight. The usual shape is the north for three days and the centre for two, which pairs Vietnam's busiest city with its quietest old town. The alternative, staying north and adding Sapa, trades Hoi An for mountains and is the better choice in autumn.",
    bestFor: "A first trip that wants variety rather than depth, and travellers happy to fly once.",
    days_detail: [
      {
        day: 1,
        base: "Hanoi",
        heading: "Arrive and walk the Old Quarter",
        narrative: "Land, drop bags and get out on foot. The Old Quarter rewards wandering more than a list, and the first evening is the easiest time to start because the streets around Ta Hien fill up after seven and the city feels immediately legible.\n\nIf you land early enough, take a street food walk on the first evening rather than the last. It maps the neighbourhood for you and everything afterwards is easier.",
        tours: [`${U}/hanoi/small-group-street-food-walking-tour-in-hanoi`],
        travel: "Noi Bai airport to the Old Quarter: about 45 minutes",
        tip: "From Friday evening to Sunday night the streets around Hoan Kiem lake close to traffic and fill with families and street games. If your dates include a weekend, keep one evening for it.",
      },
      {
        day: 2,
        base: "Ha Long Bay",
        heading: "Overnight on the bay",
        narrative: "Take the overnight rather than the day cruise if the budget allows. The difference is not the boat, it is the hours: the day fleet leaves around four, and from then until the next morning the bay is quiet in a way no day trip reaches.\n\nThe afternoon runs a cave and a kayak stop, then the boat anchors for sunset. Dinner is aboard, squid fishing after for whoever stays up, and a morning activity before the run back.\n\nRead the itinerary rather than the title: a cruise called a Ha Long cruise may spend most of its time in quieter Lan Ha Bay, which is usually better.",
        tours: [`${U}/ha-long/2-day-ha-long-bay-boat-tour-cabin-with-ocean-view`, `${U}/ha-long/ha-long-and-bai-tu-long-bay-1-or-2-day-cruise`],
        travel: "Hanoi to Ha Long: about 2.5 hours by road",
        tip: "A private balcony is the upgrade people say afterwards was worth it, because the whole point is the hours when you are moored and everyone else is inside.",
      },
      {
        day: 3,
        base: "Hanoi → Da Nang",
        heading: "Back to Hanoi, then fly south",
        narrative: "The boat returns to the harbour late morning and you are back in Hanoi mid-afternoon. Take an evening flight to Da Nang — it is about an hour and fifteen minutes and they run frequently.\n\nDa Nang's airport is inside the city, and Hoi An is about forty-five minutes further by road. You will arrive late; book the transfer in advance rather than sorting it at the airport.\n\nStay in Hoi An rather than Da Nang unless you want a resort beach holiday.",
        tours: [`${U}/ha-long/2-day-ha-long-bay-cruise-and-ninh-binh-unesco-tour`],
        travel: "Ha Long to Hanoi by road, then Hanoi to Da Nang by air, about 1h15",
        tip: "Do not book the last flight of the day. If the cruise runs late — and bay weather can delay a return — there is nothing after it.",
      },
      {
        day: 4,
        base: "Hoi An",
        heading: "The ancient town, early and late",
        narrative: "Be out before eight. The old town is almost empty, the light is low and the market is working rather than performing. That hour is the best thing in Hoi An and it costs nothing.\n\nThe heritage ticket admits you to a set number of the protected buildings — Tan Ky house and the Fujian Assembly Hall are the two to spend entries on. Walking the streets themselves is free.\n\nSpend the hot middle of the day at An Bang beach or with a tailor, then come back at five when the lanterns come on and the day groups have gone.",
        tours: [`${U}/hoi-an/vietnamese-foldable-lantern-making-class-in-hoi-an`, `${U}/hoi-an/thanh-ha-village-tour-with-pottery-making-and-gift-in-hoi-an`],
        travel: null,
        tip: "If you want clothes made, order today, not tomorrow. Two full days is the realistic minimum for a suit and one fitting is not enough.",
      },
      {
        day: 5,
        base: "Hoi An",
        heading: "My Son at dawn, then home",
        narrative: "Take the earliest My Son departure. There is almost no shade in that valley and by ten in the morning it is punishing for most of the year; at dawn it is cool, quiet and far better lit.\n\nThe Cham brickwork is the thing to look at — built without visible mortar, and how they bonded it is still not fully settled. Restored sections give themselves away because the modern joints show.\n\nYou will be back in Hoi An by early afternoon, which leaves time for the beach or a last walk before the airport.",
        tours: [`${U}/hoi-an/my-son-early-morning-with-banh-my-and-coffee-6-am-in-hoi-an`, `${U}/hoi-an/my-son-morning-tour-with-quang-noodle-in-hoi-an`],
        travel: "Hoi An to Da Nang airport: about 45 minutes",
        tip: "Parts of My Son are missing because the valley was bombed during the war. Ask your guide about it — without that, the gaps look like ordinary decay and they are not.",
      },
    ],
    logistics: [
      { heading: "The one flight", content: "Hanoi to Da Nang is about an hour and fifteen minutes and runs many times a day on several carriers. Book it in advance rather than on arrival; the fares move sharply close in and the early flights fill first." },
      { heading: "The northern alternative", content: "Instead of flying south, stay north and give days three to five to Sapa: five to six hours each way by road, two nights minimum, and a valley trek in between. Better in September and October when the terraces are gold, worse from January to March when the valley sits inside cloud." },
      { heading: "Central Vietnam's weather is its own", content: "Hoi An's wet season is September to November, which is different from the north's. Autumn in Hanoi is the best time of year; in Hoi An it is the wettest, and the old town floods most years in October or November." },
    ],
    faqs: [
      { question: "Is five days enough for Vietnam?", answer: "For two regions, yes. For the whole country, no — Vietnam is about 1,600km end to end and the north, centre and south each need their own flight. Five days done as two regions is a good trip; five days done as four cities is four airports." },
      { question: "Should I skip Ha Long and go straight to Hoi An?", answer: "Only if the weather is against you. Between July and September the harbour authority can suspend sailings for typhoons, and a cancelled cruise on a five-day trip is a lost day. Outside those months, Ha Long earns its place." },
      { question: "Hoi An or Da Nang as a base?", answer: "Hoi An, for almost everyone. Da Nang is a modern coastal city with a long beach and an airport; Hoi An is the old town, and it is the reason people come to central Vietnam. Reverse it only if you want a resort holiday with a day trip attached." },
    ],
  },

  '7-days': {
    days: 7,
    quickAnswer: "Seven days covers Vietnam's three classic stops with two internal flights: three days in the north for Hanoi and an overnight on Ha Long Bay, two in the centre for Hoi An and My Son, and two in the south for Saigon and the Mekong Delta. It is the standard route because it works.",
    title: "7 Days in Vietnam: North to South",
    metaTitle: "7-Day Vietnam Itinerary: Hanoi, Hoi An and Saigon 2026",
    metaDescription: "The classic seven-day Vietnam route from Hanoi to Ho Chi Minh City, with an overnight on Ha Long Bay, Hoi An's old town and a Mekong Delta day. Flights and timings included.",
    routeSummary: "Hanoi → Ha Long Bay → fly to Da Nang → Hoi An → fly to Ho Chi Minh City → Mekong Delta",
    intro: "Seven days is the length Vietnam is built for. The country runs 1,600km north to south and the three regions are genuinely different — in food, in climate and in what the streets feel like. Two short domestic flights link them, and the route below is the one most first trips take because the alternatives cost more time in transit than they gain.",
    bestFor: "A complete first trip, and anyone who wants to understand why people talk about northern and southern Vietnam as different places.",
    days_detail: [
      {
        day: 1,
        base: "Hanoi",
        heading: "Arrive, and the Old Quarter after dark",
        narrative: "Land, and walk. The Old Quarter is small, dense and easiest to read in the evening when the food streets open and the pavements fill.\n\nA street food walk on the first night is worth more than on the last, because it teaches you the timing: most Hanoi stalls make one dish, have made it for decades, and stop when the pot is empty. Knowing which hour each thing is eaten in changes the rest of the trip.",
        tours: [`${U}/hanoi/old-quarter-street-food-tour-with-12-tastings-in-hanoi`, `${U}/hanoi/small-group-street-food-walking-tour-in-hanoi`],
        travel: "Noi Bai airport to the Old Quarter: about 45 minutes",
        tip: "Pho is breakfast here and bun cha is lunch, and most bun cha places stop serving in the early afternoon. That is not a quirk; it is how the city eats.",
      },
      {
        day: 2,
        base: "Hanoi",
        heading: "The city proper, or Ninh Binh",
        narrative: "Two ways to spend this. In the city: the Temple of Literature, the museums, the lake at dawn, and the craft streets in between.\n\nOr take Ninh Binh, which is the best day trip in northern Vietnam. Two hours each way, limestone karsts identical in geology to Ha Long's but seen from a small rowing boat on a river, and Mua Cave's staircase for the view over the whole valley.\n\nIf you are doing Ha Long tomorrow, the city day is the better choice — Ninh Binh and Ha Long back to back is more repetitive than it sounds.",
        tours: [`${U}/hanoi/guided-half-day-city-highlights-tour-with-transfers-in-hanoi`, `${U}/hanoi/bike-tour-through-hidden-gems-and-banana-island-in-hanoi`],
        travel: null,
        tip: "Book tomorrow's cruise transfer as a private one. The shared minibus collects from several hotels and reliably adds an hour at the start of the day.",
      },
      {
        day: 3,
        base: "Ha Long Bay",
        heading: "Overnight on the water",
        narrative: "This is the night that makes the difference. The day boats leave around four in the afternoon, and from then until the next morning the bay belongs to the handful of boats staying out.\n\nSunset from the deck, dinner aboard, and the karsts at dawn with mist between them — the image people come for, and one that is not available on a day trip.\n\nRead the itinerary rather than the name. Ha Long, Bai Tu Long and Lan Ha sit next to each other and are sold interchangeably; Lan Ha has the beaches, Bai Tu Long has fewer boats.",
        tours: [`${U}/ha-long/2-day-ha-long-bay-boat-tour-cabin-with-ocean-view`, `${U}/ha-long/2-day-ha-long-bay-cruise-and-ninh-binh-unesco-tour`],
        travel: "Hanoi to Ha Long: about 2.5 hours by road",
        tip: "Between July and September the harbour authority can stop all sailings for weather. Keep Ha Long early in the trip so a lost day can be moved.",
      },
      {
        day: 4,
        base: "Da Nang → Hoi An",
        heading: "Back to Hanoi, fly to the centre",
        narrative: "The boat docks late morning and you are in Hanoi by mid-afternoon. Fly to Da Nang in the early evening — about an hour and fifteen minutes.\n\nHoi An is forty-five minutes from the airport. Arrive, eat, and walk the old town at night: the lanterns are lit every evening, not only at festival, and the first sight of it lit is the one people remember.",
        tours: [`${U}/da-nang/transfer-from-da-nang-to-hoian-or-vice-versa`],
        travel: "Ha Long to Hanoi by road, then Hanoi to Da Nang by air, about 1h15",
        tip: "Do not take the last flight. A bay weather delay with nothing behind it strands you in Hanoi for the night.",
      },
      {
        day: 5,
        base: "Hoi An",
        heading: "Ancient town, beach, and a tailor if you want one",
        narrative: "Out before eight for the empty streets, then the heritage ticket for two or three of the old houses — Tan Ky and the Fujian Assembly Hall are the ones worth an entry.\n\nMiddle of the day at An Bang beach or with a tailor. If you want clothes made, this is the day to order: two full days and two fittings is the realistic minimum, and the twenty-four-hour turnaround everyone advertises is how the disappointments happen.\n\nBack out at five for the lanterns.",
        tours: [`${U}/hoi-an/vietnamese-foldable-lantern-making-class-in-hoi-an`, `${U}/hoi-an/coconut-basket-boat-ride-and-fishing-experience-in-hoi-an`],
        travel: null,
        tip: "Bring a garment you already love the fit of for the tailor to copy. Copying something real beats describing something imagined across a language gap.",
      },
      {
        day: 6,
        base: "Hoi An → Ho Chi Minh City",
        heading: "My Son at dawn, then fly south",
        narrative: "Earliest My Son departure, back by early afternoon, then the flight to Saigon — about an hour and twenty minutes.\n\nThe change is immediate. Saigon is bigger, louder, later and hotter, the food is sweeter and comes with a plate of herbs, and the city runs well into the night in a way Hanoi does not.\n\nEat late. The best street eating in Saigon starts after nine.",
        tours: [`${U}/hoi-an/my-son-early-morning-with-banh-my-and-coffee-6-am-in-hoi-an`, `${U}/ho-chi-minh-city/saigon-street-food-flower-market-and-old-apartment-tour`],
        travel: "Hoi An to Da Nang airport 45 minutes, then Da Nang to Ho Chi Minh City by air, about 1h20",
        tip: "Southern pho arrives with basil, bean sprouts and lime to add yourself. That is not a lesser version of the northern one; it is a different dish with the same name.",
      },
      {
        day: 7,
        base: "Ho Chi Minh City",
        heading: "Cu Chi or the Mekong, then out",
        narrative: "One big thing, not two. Cu Chi is north-west of the city; the Mekong is south. Doing both in a day is sold and is almost entirely road.\n\nCu Chi is the tunnel network, the trap systems and a stretch you can go down into — tight, hot and not for everyone, with exits at intervals that the guides point out before you enter.\n\nThe Mekong day reaches My Tho and Ben Tre: coconut groves, narrow canals by rowing boat, and workshops. Ben Tre is the quieter of the two.\n\nIf you have an evening flight, the War Remnants Museum in the city is the third option and needs only a couple of hours.",
        tours: [`${U}/ho-chi-minh-city/cu-chi-tunnels-tour-with-optional-shooting-range-in-ho-chi-minh-city`, `${U}/ho-chi-minh-city/hcm-mekong-delta-my-tho-and-ben-tre-coconut-village-ho-chi-minh-city`],
        travel: "Tan Son Nhat airport is inside the city, about 30 minutes from District 1 in traffic",
        tip: "The famous Cai Rang floating market is near Can Tho, four hours away and winding down by eight in the morning. It cannot be done as a day trip from Saigon, whatever the listing says.",
      },
    ],
    logistics: [
      { heading: "The two flights", content: "Hanoi to Da Nang and Da Nang to Ho Chi Minh City, roughly 1h15 and 1h20. Several carriers fly both many times a day. Book ahead, take morning or early-evening departures rather than the last of the day, and remember that Da Nang's airport is inside the city while Hoi An is 45 minutes further." },
      { heading: "Three climates, one suitcase", content: "In the same week Hanoi can be cool and damp, Hoi An hot and wet, and Saigon hot and dry. Pack light layers and something genuinely waterproof. Winter in the north surprises people: buildings are not heated, so 15°C is felt all day." },
      { heading: "Money and booking ahead", content: "Cash is still normal for street food and small operators, cards are fine in hotels and larger restaurants. Book the Ha Long cruise and the two flights before you arrive; everything else on this route can be arranged a day or two ahead." },
    ],
    faqs: [
      { question: "Is seven days enough to see Vietnam?", answer: "It is enough to see its three main regions properly, which is what most people mean. It is not enough to add Sapa, the Ha Giang loop or Phu Quoc — each of those needs two nights of its own, and squeezing one in turns a good week into a tiring one." },
      { question: "North to south, or south to north?", answer: "Either works and the flights are the same length. North to south is marginally better because Hanoi's compactness is an easier landing than Saigon's scale, and because ending in the south gives you the warmest weather at the end rather than the start." },
      { question: "Can I take the train instead of flying?", answer: "For the Da Nang to Hue stretch, yes, and it is one of the best rail rides in Asia. For Hanoi to Da Nang or Da Nang to Saigon, the train takes 15 to 20 hours against 90 minutes in the air. On a seven-day trip that is a day and a half you do not have." },
      { question: "Do I need a visa?", answer: "Most nationalities need either an e-visa applied for online in advance or fall under a short visa exemption, and the rules change from year to year. Check the current position for your passport before booking flights rather than after." },
    ],
  },

  '10-days': {
    days: 10,
    quickAnswer: "Ten days in Vietnam lets you add the mountains to the classic route. Three days in the north for Hanoi and Ha Long, two nights in Sapa for the valley treks, two in Hoi An for the old town and My Son, and two in the south for Saigon and the Mekong Delta, linked by two internal flights.",
    title: "10 Days in Vietnam: Hanoi, Sapa, Hoi An and the Mekong",
    metaTitle: "10-Day Vietnam Itinerary: North, Centre and South 2026",
    metaDescription: "Ten days in Vietnam covering Hanoi, an overnight on Ha Long Bay, two nights trekking in Sapa, Hoi An and My Son, and the Mekong Delta from Saigon.",
    routeSummary: "Hanoi → Ha Long Bay → Sapa → fly to Da Nang → Hoi An → fly to Ho Chi Minh City → Mekong Delta",
    intro: "Ten days is where Vietnam stops being a highlights run. The extra three days over the standard week buy the thing most first trips miss: the northern mountains, where the country looks least like its own postcards. The route still uses only two flights, and every long road transfer is one you sleep through or spend looking out of the window.",
    bestFor: "Travellers who want the classic route plus one region that most itineraries skip, and anyone who would rather walk than sightsee.",
    days_detail: [
      {
        day: 1,
        base: "Hanoi",
        heading: "Arrive and eat",
        narrative: "Land, drop bags, walk. The Old Quarter after dark is the easiest introduction to the city and a food walk on the first evening maps the neighbourhood for everything that follows.",
        tours: [`${U}/hanoi/small-group-street-food-walking-tour-in-hanoi`],
        travel: "Noi Bai airport to the Old Quarter: about 45 minutes",
        tip: "Sleep early. Tomorrow starts before eight, because Hanoi does.",
      },
      {
        day: 2,
        base: "Hanoi",
        heading: "The city, properly",
        narrative: "The lake at dawn, the Temple of Literature before the heat, the museums through the middle of the day, and the craft streets in the late afternoon.\n\nThe trade-street system is the thing to notice: each street was a guild and most still sell roughly what they always sold. Walk a few blocks and watch the goods on both sides change at every junction.",
        tours: [`${U}/hanoi/guided-half-day-city-highlights-tour-with-transfers-in-hanoi`, `${U}/hanoi/war-site-museums-tour-in-hanoi`],
        travel: null,
        tip: "If your dates include a weekend, the streets around Hoan Kiem close to traffic from Friday evening. Keep that night free.",
      },
      {
        day: 3,
        base: "Ha Long Bay",
        heading: "Overnight on the bay",
        narrative: "Afternoon on the water, a cave and a kayak stop, then the boat anchors for sunset once the day fleet has gone. Dinner aboard, and the karsts at dawn with mist sitting between them.\n\nThis is the night the whole Ha Long question turns on, and it is why a day trip is a compromise rather than a version.",
        tours: [`${U}/ha-long/2-day-ha-long-bay-boat-tour-cabin-with-ocean-view`, `${U}/ha-long/ha-long-and-bai-tu-long-bay-1-or-2-day-cruise`],
        travel: "Hanoi to Ha Long: about 2.5 hours by road",
        tip: "Put Ha Long early in a long trip. If weather cancels it, a ten-day itinerary has room to move it; a seven-day one does not.",
      },
      {
        day: 4,
        base: "Sapa",
        heading: "Back through Hanoi and up into the hills",
        narrative: "The boat docks late morning, and from Hanoi it is five to six hours to Sapa on the expressway — a sleeper bus with flat berths, or a limousine van with proper seats and hotel pickup.\n\nArrive in the evening. Sapa town itself has been built up hard and is not the reason to come; the valley below it is. Eat, sleep, and start early.",
        tours: [`${U}/sapa/transfer-to-or-from-sapa-by-a-vip-sleeper-bus`],
        travel: "Ha Long to Hanoi by road, then Hanoi to Sapa, about 5-6 hours",
        tip: "The last climb into Sapa is continuous tight bends and affects people who are usually fine on buses. Take something before you leave rather than when you start to feel it.",
      },
      {
        day: 5,
        base: "Sapa",
        heading: "The Muong Hoa valley on foot",
        narrative: "The classic walk drops from the town through Y Linh Ho, Lao Chai and Ta Van, following the valley with terraces on both sides. About six hours with lunch, mostly downhill.\n\nNothing about it is technical. What makes it hard is surface: the paths are clay, and wet clay on a descent is genuinely slippery. Shoes with grip matter more than fitness.\n\nGuides are mostly H'mong and Red Dao women from the villages you walk through, which is the difference between a walk and a day in someone's home ground.",
        tours: [`${U}/sapa/trekking-to-y-linh-ho-lao-chai-and-ta-van-villages-in-sapa`, `${U}/sapa/sapa-1-day-trekking-tour-rice-terraces-and-villages-sapa`],
        travel: null,
        tip: "Tell your guide early if you want a slower pace. The route can be shortened at the start, not three hours down the valley.",
      },
      {
        day: 6,
        base: "Sapa → Hanoi",
        heading: "Fansipan or a second valley, then the road back",
        narrative: "Two good options. The cable car climbs to near the summit of Fansipan in about fifteen minutes, covering ground that used to take a day and a half — remarkable above the cloud, and a white room inside it. Note that it stops at an upper station, and it is around six hundred steps from there to the top unless you take the funicular.\n\nOr take a second, quieter trek towards Su Pan or Giang Ta Chai, with fewer people on the path.\n\nEvening bus back to Hanoi, arriving late.",
        tours: [`${U}/sapa/t-van-to-su-pan-guided-trek-with-local-guide-in-sapa`, `${U}/sapa/walking-food-tour-with-local-guide-in-sapa`],
        travel: "Sapa to Hanoi: about 5-6 hours",
        tip: "If the mountain is under cloud when you wake, switch the plan and walk instead. Mornings are clearer than afternoons here in every season.",
      },
      {
        day: 7,
        base: "Da Nang → Hoi An",
        heading: "Fly to the centre",
        narrative: "A morning flight to Da Nang, about an hour and fifteen minutes, then forty-five minutes by road to Hoi An.\n\nYou arrive with the afternoon intact. Spend it at An Bang beach, then walk the old town after five when the lanterns are lit and the day groups have left.",
        tours: [`${U}/hoi-an/hoi-an-private-lantern-cruise-by-romantic-sunset-night-hoi-an`],
        travel: "Hanoi to Da Nang by air, about 1h15, then 45 minutes by road",
        tip: "Order anything you want tailored today. Two full days and two fittings is the honest minimum.",
      },
      {
        day: 8,
        base: "Hoi An",
        heading: "The ancient town and My Son",
        narrative: "My Son on the earliest departure, back by early afternoon. The valley has almost no shade and by ten in the morning it is punishing; at dawn it is cool and quiet.\n\nBack in Hoi An, use the heritage ticket on two or three of the old houses, then the middle of the day somewhere cool, then the town again at five.\n\nIf a full moon falls in your stay, the old town turns off its electric lights on the fourteenth night of the lunar month and lights lanterns instead. It happens monthly, not annually.",
        tours: [`${U}/hoi-an/my-son-early-morning-with-banh-my-and-coffee-6-am-in-hoi-an`, `${U}/hoi-an/thanh-ha-village-tour-with-pottery-making-and-gift-in-hoi-an`],
        travel: null,
        tip: "Hoi An floods most years in October or November. If your dates fall then, keep the plan loose rather than booking one unmissable thing for a fixed date.",
      },
      {
        day: 9,
        base: "Ho Chi Minh City",
        heading: "Fly south, and the city at night",
        narrative: "Late morning flight to Saigon, about an hour and twenty minutes. The change is immediate: bigger, louder, later, hotter.\n\nSpend the afternoon on the War Remnants Museum or the old apartment blocks on Nguyen Hue, and the evening eating. Saigon's good street food is spread across districts rather than concentrated in one quarter, which is why the motorbike food tours took hold here — you ride pillion and cover ground you could not walk.",
        tours: [`${U}/ho-chi-minh-city/saigon-street-food-flower-market-and-old-apartment-tour`, `${U}/ho-chi-minh-city/iconic-apartments-walking-tour-in-ho-chi-minh-city`],
        travel: "Da Nang to Ho Chi Minh City by air, about 1h20",
        tip: "Banh mi is better in the south, and the reason is the bread. Start there.",
      },
      {
        day: 10,
        base: "Ho Chi Minh City",
        heading: "The Mekong Delta, then home",
        narrative: "A delta day reaches My Tho and Ben Tre, about two hours out: coconut groves, narrow canals by rowing boat, and workshops making coconut candy and rice paper. Ben Tre is the quieter of the two and the better choice.\n\nThe difference between good and poor Mekong tours is pace, not content. A good one does four things properly; a poor one lists seven and gives you fifteen minutes at each, most of it ending at a shop counter.\n\nBack in the city by early evening, which works for a night flight.",
        tours: [`${U}/ho-chi-minh-city/hcm-mekong-delta-my-tho-and-ben-tre-coconut-village-ho-chi-minh-city`, `${U}/ho-chi-minh-city/hcm-city-mekong-delta-tour-with-sampan-ride-and-local-lunch-ho-chi-minh-city`],
        travel: "About 2 hours each way to the delta; Tan Son Nhat airport is inside the city",
        tip: "Small-group Mekong tours cost more and are the whole difference, because the rowing boats seat a handful of people and a large group means waiting in the sun for your turn.",
      },
    ],
    logistics: [
      { heading: "Two flights, one long road", content: "Hanoi to Da Nang and Da Nang to Ho Chi Minh City are the only flights. Sapa is reached by road — five to six hours each way — which is why it needs two nights rather than one, and why it sits between Ha Long and the flight south rather than at the end." },
      { heading: "Season, and which region suffers", content: "There is no month that is good everywhere. October and November are the best of the year in Hanoi and Sapa and the wettest in Hoi An. February to April is dry in the centre and can be grey and drizzly in the north. Pick for the region you care most about." },
      { heading: "What to add if you have more time", content: "Two more days would go to the Ha Giang loop north of Sapa, which is the finest motorbike road in the country, or to Phu Quoc if you want the trip to end on a beach. Neither fits into ten days without cutting something already here." },
    ],
    faqs: [
      { question: "Is Sapa worth three days of a ten-day trip?", answer: "If you like walking, yes — it is the part of Vietnam that looks least like everywhere else, and the valley trek is what people remember afterwards. If you would rather sightsee than hike, spend those days on Hue and the Hai Van Pass instead, which sits between Hanoi and Hoi An on the same route." },
      { question: "Can I do Sapa as a day trip and save two days?", answer: "No. It is five to six hours each way, so a day trip is ten to twelve hours in a seat for a few hours in the hills. Two nights is the minimum that gives you two mornings, and mornings are when the valley is clear." },
      { question: "Should I add Hue?", answer: "Hue sits between Da Nang and the north and has the imperial citadel and the tombs along the Perfume River. It is a natural addition if you are travelling by road or rail between Hoi An and further north, and an awkward one if you are flying past it, which this route does." },
      { question: "How much should I budget?", answer: "Vietnam is inexpensive by regional standards outside the cruise. The two internal flights and the Ha Long boat are the significant line items; food, local transport and guided days are all modest, and street food for two costs less than a coffee in most Western cities." },
    ],
  },
};
